- .github/scripts/test-online-transducer.sh
- .github/workflows/linux.yaml
- .gitignore
- build-aarch64-linux-gnu.sh
- c-api-examples/Makefile
- c-api-examples/decode-file-c-api.c
- c-api-examples/run.sh
- cmake/portaudio.cmake
- ffmpeg-examples/Makefile
- ffmpeg-examples/README.md
- ffmpeg-examples/how-to-fix-errors.md
- ffmpeg-examples/run.sh
- ffmpeg-examples/sherpa-onnx-ffmpeg.c
Fixes #44 
Code is modified from
https://github.com/k2-fsa/sherpa-ncnn/tree/master/ffmpeg-examples
Thanks again to @begeekmyfriend
> Add ffmpeg example

- android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt
- ios-swift/SherpaOnnx/SherpaOnnx/ViewController.swift
- sherpa-onnx/csrc/cat.cc
- sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc
- sherpa-onnx/csrc/onnx-utils.cc
- sherpa-onnx/csrc/onnx-utils.h
- sherpa-onnx/csrc/unbind.cc
After fixing this bug, it works perfectly on iOS and Android.
> Use deep copy in Clone()

- .github/scripts/.gitignore
- .github/scripts/Main.kt
- .gitignore
- android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt
- android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt
- ios-swift/SherpaOnnx/SherpaOnnx/ViewController.swift
- sherpa-onnx/c-api/c-api.cc
- sherpa-onnx/c-api/c-api.h
- sherpa-onnx/csrc/features.cc
- sherpa-onnx/csrc/features.h
- sherpa-onnx/csrc/sherpa-onnx-microphone.cc
- sherpa-onnx/csrc/sherpa-onnx.cc
- sherpa-onnx/jni/jni.cc
- swift-api-examples/SherpaOnnx.swift
- swift-api-examples/decode-file.swift
Also, it changes the type of sampling rate from float to int.
> Fix modified beam search for iOS and android

- CMakeLists.txt
- bug fixes
- support modified beam search
- support resampling
- support android armv7-eabi
> Release v1.3.0

- python-api-examples/online-websocket-client-microphone.py
add "import sys"，solve "NameError: name 'sys' is not defined".
> add "import sys",

- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/macros.h
- sherpa-onnx/csrc/offline-recognizer-impl.cc
- sherpa-onnx/csrc/offline-recognizer-impl.h
- sherpa-onnx/csrc/offline-recognizer-transducer-impl.h
- sherpa-onnx/csrc/offline-recognizer.cc
- sherpa-onnx/csrc/offline-recognizer.h
- sherpa-onnx/csrc/text-utils.cc
- sherpa-onnx/csrc/text-utils.h
The purpose is to make it easier to support different types of models.
> Refactor offline recognizer.

- .github/scripts/test-offline-transducer.sh
- .github/workflows/windows-x64.yaml
- .github/workflows/windows-x86.yaml
- .gitignore
- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/macros.h
- sherpa-onnx/csrc/offline-model-config.cc
- sherpa-onnx/csrc/offline-model-config.h
- sherpa-onnx/csrc/offline-paraformer-decoder.h
- sherpa-onnx/csrc/offline-paraformer-greedy-search-decoder.cc
- sherpa-onnx/csrc/offline-paraformer-greedy-search-decoder.h
- sherpa-onnx/csrc/offline-paraformer-model-config.cc
- sherpa-onnx/csrc/offline-paraformer-model-config.h
- sherpa-onnx/csrc/offline-paraformer-model.cc
- sherpa-onnx/csrc/offline-paraformer-model.h
- sherpa-onnx/csrc/offline-recognizer-impl.cc
- sherpa-onnx/csrc/offline-recognizer-paraformer-impl.h
- sherpa-onnx/csrc/offline-recognizer-transducer-impl.h
- sherpa-onnx/csrc/offline-recognizer.cc
- sherpa-onnx/csrc/offline-recognizer.h
- sherpa-onnx/csrc/offline-stream.cc
- sherpa-onnx/csrc/offline-stream.h
- sherpa-onnx/csrc/offline-transducer-model-config.cc
- sherpa-onnx/csrc/offline-transducer-model-config.h
- sherpa-onnx/csrc/offline-transducer-model.cc
- sherpa-onnx/csrc/offline-transducer-model.h
- sherpa-onnx/csrc/onnx-utils.cc
- sherpa-onnx/csrc/onnx-utils.h
- sherpa-onnx/csrc/sherpa-onnx-offline.cc
> Support paraformer.

- sherpa-onnx/csrc/offline-recognizer-impl.cc
Fix a bug for supporting zipformer.
> Add zipformer model_type

- python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py
- python-api-examples/speech-recognition-from-microphone.py
chinese characters can normal show in console
> fix garbled console output with chinese characters

- python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py
- python-api-examples/speech-recognition-from-microphone.py
> remove sherpa_onnx.Display

- python-api-examples/offline-decode-files.py
- sherpa-onnx/csrc/offline-recognizer.h
- sherpa-onnx/csrc/offline-stream.h
- sherpa-onnx/python/csrc/CMakeLists.txt
- sherpa-onnx/python/csrc/offline-model-config.cc
- sherpa-onnx/python/csrc/offline-model-config.h
- sherpa-onnx/python/csrc/offline-paraformer-model-config.cc
- sherpa-onnx/python/csrc/offline-paraformer-model-config.h
- sherpa-onnx/python/csrc/offline-recognizer.cc
- sherpa-onnx/python/csrc/offline-recognizer.h
- sherpa-onnx/python/csrc/offline-stream.cc
- sherpa-onnx/python/csrc/offline-stream.h
- sherpa-onnx/python/csrc/offline-transducer-model-config.cc
- sherpa-onnx/python/csrc/offline-transducer-model-config.h
- sherpa-onnx/python/csrc/sherpa-onnx.cc
- sherpa-onnx/python/sherpa_onnx/__init__.py
- sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
you can use python-api-examples/offline-decode-files.py decoding wav-files by onnx model.
> adding a python api for offline decode

- CMakeLists.txt
- release.sh
- Also release precompiled libs for Android and iOS.
> Release v1.4.1

- java-api-examples/Makefile
- java-api-examples/README.md
- java-api-examples/src/DecodeMic.java
java decode example for microphone
Ubuntu 18.04
> java decode example for microphone

- sherpa-onnx/csharp-api/online-api.cc
- sherpa-onnx/csharp-api/online-api.h
Modify 'struct SherpaOnnxOnlineRecognizerConfig' body，
add 'struct SherpaOnnxOnlineModelConfig',
and modify method name : 'AcceptWaveform'->'AcceptOnlineWaveform'.
> add online-api for csharp-api

- CMakeLists.txt
- bugfixes
- java websocket server
- python streaming websocket server
> Release v1.4.4

- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/online-transducer-model.cc
- sherpa-onnx/csrc/online-zipformer2-transducer-model.cc
- sherpa-onnx/csrc/online-zipformer2-transducer-model.h
It works but the code is not clean enough. I will refactor the code later
> support streaming zipformer2

- sherpa-onnx/python/csrc/online-recognizer.cc
- sherpa-onnx/python/sherpa_onnx/online_recognizer.py
Implemented tokens and timestamps in Python API. Tested on Linux.
> Implemented tokens and timestamps in Python API

- sherpa-onnx/python/sherpa_onnx/utils.py
See also https://github.com/k2-fsa/sherpa/pull/433
Thanks to @shaynemei
> Fix setting context lists.

- mfc-examples/StreamingSpeechRecognition/StreamingSpeechRecognitionDlg.cpp
The path was hardcoded before. This PR fixes that.
> small fixes for MFC examples

- CMakeLists.txt
- Add non-streaming speech recognition examples for MFC
- Reduce initialization time for non-streaming models
> release-v1.5.2

- android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt
- ios-swift/SherpaOnnx/SherpaOnnx/Model.swift
- ios-swiftui/SherpaOnnx/SherpaOnnx/Model.swift
- scripts/dotnet/online.cs
- sherpa-onnx/c-api/c-api.h
- sherpa-onnx/jni/jni.cc
- swift-api-examples/SherpaOnnx.swift
> Fix model_type for jni, c# and iOS.

- CMakeLists.txt
Add go-api-examples.
Tested on the following platforms
- Linux (x86_64, aarch64, arm)
- Windows (x86_64, x86)
- macOS (x86_64, aarch64)
> Release v1.5.4

- java-api-examples/modelconfig.cfg
- java-api-examples/src/DecodeFile.java
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OnlineRecognizer.java
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OnlineTransducerModelConfig.java
next I will try build a CI pipeline for github action.
> Java api update for adding modelType in config class

- python-api-examples/speech-recognition-from-microphone.py
Try supporting real time hot words function on python. Test locally, both Chinese and English hot words work well.
> Support real time hotwords on python

- CMakeLists.txt
- sherpa-onnx/csrc/offline-transducer-greedy-search-decoder.cc
- sherpa-onnx/csrc/offline-transducer-modified-beam-search-decoder.cc
- sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc
- sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.cc
See also
- https://github.com/k2-fsa/icefall/issues/1206
- https://github.com/k2-fsa/icefall/issues/1208
Note: This is a bug fix and please update your sherpa-onnx.
> Fix initial tokens for decoding

- .github/workflows/linux-gpu.yaml
- cmake/onnxruntime-linux-x86_64-gpu.cmake
- cmake/onnxruntime-win-x64-gpu.cmake
- sherpa-onnx/csrc/CMakeLists.txt
> fix building on linux with GPU

- go-api-examples/real-time-speech-recognition-from-microphone/main.go
> fix go build error

- sherpa-onnx/csrc/online-recognizer-transducer-impl.h
Reinitialize context state after Reset stream when using contexts, so as to make contexts work again after reset.
> Reinitialize context state after Reset stream when using contexts

- android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt
- android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt
- sherpa-onnx/csrc/online-recognizer-paraformer-impl.h
- sherpa-onnx/jni/jni.cc
You can find the pre-built APK at
https://huggingface.co/csukuangfj/sherpa-onnx-apk/tree/main
It can can be downloaded with the following URL:
https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/20230814-int8-paraformer-cpu.apk
----
> Support paraformer on Android

- .github/workflows/macos.yaml
- CMakeLists.txt
- setup.py
See #270 
This PR should fix it after releasing v1.7.6
> Fix pip install on Windows for Python 3.11

- java-api-examples/Makefile
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OnlineRecognizer.java
> update Makefile for paraformer java

- CMakeLists.txt
- android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt
Use a model type that matches the one listed in the documentation.
https://k2-fsa.github.io/sherpa/onnx/android/build-sherpa-onnx.html#download-pre-trained-models
> Fix building APK

- sherpa-onnx/c-api/c-api.cc
- sherpa-onnx/c-api/c-api.h
- sherpa-onnx/csrc/hypothesis.cc
- sherpa-onnx/csrc/silero-vad-model-config.h
- swift-api-examples/.gitignore
- swift-api-examples/SherpaOnnx.swift
- swift-api-examples/decode-file-non-streaming.swift
- swift-api-examples/generate-subtitles.swift
- swift-api-examples/run-generate-subtitles.sh
Note that it can be used as a basis to write an iOS app.
> Add Swift example for generating subtitles

- CMakeLists.txt
- python-api-examples/offline-tts.py
- sherpa-onnx/csrc/lexicon.cc
- sherpa-onnx/csrc/lexicon.h
- sherpa-onnx/csrc/offline-tts-vits-impl.h
- sherpa-onnx/csrc/offline-tts-vits-model.cc
- sherpa-onnx/csrc/offline-tts-vits-model.h
- sherpa-onnx/csrc/sherpa-onnx-offline-tts.cc
and also support punctuations in vits chinese models.
> Validate input sid

- android/SherpaOnnxTts/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt
- sherpa-onnx/csrc/lexicon.cc
- sherpa-onnx/csrc/lexicon.h
We have converted the following model from [piper](https://github.com/rhasspy/piper):
https://huggingface.co/rhasspy/piper-voices/tree/main/de/de_DE/thorsten/medium
The colab for the conversion can be found at
https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/piper/convert_de_DE_thorsten_medium.ipynb
You can find the converted model at
https://huggingface.co/csukuangfj/vits-piper-de_DE-thorsten-medium/tree/main
You can try it at
https://huggingface.co/spaces/k2-fsa/text-to-speech
https://github.com/k2-fsa/sherpa-onnx/assets/5284924/024ee380-2fb8-4e72-96d5-cf3e7cc0e3fe
> Support German TTS

- dotnet-examples/TTS/PlayAudioPartial/SherpaOnnxGeneratedAudioResultPlayAudio.cs
- dotnet-examples/TTS/Program.cs
- dotnet-examples/TTS/Struct/SherpaOnnxGeneratedAudio.cs
- dotnet-examples/TTS/Struct/SherpaOnnxOfflineTtsConfig.cs
- dotnet-examples/TTS/Struct/SherpaOnnxOfflineTtsModelConfig.cs
- dotnet-examples/TTS/Struct/SherpaOnnxOfflineTtsVitsModelConfig.cs
- dotnet-examples/TTS/TTSCore.cs
Program.cs 示例代码，包含了文字转语音，在线播放，音字同步等
PlayAudioPartial/SherpaOnnxGeneratedAudioResultPlayAudio.cs  这个文件扩展了可以在线播放的代码，依赖NAudio库
> 添加C# TTS api

- sherpa-onnx/csrc/lexicon.cc
- sherpa-onnx/csrc/lexicon.h
Text:
```
招商银行欢迎你! 欢迎莅临我行调研指导工作。行政领导接待。
```
Generated audio
https://github.com/k2-fsa/sherpa-onnx/assets/5284924/bf33686a-db65-4c61-b62a-59a24cff1254
> Support Chinese polyphones in TTS

- CMakeLists.txt
- sherpa-onnx/csrc/lexicon.cc
- sherpa-onnx/csrc/offline-tts-vits-model.cc
Support VITS models from https://github.com/coqui-ai/TTS
---
You can find a colab notebook below about how to convert VITS models from  https://github.com/coqui-ai/TTS
https://colab.research.google.com/drive/1cI9VzlimS51uAw4uCR-OBeSXRPBc4KoK?usp=sharing
> Support VITS TTS models from coqui-ai/TTS

- scripts/apk/generate-tts-apk-script.py
Support building Android APKs for VITS models from
https://github.com/coqui-ai/TTS
Please see
https://k2-fsa.github.io/sherpa/onnx/tts/apk.html
> Build Android APKs for VITS models from Coqui-ai/TTS

- cmake/cmake_extension.py
- setup.py
- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/sherpa-onnx-vad-microphone-offline-asr.cc
You can find a video demo for this PR at the following address
https://www.bilibili.com/video/BV1Pb4y1g7n2/
> Add a C++ example to show streaming VAD + non-streaming ASR.

- .github/workflows/aarch64-linux-gnu-shared.yaml
- .github/workflows/aarch64-linux-gnu-static.yaml
- .github/workflows/arm-linux-gnueabihf.yaml
- .github/workflows/linux.yaml
- .github/workflows/mfc.yaml
- sherpa-onnx/csrc/lexicon.cc
Also, strip binaries on Linux before uploading.
> Build MFC examples for Windows x86 (Win32)

- scripts/apk/generate-tts-apk-script.py
See also
https://github.com/rhasspy/piper/issues/187
> Add two GLaDOS TTS models

- CMakeLists.txt
- cmake/cmake_extension.py
- setup.py
- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/alsa-play.cc
- sherpa-onnx/csrc/alsa-play.h
- sherpa-onnx/csrc/sherpa-onnx-offline-tts-play-alsa.cc
Tested on Raspberry Pi and it works very well.
> Play generated audio using alsa for TTS

- sherpa-onnx/python/csrc/offline-recognizer.cc
- sherpa-onnx/python/csrc/offline-tts.cc
- sherpa-onnx/python/csrc/online-recognizer.cc
- sherpa-onnx/python/csrc/voice-activity-detector.cc
> Release Python GIL in C++ class constructor

- .github/workflows/apk-tts-engine.yaml
- CMakeLists.txt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/GetSampleText.kt
- scripts/apk/build-apk-tts-engine.sh.in
- scripts/apk/build-apk-tts.sh.in
- scripts/apk/generate-tts-apk-script.py
You can find them at
https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html
> Build text-to-speech engine APKs

- sherpa-onnx/csrc/features.cc
- sherpa-onnx/csrc/offline-stream.cc
> Use high_freq -400 in computing fbank features.

- .github/workflows/export-3dspeaker-to-onnx.yaml
- scripts/3dspeaker/README.md
- scripts/3dspeaker/export-onnx.py
- scripts/3dspeaker/run.sh
- scripts/3dspeaker/test-onnx.py
- scripts/wespeaker/add_meta_data.py
- scripts/wespeaker/test.py
- sherpa-onnx/csrc/speaker-embedding-extractor-wespeaker-impl.h
- sherpa-onnx/csrc/speaker-embedding-extractor-wespeaker-model-metadata.h
- sherpa-onnx/csrc/speaker-embedding-extractor-wespeaker-model.cc
Now you can export models from https://github.com/alibaba-damo-academy/3D-Speaker to ONNX.
This PR should fix the following issue:
- https://github.com/alibaba-damo-academy/3D-Speaker/issues/16
I am adding C++ runtime for it in the coming pull-request.
> Support exporting models to onnx from 3D-Speaker

- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt
Here is the screenshot of the UI after the refactor.
> Refactor the UI of Android TTS engine

- cmake/asio.cmake
- cmake/cargs.cmake
- cmake/eigen.cmake
- cmake/espeak-ng-for-piper.cmake
- cmake/googletest.cmake
- cmake/kaldi-decoder.cmake
- cmake/kaldi-native-fbank.cmake
- cmake/kaldifst.cmake
- cmake/onnxruntime-linux-aarch64-static.cmake
- cmake/onnxruntime-linux-aarch64.cmake
- cmake/onnxruntime-linux-arm-static.cmake
- cmake/onnxruntime-linux-arm.cmake
- cmake/onnxruntime-linux-x86_64-gpu.cmake
- cmake/onnxruntime-linux-x86_64-static.cmake
- cmake/onnxruntime-linux-x86_64.cmake
- cmake/onnxruntime-osx-arm64-static.cmake
- cmake/onnxruntime-osx-arm64.cmake
- cmake/onnxruntime-osx-universal-static.cmake
- cmake/onnxruntime-osx-universal.cmake
- cmake/onnxruntime-osx-x86_64-static.cmake
- cmake/onnxruntime-osx-x86_64.cmake
- cmake/onnxruntime-win-x64-gpu.cmake
- cmake/onnxruntime-win-x64-static.cmake
- cmake/onnxruntime-win-x64.cmake
- cmake/onnxruntime-win-x86-static.cmake
- cmake/onnxruntime-win-x86.cmake
- cmake/piper-phonemize.cmake
- cmake/portaudio.cmake
- cmake/pybind11.cmake
- cmake/websocketpp.cmake
See also
https://stackoverflow.com/questions/32028667/are-cmake-source-dir-and-project-source-dir-the-same-in-cmake
> Fix cmake variables to point to the project root directory.

- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt
> Ensure input for speaker ID is a valid number.

- CMakeLists.txt
- android/SherpaOnnxTtsEngine/app/src/main/AndroidManifest.xml
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/TtsEngine.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/TtsService.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/TtsViewModel.kt
Now you don't need to start the APP to use the TTS engine.
You can use the TTS engine directly without any issues with this issue.
Please download the APK for v1.9.9.
> Run TTS engine service without starting the app.

- scripts/apk/generate-tts-apk-script.py
See also
https://github.com/k2-fsa/sherpa-onnx/issues/524#issuecomment-1913120448
---
We have updated the APK download page. Please see
---
You can also try it at
https://huggingface.co/spaces/k2-fsa/text-to-speech
> Add a new Persian tts model

- dotnet-examples/offline-tts/run-aishell3.sh
- dotnet-examples/offline-tts/run-piper.sh
wget is not available on Windows in GitHub actions
> Use curl to replace wget for Windows.

- .github/workflows/export-whisper-to-onnx.yaml
- scripts/whisper/export-onnx.py
- scripts/whisper/test.py
You can find the code for fine-tuning whisper on aishell
at https://github.com/k2-fsa/icefall/pull/1466
The converted model can be found at
https://huggingface.co/csukuangfj/sherpa-onnx-whisper-medium-aishell/tree/main
You can also try it in the following huggingface space
https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition-with-whisper
> Add fine-tuned whisper model on aishell

- build-android-arm64-v8a.sh
- build-android-armv7-eabi.sh
- build-android-x86-64.sh
- build-android-x86.sh
It does not need to use git lfs any longer.
> Download android onnxruntime libs from github.

- .github/workflows/linux.yaml
- cmake/onnxruntime-linux-x86_64-static.cmake
- cmake/piper-phonemize.cmake
> Use onnxruntime static lib compiled with gcc8 on unbuntu 20.04

- .github/workflows/run-python-test.yaml
- .github/workflows/wasm-simd-hf-space-de-tts.yaml
- .github/workflows/wasm-simd-hf-space-en-tts.yaml
You can find the two spaces on ModelScope for TTS below.
https://modelscope.cn/studios/k2-fsa/web-assembly-tts-sherpa-onnx-en/summary
https://modelscope.cn/studios/k2-fsa/web-assembly-tts-sherpa-onnx-de/summary
> Publish wasm tts to model scope.

- .github/workflows/wasm-simd-hf-space-de-tts.yaml
- .github/workflows/wasm-simd-hf-space-en-asr-zipformer.yaml
- .github/workflows/wasm-simd-hf-space-en-tts.yaml
- .github/workflows/wasm-simd-hf-space-zh-cantonese-en-asr-paraformer.yaml
- .github/workflows/wasm-simd-hf-space-zh-en-asr-paraformer.yaml
- .github/workflows/wasm-simd-hf-space-zh-en-asr-zipformer.yaml
The model supports 3 languages:
- Chinese
- Cantonese
- English
You can find the huggingface space at
https://huggingface.co/spaces/k2-fsa/web-assembly-asr-sherpa-onnx-zh-cantonese-en-paraformer
If you are from China, you can also visit
https://modelscope.cn/studios/k2-fsa/web-assembly-asr-sherpa-onnx-zh-cantonese-en-paraformer/summary
--
We also disable uploading files to model scope from github actions since it causes errors. Looks like model scope forbids
uploading large files to it with git lfs outside of China.
> Add WebAssembly demo for streaming trilingual Paraformer (Chinese+Cantonese+English)

- CMakeLists.txt
- python-api-examples/speech-recognition-from-microphone-with-endpoint-detection-alsa.py
- sherpa-onnx/csrc/session.cc
- sherpa-onnx/csrc/sherpa-onnx-alsa-offline-speaker-identification.cc
- sherpa-onnx/csrc/sherpa-onnx-alsa-offline.cc
- sherpa-onnx/csrc/sherpa-onnx-keyword-spotter-alsa.cc
- sherpa-onnx/python/csrc/CMakeLists.txt
- sherpa-onnx/python/csrc/alsa.cc
- sherpa-onnx/python/csrc/alsa.h
- sherpa-onnx/python/csrc/faked-alsa.cc
- sherpa-onnx/python/csrc/sherpa-onnx.cc
- sherpa-onnx/python/sherpa_onnx/__init__.py
This is for Linux users, especially for embedded Linux users, since only alsa is known to 100% work for them.
> Add Python ASR examples with alsa

- .github/workflows/aarch64-linux-gnu-shared.yaml
- .github/workflows/aarch64-linux-gnu-static.yaml
- .github/workflows/android.yaml
- .github/workflows/arm-linux-gnueabihf.yaml
- .github/workflows/dot-net.yaml
- .github/workflows/linux-gpu.yaml
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- .github/workflows/mfc.yaml
- .github/workflows/release-go.yaml
- .github/workflows/riscv64-linux.yaml
- .github/workflows/run-python-test.yaml
- .github/workflows/test-dot-net-nuget.yaml
- .github/workflows/test-dot-net.yaml
- .github/workflows/windows-x64-cuda.yaml
- .github/workflows/windows-x64.yaml
- .github/workflows/windows-x86.yaml
- cmake/kaldi-native-fbank.cmake
- dotnet-examples/offline-decode-files/run-hotwords.sh
- dotnet-examples/offline-decode-files/run-zipformer.sh
- dotnet-examples/online-decode-files/Program.cs
- dotnet-examples/online-decode-files/run-transducer.sh
- scripts/dotnet/online.cs
- sherpa-onnx/c-api/c-api.cc
- sherpa-onnx/c-api/c-api.h
- sherpa-onnx/csrc/online-zipformer2-transducer-model.h
> Add timestamps and tokens for .Net's online models.

- .github/workflows/aarch64-linux-gnu-shared.yaml
- .github/workflows/aarch64-linux-gnu-static.yaml
- .github/workflows/android.yaml
- .github/workflows/arm-linux-gnueabihf.yaml
- .github/workflows/build-xcframework.yaml
- .github/workflows/linux.yaml
- .github/workflows/riscv64-linux.yaml
- .github/workflows/windows-x64.yaml
- .github/workflows/windows-x86.yaml
- CMakeLists.txt
It uses CentOS 7 to build sherpa-onnx in CI.
> Use manylinux in CI test

- cmake/openfst.cmake
1. When compiling locally, openfst is missing.so add this file to the sherpa-onnx/cmake folder
> add openfst.cmake file

- .github/workflows/apk-tts-engine.yaml
- .github/workflows/apk-tts.yaml
- scripts/apk/build-apk-tts-engine.sh.in
- scripts/apk/build-apk-tts.sh.in
> Sign released TTS APKs

- sherpa-onnx/jni/jni.cc
> delete incorrect logs

- sherpa-onnx/c-api/c-api.cc
- sherpa-onnx/c-api/c-api.h
- sherpa-onnx/csrc/offline-tts-vits-impl.h
- sherpa-onnx/csrc/offline-tts.h
- sherpa-onnx/csrc/sherpa-onnx-offline-tts-play.cc
- sherpa-onnx/csrc/sherpa-onnx-offline-tts.cc
- sherpa-onnx/jni/jni.cc
- sherpa-onnx/python/csrc/offline-tts.cc
Add progress report for tts generator callback.
Added extra callback which contains progress parameter.
> Added progress for callback of tts generator

- build-ios.sh
- cmake/asio.cmake
- cmake/cargs.cmake
- cmake/googletest.cmake
- cmake/kaldi-native-fbank.cmake
- cmake/onnxruntime-linux-x86_64.cmake
- SHERPA_ONNX_GITHUB 环境变量设置为 true 使用镜像
- 断点续传
- hf 改用 github 镜像
> # 添加SHERPA_ONNX_GITHUB

- sherpa-onnx/csrc/online-websocket-server-impl.cc
- sherpa-onnx/csrc/online-websocket-server-impl.h
Patch to make the amount of padding configurable.
> [feature] Configurable padding length

- CMakeLists.txt
- cmake/cppjieba.cmake
- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/cppjieba-test.cc
- sherpa-onnx/csrc/file-utils.cc
- sherpa-onnx/csrc/jieba-lexicon.cc
- sherpa-onnx/csrc/jieba-lexicon.h
- sherpa-onnx/csrc/lexicon.cc
- sherpa-onnx/csrc/offline-tts-vits-impl.h
- sherpa-onnx/csrc/offline-tts-vits-model-config.cc
- sherpa-onnx/csrc/offline-tts-vits-model-config.h
- sherpa-onnx/csrc/offline-tts-vits-model-metadata.h
- sherpa-onnx/csrc/offline-tts-vits-model.cc
- sherpa-onnx/python/csrc/offline-tts-vits-model-config.cc
It supports Chinese TTS models from
https://github.com/Plachtaa/VITS-fast-fine-tuning
> Add jieba for Chinese TTS models

- sherpa-onnx/csrc/sherpa-onnx-microphone.cc
Just a function to handle lowercase transformation compatible with Unicode.
Fix for #791
> Add function 'tolowerUnicode' in sherpa-onnx-microphone (fix #791)

- .gitignore
- sherpa-onnx/csrc/offline-paraformer-greedy-search-decoder.cc
`us_cif_peak` may be a 1-dim tensor for some paraformer models.
> Fix a bug for offline paraformer

- scripts/3dspeaker/run.sh
See also #836 
CC @chiiyeh 
---
You can find the exported models at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/speaker-recongition-models
> Upload two more 3d-speaker models

- nodejs-addon-examples/README.md
- nodejs-addon-examples/package.json
- nodejs-addon-examples/test_asr_streaming_transducer_microphone.js
- scripts/node-addon-api/lib/sherpa-onnx.js
- scripts/node-addon-api/lib/streaming-asr.js
- scripts/node-addon-api/src/streaming-asr.cc
Also, add a microphone example for nodejs using node-addon-api.
> Add more streaming ASR methods for node-addon-api

- sherpa-onnx/csrc/wave-reader.cc
See also
https://github.com/naudio/NAudio/issues/1132
> Fix reading wave files generated by NAudio.

- sherpa-onnx/c-api/c-api.cc
- sherpa-onnx/c-api/c-api.h
c-api add hotwords to modeling-unit and bpe_vocab
> Update c-api.h to hotwords

- .github/workflows/flutter-linux.yaml
- CMakeLists.txt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/GetSampleText.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/PreferencesHelper.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/TtsEngine.kt
- build-swift-macos.sh
- Fix CI for Swift and flutter linux
- Save speaker ID for tts engine on restart
> Fix CI errors.

- scripts/tele-speech/test.py
- scripts/wenet/test-onnx-streaming.py
- scripts/wenet/test-onnx.py
> scale value fix

- scripts/apk/generate-asr-apk-script.py
- sherpa-onnx/csrc/online-recognizer-transducer-impl.h
- sherpa-onnx/kotlin-api/OnlineRecognizer.kt
See also
https://github.com/k2-fsa/icefall/pull/1651
CC @whsqkaak
You can download pre-built Android APKs at
https://k2-fsa.github.io/sherpa/onnx/android/apk.html
> Add Android APK for Korean

- python-api-examples/generate-subtitles.py
The converted audio file does not have a mute data of 1 second or more at the end, which will result in the loss of the last segment data
> fix generate-subtitles.py bug

- sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
Python API support for offline transducer LM rescoring
> Add Python API support for Offline LM rescoring

- dotnet-examples/online-decode-files/run-transducer-itn.sh
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
The model is from
https://huggingface.co/yfyeung/icefall-asr-gigaspeech2-th-zipformer-2024-06-20/tree/main
The dataset is from
https://github.com/SpeechColab/GigaSpeech2
> Build Android APK for Thai

- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
See also
https://github.com/k2-fsa/icefall/pull/1667
You can download it at
https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr.html
> Add non-streaming zipformer Android APK for Korean

- sherpa-onnx/csrc/parse-options.cc
- sherpa-onnx/csrc/parse-options.h
Adding parse option for int64_t
Will be useful in increasing the trt_workspace_size config
> parse option int64_t

- CMakeLists.txt
> Fix windows build

- CHANGELOG.md
- flutter/sherpa_onnx/lib/src/offline_recognizer.dart
- flutter/sherpa_onnx/lib/src/online_recognizer.dart
- flutter/sherpa_onnx/lib/src/utils.dart
> Handle invalid utf8 sequence from Whisper for Dart API.

- dotnet-examples/keyword-spotting-from-microphone/Program.cs
- dotnet-examples/keyword-spotting-from-microphone/keyword-spotting-from-microphone.csproj
- dotnet-examples/keyword-spotting-from-microphone/run.sh
- dotnet-examples/sherpa-onnx.sln
> Add microphone example for .Net keyword spotting

- .github/workflows/export-whisper-to-onnx.yaml
- scripts/whisper/export-onnx.py
- scripts/whisper/test.py
Please see
https://github.com/k2-fsa/sherpa/pull/621
for details.
> Add int8 quantized whisper large models

- .github/workflows/export-melo-tts-to-onnx.yaml
- scripts/melo-tts/export-onnx.py
- scripts/melo-tts/run.sh
- scripts/melo-tts/test.py
See also
https://github.com/myshell-ai/MeloTTS
The plan is to support the bilingual (Chinese + English) TTS from MeloTTS.
> Export MeloTTS to ONNX

- scripts/sense-voice/export-onnx.py
- scripts/sense-voice/run.sh
- scripts/sense-voice/test.py
> test exported sense voice models

- .github/workflows/run-java-test.yaml
- java-api-examples/NonStreamingDecodeFileSenseVoice.java
- java-api-examples/README.md
- java-api-examples/VadFromMicWithNonStreamingSenseVoice.java
- java-api-examples/VadNonStreamingSenseVoice.java
- java-api-examples/run-non-streaming-decode-file-sense-voice.sh
- java-api-examples/run-vad-from-mic-non-streaming-sense-voice.sh
- java-api-examples/run-vad-non-streaming-sense-voice.sh
- kotlin-api-examples/run.sh
- kotlin-api-examples/test_offline_asr.kt
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/java-api/Makefile
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineModelConfig.java
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineSenseVoiceModelConfig.java
- sherpa-onnx/jni/offline-recognizer.cc
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
You can find a pre-built Android APK containing silero VAD + SenseVoice at
- https://hf-mirror.com/csukuangfj/sherpa-onnx-apk/blob/main/vad-asr/1.10.17/sherpa-onnx-1.10.17-arm64-v8a-vad_asr-zh_en_ko_ja_yue-sense_voice.apk
- https://huggingface.co/csukuangfj/sherpa-onnx-apk/blob/main/vad-asr/1.10.17/sherpa-onnx-1.10.17-arm64-v8a-vad_asr-zh_en_ko_ja_yue-sense_voice.apk
> Add Java and Kotlin API for sense voice

- java-api-examples/NonStreamingTtsPiperEnWithCallback.java
- java-api-examples/README.md
- java-api-examples/run-non-streaming-tts-piper-en-with-callback.sh
- sherpa-onnx/java-api/Makefile
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineTts.java
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineTtsCallback.java
It plays the generated audio as it is still generating.
Fixes #1175 
CC @GeminiX369
> Add TTS example for Java API.

- .github/workflows/c-api.yaml
- ffmpeg-examples/Makefile
- ffmpeg-examples/run.sh
- ffmpeg-examples/sherpa-onnx-ffmpeg.c
Fixes #1145 
CC @waqasakram117
> Fix ffmpeg c api example

- .github/scripts/test-offline-ctc.sh
- sherpa-onnx/csrc/wave-reader.cc
Support reading wav files  saved by the flutter package `record: ^5.0.4`
> Fix reading non-standard wav files.

- .github/scripts/test-offline-transducer.sh
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
You can find the doc at
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/zipformer-transducer-models.html#sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01-japanese
Android APKs for it with silero-vad can be found at
https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr.html
A video demo for the above Android APK is available at
https://www.bilibili.com/video/BV1BRvve1ESV/
https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
> Add ReazonSpeech Japanese pre-trained model

- sherpa-onnx/csrc/CMakeLists.txt
Fixes #1030 
Fixes #392 
CC @KarelVesely84 @ytc19990517
> Remove libonnxruntime_providers_cuda.so as a dependency.

- sherpa-onnx/csrc/offline-sense-voice-model.cc
> Fix setting SenseVoice language.

- swift-api-examples/SherpaOnnx.swift
- swift-api-examples/tts.swift
- [Swift + C: Callback Interoperability](https://medium.com/codex/swift-c-callback-interoperability-6d57da6c8ee6)
- [Swift Function as a callback to a C Function](https://forums.swift.org/t/swift-function-as-a-callback-to-a-c-function/37409)
> Support passing TTS callback from Swift to C

- build-ios.sh
- ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/ViewModel.swift
CC @nanaghartey  
See also https://github.com/k2-fsa/sherpa-onnx/issues/1193#issuecomment-2270385311
| 1 | 2 | 3 | 4 |
|---|---|---|---|
|![ios-tts-1](https://github.com/user-attachments/assets/63f7b628-9dff-49b4-8ff1-d38417064335)|![ios-tts-2](https://github.com/user-attachments/assets/13eafd73-3f24-4d91-8365-bbfe9a50dc5e)|![ios-tts-3](https://github.com/user-attachments/assets/5c19a386-755e-4631-9f0e-d7107ff33a83)|![ios-tts-4](https://github.com/user-attachments/assets/057c90ce-f48e-491f-878c-c3f555bd6f81)|
> Add MeloTTS example for ios

- sherpa-onnx/c-api/c-api.cc
- sherpa-onnx/c-api/c-api.h
- sherpa-onnx/csrc/offline-recognizer-sense-voice-impl.h
- sherpa-onnx/csrc/offline-stream.cc
- sherpa-onnx/csrc/offline-stream.h
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineRecognizer.java
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineRecognizerResult.java
- sherpa-onnx/jni/offline-recognizer.cc
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
- sherpa-onnx/python/csrc/offline-stream.cc
Returns the emotion, event of SenseVoice, as https://github.com/k2-fsa/sherpa-onnx/issues/1184
> Add emotion, event of SenseVoice.

- CMakeLists.txt
See also https://github.com/k2-fsa/sherpa-onnx/discussions/1260
> Enable IPO only for Release build.

- sherpa-onnx/csrc/online-stream.h
> chore: update online-stream.h

- .github/workflows/mobile-asr-models.yaml
- scripts/mobile-asr-models/README.md
- scripts/mobile-asr-models/dynamic_quantization.py
- scripts/mobile-asr-models/parse_options.sh
- scripts/mobile-asr-models/run-impl.sh
- scripts/mobile-asr-models/run.sh
> Provide models for mobile-only platforms by fixing batch size to 1

- sherpa-onnx/c-api/c-api.cc
> Avoid SherpaOnnxSpeakerEmbeddingManagerFreeBestMatches freeing null.

- dotnet-examples/TTS/Program.cs
- dotnet-examples/TTS/Struct/SherpaOnnxOfflineTtsConfig.cs
- dotnet-examples/TTS/Struct/SherpaOnnxOfflineTtsVitsModelConfig.cs
- dotnet-examples/TTS/TTS.csproj
- dotnet-examples/TTS/TTSCore.cs
- dotnet-examples/sherpa-onnx.sln
The dot net examples contained an orphaned project that seemed to use an older version of the C api. I added a project file for TTS and fixed the C api calls.
> Fixed the C api calls and created the TTS project file

- sherpa-onnx/csrc/voice-activity-detector.cc
> Fix vad.Flush()

- scripts/go/sherpa_onnx.go
Fix the null pointer exception when n = 0.
> Fix sherpa_onnx.go

- .github/scripts/test-offline-transducer.sh
- .github/workflows/export-russian-onnx-models.yaml
- .github/workflows/linux.yaml
- .github/workflows/macos.yaml
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
The two Russian models are from
- https://huggingface.co/alphacep/vosk-model-ru
- https://huggingface.co/alphacep/vosk-model-small-ru
Pre-built Android APKs for Russian models with VAD can be found at
https://k2-fsa.github.io/sherpa/onnx/vad/apk-asr.html
> Add non-streaming ONNX models for Russian ASR

- .github/workflows/export-nemo-fast-conformer-hybrid-transducer-ctc-non-streaming.yaml
- .github/workflows/export-nemo-fast-conformer-hybrid-transducer-ctc.yaml
- .github/workflows/export-nemo-fast-conformer-hybrid-transducer-transducer-non-streaming.yaml
- .github/workflows/export-nemo-fast-conformer-hybrid-transducer-transducer.yaml
- .github/workflows/test-build-wheel.yaml
- .github/workflows/test-pip-install.yaml
- scripts/melo-tts/export-onnx.py
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/README.md
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/run-ctc-non-streaming.sh
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/run-transducer-non-streaming.sh
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/test-onnx-ctc-non-streaming.py
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/test-onnx-transducer-non-streaming.py
- sherpa-onnx/csrc/offline-recognizer-ctc-impl.h
Fixes #1380 
You can find the doc at
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-transducer/nemo-transducer-models.html#nemo-parakeet-tdt-transducer-110m
---
You can try them at https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
> Support Parakeet models from NeMo

- sherpa-onnx/csrc/offline-speaker-diarization-pyannote-impl.h
If the input audio file is less than 10 seconds long, there is only one chunk, and there is no need to compute embeddings or do clustering. 
We can use the segmentation result from the speaker segmentation model directly.
> Handle audio files less than 10s for speaker diarization.

- .github/scripts/test-nodejs-npm.sh
- .github/workflows/test-build-wheel.yaml
- .github/workflows/test-pip-install.yaml
- nodejs-examples/README.md
- nodejs-examples/test-offline-speaker-diarization.js
- scripts/nodejs/index.js
- wasm/nodejs/CMakeLists.txt
- wasm/speaker-diarization/assets/README.md
- wasm/speaker-diarization/sherpa-onnx-speaker-diarization.js
#1408 uses [node-addon-api](https://github.com/nodejs/node-addon-api) to call C API from JavaScript, whereas this pull request uses WebAssembly to call C API from JavaScript.
> JavaScript API with WebAssembly for speaker diarization

- .github/workflows/export-3dspeaker-to-onnx.yaml
- .github/workflows/export-nemo-speaker-verification-to-onnx.yaml
- .github/workflows/export-wespeaker-to-onnx.yaml
- README.md
- scripts/3dspeaker/run.sh
- scripts/nemo/speaker-verification/run.sh
You can find the huggingface space for speaker diarization at
https://huggingface.co/spaces/k2-fsa/speaker-diarization
| Screenshot 1| Screenshot 2|
|---|---|
|![Screenshot 2024-10-14 at 15 32 31](https://github.com/user-attachments/assets/3008c8f9-b816-4cd0-bc4c-9f1855e878c9)|![Screenshot 2024-10-14 at 15 32 48](https://github.com/user-attachments/assets/9594f832-d53b-43b6-913c-4e72d5e9b185)|
> Upload speaker embedding models to huggingface

- android/SherpaOnnxSpeakerDiarization/app/src/main/java/com/k2fsa/sherpa/onnx/speaker/diarization/SpeakerDiarizationObject.kt
- scripts/apk/build-apk-speaker-diarization.sh.in
- scripts/apk/generate-speaker-diarization-apk-script.py
You can find them at
https://k2-fsa.github.io/sherpa/onnx/speaker-diarization/apk.html
> add more models for speaker diarization

- python-api-examples/speaker-identification-with-vad-non-streaming-asr-alsa.py
This PR adds a file speaker-identification-with-vad-non-streaming-asr-alsa.py.
> Add speaker identification with VAD and non-streaming ASR using ALSA

- .github/workflows/export-moonshine-to-onnx.yaml
- scripts/moonshine/.gitignore
- scripts/moonshine/README.md
- scripts/moonshine/export-onnx.py
- scripts/moonshine/run.sh
- scripts/moonshine/test.py
See also
https://github.com/usefulsensors/moonshine
It is straightforward to add it to sherpa-onnx.
The only downside of moonshine I can think of is that it splits the decoder model into two parts:
- cached_decode.onnx
- uncached_decode.onnx
where there are many shared layers between the two parts. It increases the model file sizes during deployment and occupies more memory (both disk memory and RAM).
> Begin to support https://github.com/usefulsensors/moonshine

- .github/workflows/swift.yaml
- build-swift-macos.sh
- sherpa-onnx/c-api/cxx-api.h
> Publish pre-built macos xcframework

- sherpa-onnx/csrc/symbol-table.cc
> Fix reading tokens.txt on Windows.

- .github/workflows/apk-asr-2pass.yaml
- scripts/apk/generate-asr-2pass-apk-script.py
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
Please download them from
https://k2-fsa.github.io/sherpa/onnx/android/apk-2pass.html
(Search for moonshine in the above page)
> Add two-pass ASR Android APKs for Moonshine models.

- .github/workflows/build-wheels-aarch64-cuda.yaml
- cxx-api-examples/streaming-zipformer-rtf-cxx-api.cc
You can find them at
https://k2-fsa.github.io/sherpa/onnx/cuda.html
> Publish pre-built wheels with CUDA support for Linux aarch64.

- python-api-examples/two-pass-speech-recognition-from-microphone.py
sample-buffer needs to be reset after model processing
> Fix: Reset sample-buffer after processing

- python-api-examples/two-pass-speech-recognition-from-microphone.py
> Revert: [#1521] No need to reset sample-buffer

- build-ios-shared.sh
- cmake/piper-phonemize.cmake
- lazarus-examples/generate_subtitles/my_init.pas
- scripts/lazarus/generate-subtitles.py
See also
https://k2-fsa.github.io/sherpa/onnx/lazarus/download-generated-subtitles.html
> Add Lazarus example for Moonshine models.

- CHANGELOG.md
- CMakeLists.txt
- build-ios-shared.sh
- dart-api-examples/add-punctuations/pubspec.yaml
- dart-api-examples/audio-tagging/pubspec.yaml
- dart-api-examples/keyword-spotter/pubspec.yaml
- dart-api-examples/non-streaming-asr/pubspec.yaml
- dart-api-examples/speaker-diarization/pubspec.yaml
- dart-api-examples/speaker-identification/pubspec.yaml
- dart-api-examples/streaming-asr/pubspec.yaml
- dart-api-examples/tts/pubspec.yaml
- dart-api-examples/vad-with-non-streaming-asr/pubspec.yaml
- dart-api-examples/vad/pubspec.yaml
- flutter-examples/streaming_asr/pubspec.yaml
- flutter-examples/tts/pubspec.yaml
- flutter/sherpa_onnx/pubspec.yaml
- flutter/sherpa_onnx_ios/ios/sherpa_onnx_ios.podspec
- flutter/sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec
- new-release.sh
- nodejs-addon-examples/package.json
> Fix flutter ios

- sherpa-onnx/csrc/online-transducer-model.cc
> fix building for Android

- .github/workflows/har.yaml
- harmony-os/SherpaOnnxHar/README.md
- harmony-os/SherpaOnnxHar/sherpa_onnx/BuildProfile.ets
- harmony-os/SherpaOnnxHar/sherpa_onnx/README.md
- harmony-os/SherpaOnnxHar/sherpa_onnx/oh-package.json5
- new-release.sh
You can find it at https://ohpm.openharmony.cn/#/cn/detail/sherpa_onnx
> Fix publishing har packages for HarmonyOS

- README.md
See also 
https://github.com/t41372/Open-LLM-VTuber/pull/50
> Update readme to include Open-LLM-VTuber

- .github/workflows/checksum.yaml
Resolve https://github.com/k2-fsa/sherpa-onnx/issues/1542 using [marketplace/actions/checksums-action](https://github.com/marketplace/actions/checksums-action)
> feat: add checksum action

- scripts/apk/generate-tts-apk-script.py
> Add new tts models for Latvia and Persian+English

- .github/scripts/test-python.sh
- .github/workflows/add-new-asr-models.yaml
- harmony-os/SherpaOnnxVadAsr/entry/src/main/ets/pages/NonStreamingAsrModels.ets
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
Please see
https://huggingface.co/zrjin/icefall-asr-zipformer-multi-zh-en-2023-11-22
and
https://github.com/k2-fsa/icefall/pull/1265
You can download it from
https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-zipformer-zh-en-2023-11-22.tar.bz2
> Add a byte-level BPE Chinese+English non-streaming zipformer model

- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/offline-recognizer-impl.cc
- sherpa-onnx/csrc/online-recognizer-impl.cc
- sherpa-onnx/csrc/text-utils-test.cc
- sherpa-onnx/csrc/text-utils.cc
- sherpa-onnx/csrc/text-utils.h
> Support removing invalid utf-8 sequences.

- .github/workflows/macos.yaml
> Fix building macOS libs

- python-api-examples/generate-subtitles.py
> Avoid adding tail padding for VAD in generate-subtitles.py

- dotnet-examples/Common/Common.csproj
- dotnet-examples/Common/WaveHeader.cs
- dotnet-examples/keyword-spotting-from-files/Program.cs
- dotnet-examples/keyword-spotting-from-files/keyword-spotting-from-files.csproj
- dotnet-examples/keyword-spotting-from-microphone/Program.cs
- dotnet-examples/keyword-spotting-from-microphone/keyword-spotting-from-microphone.csproj
- dotnet-examples/offline-decode-files/Program.cs
- dotnet-examples/offline-decode-files/offline-decode-files.csproj
- dotnet-examples/offline-punctuation/Program.cs
- dotnet-examples/offline-punctuation/offline-punctuation.csproj
- dotnet-examples/offline-speaker-diarization/Program.cs
- dotnet-examples/offline-speaker-diarization/offline-speaker-diarization.csproj
- dotnet-examples/offline-tts-play/Program.cs
- dotnet-examples/offline-tts-play/offline-tts-play.csproj
- dotnet-examples/offline-tts/Program.cs
- dotnet-examples/offline-tts/offline-tts.csproj
- dotnet-examples/online-decode-files/Program.cs
- dotnet-examples/online-decode-files/online-decode-files.csproj
- dotnet-examples/sherpa-onnx.sln
- dotnet-examples/speaker-identification/Program.cs
- dotnet-examples/speaker-identification/speaker-identification.csproj
- dotnet-examples/speech-recognition-from-microphone/Program.cs
- dotnet-examples/speech-recognition-from-microphone/speech-recognition-from-microphone.csproj
- dotnet-examples/spoken-language-identification/Program.cs
- dotnet-examples/spoken-language-identification/spoken-language-identification.csproj
- dotnet-examples/streaming-hlg-decoding/Program.cs
- dotnet-examples/streaming-hlg-decoding/streaming-hlg-decoding.csproj
- dotnet-examples/vad-non-streaming-asr-paraformer/Program.cs
- dotnet-examples/vad-non-streaming-asr-paraformer/vad-non-streaming-asr-paraformer.csproj
The existing example projects target .NET 6 which is no longer supported.  This PR upgrades them to .NET 8, which is the current LTS version.
> Upgraded to .NET 8 and made code style a little more internally consistent.

- .github/workflows/dot-net.yaml
- .github/workflows/test-dot-net-nuget.yaml
- .github/workflows/test-dot-net.yaml
Oops, I broke the build.  The tests are failing because they aren't using .NET 8.
> Update workflows to use .NET 8.0 also.

- scripts/dotnet/KeywordSpotter.cs
- scripts/dotnet/OfflinePunctuation.cs
- scripts/dotnet/OfflineTts.cs
- scripts/dotnet/OfflineTtsGeneratedAudio.cs
- scripts/dotnet/SpeakerEmbeddingManager.cs
See also
https://github.com/k2-fsa/sherpa-onnx/issues/1695#issuecomment-2585725190
We need to place a 0 at the end of the buffer.
Thanks to @adem-rguez for pointing out the issue.
> Fix passing strings from C# to C.

- .github/workflows/run-java-test.yaml
- android/SherpaOnnxTts/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/GetSampleText.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt
- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/TtsEngine.kt
- android/SherpaOnnxTtsEngine/app/src/main/res/values/strings.xml
- java-api-examples/NonStreamingTtsKokoroEn.java
- java-api-examples/run-non-streaming-tts-kokoro-en.sh
- kotlin-api-examples/run.sh
- kotlin-api-examples/test_tts.kt
- scripts/apk/build-apk-tts-engine.sh.in
- scripts/apk/build-apk-tts.sh.in
- scripts/apk/generate-tts-apk-script.py
- sherpa-onnx/java-api/Makefile
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineTtsKokoroModelConfig.java
- sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineTtsModelConfig.java
- sherpa-onnx/jni/offline-tts.cc
- sherpa-onnx/kotlin-api/Tts.kt
You can find pre-built Android APKs for Kokoro TTS models at
https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html
Screenshot
> Add Koltin and Java API for Kokoro TTS models

- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/audio-tagging.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/keyword-spotting.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/non-streaming-speaker-diarization.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/non-streaming-tts.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/punctuation.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/speaker-identification.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/spoken-language-identification.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/streaming-asr.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/vad.cc
Use macros to delete pointers.
> Refactor node-addon C++ code.

- flutter-examples/tts/lib/model.dart
Fixes #1744
CC @studionexus-lk
Please use example 8.
> Add Flutter example for Kokoro TTS

- ios-swiftui/SherpaOnnx/SherpaOnnx/SherpaOnnxViewModel.swift
[https://github.com/k2-fsa/sherpa-onnx/issues/1784](url)
with SherpaOnnxViewModel.swift reformat via xcode under 'swift-format'
> Ios swiftui pr 0202

- mfc-examples/NonStreamingTextToSpeech/NonStreamingTextToSpeechDlg.cpp
|1|2|
|---|---|
|<img width="910" alt="Screenshot 2025-02-07 at 22 18 10" src="https://github.com/user-attachments/assets/c6a7cb97-b1d1-4950-ba45-ec2d9ca83e3a" />|<img width="917" alt="Screenshot 2025-02-07 at 22 18 19" src="https://github.com/user-attachments/assets/46430711-a50a-4d6d-9e8d-71674652b258" />|
> Add MFC example for Kokoro TTS 1.0

- .github/workflows/export-matcha-fa-en.yaml
- scripts/matcha-tts/README.md
- scripts/matcha-tts/fa-en/.gitignore
- scripts/matcha-tts/fa-en/README.md
- scripts/matcha-tts/fa-en/add_meta_data.py
- scripts/matcha-tts/fa-en/run.sh
- scripts/matcha-tts/fa-en/test.py
See also https://github.com/k2-fsa/sherpa-onnx/issues/1779
We need to update the C++ code to support it.
CC @mah92
> Export MatchaTTS fa-en model to sherpa-onnx

- .github/workflows/export-matcha-fa-en.yaml
- .github/workflows/export-peng-cheng-starling.yaml
- scripts/apk/build-apk-tts-engine.sh.in
- scripts/apk/generate-tts-apk-script.py
See also https://github.com/k2-fsa/sherpa-onnx/issues/1779#issuecomment-2648948128
> Fix matcha tts model names for Persian and English

- python-api-examples/non_streaming_server.py
non_streaming_server.py cannot use streaming models
> Modify the model used

- new-release.sh
- nodejs-examples/README.md
- nodejs-examples/package.json
- nodejs-examples/test-offline-fire-red-asr.js
- wasm/asr/sherpa-onnx-asr.js
- wasm/nodejs/sherpa-onnx-wasm-nodejs.cc
Note the FireRedAsr AED large is quite large. We need to wait for their small models to test this PR.
> Add JavaScript API (WebAssembly) for FireRedAsr model.

- flutter/sherpa_onnx/lib/src/audio_tagging.dart
- flutter/sherpa_onnx/lib/src/feature_config.dart
- flutter/sherpa_onnx/lib/src/keyword_spotter.dart
- flutter/sherpa_onnx/lib/src/offline_punctuation.dart
- flutter/sherpa_onnx/lib/src/offline_recognizer.dart
- flutter/sherpa_onnx/lib/src/offline_speaker_diarization.dart
- flutter/sherpa_onnx/lib/src/online_punctuation.dart
- flutter/sherpa_onnx/lib/src/online_recognizer.dart
- flutter/sherpa_onnx/lib/src/speaker_identification.dart
- flutter/sherpa_onnx/lib/src/tts.dart
- flutter/sherpa_onnx/lib/src/vad.dart
I was testing different models, and realized it would be convenient to be able to pass in the Config parameters as Json. 
- Created fromJson constructors and toJson methods to all pure Dart/Flutter classes. 
- Any classes involving pointers or FFI I left alone.
> Flutter Config toJson/fromJson

- .github/workflows/linux.yaml
- .github/workflows/test-build-wheel.yaml
- .github/workflows/test-pip-install.yaml
- .github/workflows/windows-x64.yaml
Fixes #1912 
@starship2018
Please redownload
[sherpa-onnx-v1.10.45-linux-x64-shared.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.10.45/sherpa-onnx-v1.10.45-linux-x64-shared.tar.bz2)
> Fix publishing linux pre-built artifacts

- .github/workflows/macos.yaml
> Fix publishing macos pre-built artifacts

- .github/workflows/export-kokoro.yaml
- scripts/apk/generate-tts-apk-script.py
- scripts/kokoro/.gitignore
- scripts/kokoro/v1.0/generate_lexicon_en.py
- scripts/kokoro/v1.0/generate_lexicon_zh.py
- scripts/kokoro/v1.1-zh/README.md
- scripts/kokoro/v1.1-zh/add_meta_data.py
- scripts/kokoro/v1.1-zh/dynamic_quantization.py
- scripts/kokoro/v1.1-zh/export_onnx.py
- scripts/kokoro/v1.1-zh/generate_lexicon_en.py
- scripts/kokoro/v1.1-zh/generate_lexicon_zh.py
- scripts/kokoro/v1.1-zh/generate_tokens.py
- scripts/kokoro/v1.1-zh/generate_voices_bin.py
- scripts/kokoro/v1.1-zh/run.sh
- scripts/kokoro/v1.1-zh/test.py
- sherpa-onnx/csrc/kokoro-multi-lang-lexicon.cc
- sherpa-onnx/csrc/offline-tts.cc
This model supports both Chinese and English.
It has 3 English female speakers, 55 Chinese female speakers, and 45 Chinese male speakers.
There are 103 speakers in total.
|ID | Speaker|
|---|---|
|0-2| English female|
|3-57|Chinese female|
|58-102|Chinese male|
Please download it from
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models
You can try it at
- https://huggingface.co/spaces/k2-fsa/text-to-speech
- 国内用户，可以直接访问 https://hf.qhduan.com/spaces/k2-fsa/text-to-speech
```
某某银行的副行长和一些行政领导表示，他们去过长江和长白山; 
经济不断增长。2024年12月31号，拨打110或者18920240511。123456块钱。
```
https://github.com/user-attachments/assets/3ad87c13-7964-4e3b-8019-6986228810c6
```
多音字测试，注意！某某银行行长和一些行政领导表示，
他们去过长江和长白山; 经济不断增长。2025年2月28号，
拨打110或者18920240511。123456块钱。
What do you think about it? 你觉得中英文说的如何呢？
``` …
> Add Kokoro v1.1-zh

- scripts/go/sherpa_onnx.go
add SherpaOnnxOfflineRecognizerSetConfig binding for go, and optimize the new/free for C.struct_SherpaOnnxOfflineRecognizerConfig ptr
> add SherpaOnnxOfflineRecognizerSetConfig binding for go

- cmake/cmake_extension.py
- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/sherpa-onnx-vad-alsa-offline-asr.cc
- sherpa-onnx/csrc/sherpa-onnx-vad-microphone-offline-asr.cc
- sherpa-onnx/csrc/vocoder.cc
Fixes #2018 
CC @SnappierSoap318
> add alsa example for vad+offline asr

- sherpa-onnx/csrc/voice-activity-detector.cc
> Fix a bug in vad.reset()

- sherpa-onnx/csrc/vocoder.cc
Fixes #1955 
CC @mah92 
Please re-download pre-built APKs for matcha tts (v1.11.1).
> Fix Matcha + vocos for Android

- android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt
> Fix crash in Android tts engine demo.

- go-api-examples/non-streaming-tts/main.go
Or will report:
Please provide  --vits-dict-dir for Chinese TTS models using jieba
> fix vits dict dir config

- sherpa-onnx/csrc/wave-writer.cc
> 缩放因子应该是32767？

- .github/scripts/test-nodejs-npm.sh
- .github/workflows/wasm-simd-hf-space-vad-asr.yaml
- README.md
- nodejs-examples/README.md
- nodejs-examples/test-offline-dolphin-ctc.js
- scripts/wasm/generate-vad-asr.py
- wasm/asr/sherpa-onnx-asr.js
- wasm/nodejs/sherpa-onnx-wasm-nodejs.cc
- wasm/vad-asr/app-vad-asr.js
You can find a huggingface space for it at
https://huggingface.co/spaces/k2-fsa/web-assembly-vad-asr-sherpa-onnx-multi-lang-dophin-ctc
If you don't have access to Huggingface, you can visit the following mirror
https://hf.qhduan.com/spaces/k2-fsa/web-assembly-vad-asr-sherpa-onnx-multi-lang-dophin-ctc
> Add Javascript (WebAssembly) API for Dolphin CTC models

- .github/workflows/export-nemo-giga-am-to-onnx.yaml
- scripts/nemo/GigaAM/export-onnx-ctc-v2.py
- scripts/nemo/GigaAM/run-ctc-v2.sh
Please note that I tried to edit GitHub Actions for uploading the resulting model as best as I can, but I could not test it.
https://huggingface.co/csukuangfj/sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19 should be created first.
Related to #2098.
> Add support for GigaAM-CTC-v2

- .github/workflows/export-kokoro.yaml
- scripts/kokoro/v1.0/add_meta_data.py
- scripts/kokoro/v1.0/dynamic_quantization.py
- scripts/kokoro/v1.0/export_onnx.py
- scripts/kokoro/v1.0/generate_tokens.py
- scripts/kokoro/v1.0/generate_voices_bin.py
- scripts/kokoro/v1.0/run.sh
Fixes #2133
kokoro 1.0 int8 onnx models can be found at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models
The following colab notebook shows how to use with sherpa-onnx
https://colab.research.google.com/drive/12kN-23gy_3mRYkQ6RDAHarOnXBNlmLue?usp=sharing
> Export kokoro 1.0 int8 models

- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/audio-tagging.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/speaker-identification.cc
- harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/utils.cc
It should fix the error in
https://github.com/k2-fsa/sherpa-onnx/issues/2120#issuecomment-2816560663
CC @ohosgg
> Fix building for open harmonyOS

- python-api-examples/simulate-streaming-sense-voice-microphone.py
- sherpa-onnx/python/sherpa_onnx/display.py
You need to run
```
pip install "sherpa-onnx>=1.11.6"
```
> Add real-time speech recognition example for SenseVoice.

- README.md
Enable custom wake word for XiaoAi Speakers. 让小爱音箱支持自定义唤醒词。
Video demo in Chinese: [小爱同学启动～˶╹ꇴ╹˶！](https://www.bilibili.com/video/BV1YfVUz5EMj)
[![](https://github.com/idootop/open-xiaoai/raw/main/docs/images/kws.jpg)](https://www.bilibili.com/video/BV1YfVUz5EMj)
> docs: add Open-XiaoAI KWS project

- README.md
See https://www.youtube.com/watch?v=KxPKkwxGWZs
> Add a link to YouTube video including sherpa-onnx.

- .github/workflows/apk-vad-asr-simulated-streaming.yaml
- scripts/apk/build-apk-vad-asr-simulate-streaming.sh.in
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
Please see
https://k2-fsa.github.io/sherpa/onnx/android/apk-simulate-streaming-asr.html
> Add script to build APK for simulated-streaming-asr.

- sherpa-onnx/jni/offline-speech-denoiser.cc
- sherpa-onnx/jni/offline-tts.cc
> Use jlong explicitly in jni.

- .github/workflows/build-wheels-aarch64-rknn.yaml
- .github/workflows/rknn-linux-aarch64.yaml
> Fix publishing binaries for RKNN

- .github/workflows/export-spleeter-to-onnx.yaml
- scripts/spleeter/.gitignore
- scripts/spleeter/convert_to_pb.py
- scripts/spleeter/convert_to_torch.py
- scripts/spleeter/export_onnx.py
- scripts/spleeter/run.sh
- scripts/spleeter/separate.py
- scripts/spleeter/separate_onnx.py
- scripts/spleeter/unet.py
See also
https://github.com/deezer/spleeter
> Export spleeter model to onnx for source separation

- .github/workflows/as_cmake_sub_project.yaml
- .github/workflows/export-uvr-to-onnx.yaml
- scripts/uvr_mdx/READEME.md
- scripts/uvr_mdx/add_meta_data_and_quantize.py
- scripts/uvr_mdx/run.sh
- scripts/uvr_mdx/show.py
- scripts/uvr_mdx/test.py
See also
- https://github.com/TRvlvr/model_repo/releases/tag/all_public_uvr_models
- https://github.com/Anjok07/ultimatevocalremovergui
See also #2242 
CC @acely
---
```bash
cd sherpa-onnx/scripts/uvr_mdx
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/source-separation-models/UVR-MDX-NET-Voc_FT.onnx
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/source-separation-models/piao-yang-guo-hai-lai-kan-ni.wav
python3 ./test.py --model-filename ./UVR-MDX-NET-Voc_FT.onnx --audio-filename ./piao-yang-guo-hai-lai-kan-ni.wav
```
https://github.com/user-attachments/assets/e67fa17a-7bb3-46b9-b9f4-60e67fe67f36
https://github.com/user-attachments/assets/ee2c8ed2-ef77-464d-9dee-c6a522dd5d54 …
> Add UVR models for source separation.

- sherpa-onnx/csrc/microphone.cc
sorry about portaudio pr, it break mfc and windows build for not found int32_t. 
this pr fixed it
> fixed mfc build error

- README.md
Please see
- https://huggingface.co/spaces/k2-fsa/source-separation
- https://hf.qhduan.com/spaces/k2-fsa/source-separation
> Add link to huggingface space for source separation.

- sherpa-onnx/csrc/offline-speaker-diarization-pyannote-impl.h
Handle the case when the input audio contains no speeches.
> Fixes #2172

- README.md
See also https://github.com/mtkresearch/BreezeApp
> Update readme to include BreezeApp from MediaTek Research

- .github/workflows/pkg-config.yaml
- cmake/sherpa-onnx-static-no-tts.pc.in
> Fix static link without tts

- scripts/apk/generate-asr-apk-script.py
- sherpa-onnx/csrc/sherpa-onnx-vad-with-offline-asr.cc
- sherpa-onnx/kotlin-api/OnlineRecognizer.kt
It was not able to handle short audios., e.g., 2.1 seconds.
> Fix VAD+ASR C++ example.

- README.md
See also https://github.com/mawwalker/stt-server
CC @mawwalker
> Update readme to include https://github.com/mawwalker/stt-server

- .github/workflows/export-nemo-canary-180m-flash.yaml
- scripts/nemo/canary/export_onnx_180m_flash.py
- scripts/nemo/canary/run_180m_flash.sh
- scripts/nemo/canary/test_180m_flash.py
Also, disable the fp16 support since the export gets stuck
> Add meta data to NeMo canary ONNX models

- README.md
See also 
https://github.com/bbeyondllove/asr_server
CC @bbeyondllove
> Update README to include https://github.com/bbeyondllove/asr_server

- .github/workflows/export-nemo-fast-conformer-hybrid-transducer-ctc-non-streaming.yaml
- .github/workflows/export-nemo-fast-conformer-hybrid-transducer-transducer-non-streaming.yaml
- scripts/apk/generate-vad-asr-apk-script.py
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/README.md
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/export-onnx-ctc-non-streaming.py
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/export-onnx-transducer-non-streaming.py
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/run-ctc-non-streaming-2.sh
- scripts/nemo/fast-conformer-hybrid-transducer-ctc/run-transducer-non-streaming-2.sh
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
You can try them at 
https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
or download pre-built APKs and run them on your Android devices.
||German| Portuguese|
|---|---|---|
|Original NeMo huggingface repo| [Address](https://huggingface.co/nvidia/stt_de_fastconformer_hybrid_large_pc)|[Address](https://huggingface.co/nvidia/stt_pt_fastconformer_hybrid_large_pc)|
|Huggingface space|<img width="1328" height="459" alt="Screenshot 2025-07-14 at 14 40 54" src="https://github.com/user-attachments/assets/ca13c48c-84d7-4b70-b621-e8293f4a14c8" />|<img width="1343" height="577" alt="Screenshot 2025-07-14 at 14 41 05" src="https://github.com/user-attachments/assets/683bde37-e02d-47ae-ad6e-fdc01f493450" />|
|Android VAD+ASR (transducer)|[Address](https://hf-mirror.com/csukuangfj/sherpa-on …
> Support Portuguese and German ASR models from NeMo

- sherpa-onnx/csrc/jieba-lexicon.cc
- sherpa-onnx/csrc/lexicon.cc
> Add more debug info for vits tts

- scripts/nemo/parakeet-tdt-0.6b-v2/test_onnx.py
- sherpa-onnx/csrc/offline-recognizer-transducer-nemo-impl.h
- sherpa-onnx/csrc/offline-transducer-greedy-search-nemo-decoder.cc
- sherpa-onnx/csrc/offline-transducer-greedy-search-nemo-decoder.h
- sherpa-onnx/csrc/offline-transducer-nemo-model.cc
- sherpa-onnx/csrc/offline-transducer-nemo-model.h
> Support TDT transducer decoding

- .github/workflows/upload-models.yaml
- scripts/apk/generate-asr-apk-script.py
- sherpa-onnx/kotlin-api/OnlineRecognizer.kt
See also
- https://huggingface.co/spaces/Banafo/Kroko-Streaming-ASR-Python
- https://huggingface.co/alphacep/vosk-model-small-streaming-ru
You can try them at 
https://huggingface.co/spaces/k2-fsa/automatic-speech-recognition
Models are available from
See also #2435
CC @nshmyrev @MrBzik
Will update the doc at https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/index.html
> Add VOSK streaming Russian ASR models and Kroko streaming German ASR models

- .github/workflows/export-kitten.yaml
- scripts/apk/generate-tts-apk-script.py
- scripts/kitten-tts/nano_v0_2/add_meta_data.py
- scripts/kitten-tts/nano_v0_2/convert_opset.py
- scripts/kitten-tts/nano_v0_2/generate_tokens.py
- scripts/kitten-tts/nano_v0_2/generate_voices_bin.py
- scripts/kitten-tts/nano_v0_2/run.sh
- scripts/kitten-tts/nano_v0_2/show.py
- scripts/kitten-tts/nano_v0_2/test.py
Its usage is the same as nano v0.1.
Just replace `1` with `2`.
> Add kitten tts nano v0.2

- .github/workflows/generate-tts-samples.yaml
- scripts/matcha-tts/en/generate_samples.py
- sherpa-onnx/python/csrc/offline-tts-matcha-model-config.cc
See also
https://k2-fsa.github.io/sherpa/onnx/tts/all/English/matcha-icefall-en_US-ljspeech.html
> Generate tts samples for MatchaTTS (English).

- .github/workflows/export-piper.yaml
- scripts/apk/generate-tts-apk-script.py
- scripts/piper/generate.py
See also
https://k2-fsa.github.io/sherpa/onnx/tts/all/German/vits-piper-de_DE-dii-high.html
> Add one more German tts model from OpenVoiceOS.

- sherpa-onnx/csrc/file-utils.cc
> Add hint for loading model files from SD card on Android.

- README.md
See also
https://github.com/Mentra-Community/MentraOS
and
https://github.com/Mentra-Community/MentraOS/pull/861
> Update README to include https://github.com/Mentra-Community/MentraOS

- .github/workflows/android.yaml
- android/SherpaOnnxAar/sherpa_onnx/src/main/java/com/k2fsa/sherpa/onnx/OnlinePunctuation.kt
Fixes #2568
Fixes #2570
CC @alpian9890
> Fix the missing online punctuation in android aar

- .github/workflows/upload-models.yaml
- scripts/apk/generate-asr-2pass-apk-script.py
- scripts/apk/generate-vad-asr-apk-script.py
- sherpa-onnx/kotlin-api/OfflineRecognizer.kt
See the doc at
https://k2-fsa.github.io/sherpa/onnx/sense-voice/pretrained.html#sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09-chinese-english-japanese-korean-cantonese
> Upload new sense-voice models

- .github/workflows/upload-models.yaml
Support the model from https://huggingface.co/ASLP-lab/WSYue-ASR/tree/main/u2pp_conformer_yue
Please see https://colab.research.google.com/drive/1Vn7IkgAnyZ8CRUbqu_Vtwcuuq3aqelgE?usp=sharing
for usages.
---
> Export ASLP-lab/WSYue-ASR/tree/main/u2pp_conformer_yue to sherpa-onnx

- .github/workflows/aarch64-linux-gnu-shared.yaml
- .github/workflows/aarch64-linux-gnu-static.yaml
- .github/workflows/build-wheels-aarch64-cuda.yaml
- .github/workflows/build-wheels-aarch64-rknn.yaml
- .github/workflows/build-wheels-aarch64.yaml
- .github/workflows/build-wheels-linux-cuda.yaml
- .github/workflows/build-wheels-linux.yaml
- .github/workflows/linux-gpu.yaml
- .github/workflows/linux-jni-aarch64.yaml
- .github/workflows/linux-jni.yaml
- .github/workflows/linux.yaml
- .github/workflows/rknn-linux-aarch64.yaml
- CMakeLists.txt
- build-aarch64-linux-gnu.sh
- cmake/cmake_extension.py
- cmake/portaudio.cmake
- sherpa-onnx/csrc/CMakeLists.txt
- sherpa-onnx/csrc/sherpa-display.h
- sherpa-onnx/csrc/sherpa-onnx-vad-microphone-simulated-streaming-asr.cc
```bash
cd /path/to/sherpa-onnx/build
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17.tar.bz2
tar xvf sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17.tar.bz2
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/silero_vad.onnx
./bin/sherpa-onnx-vad-microphone-simulated-streaming-asr \
--silero-vad-model=./silero_vad.onnx \
--sense-voice-model=./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/model.int8.onnx \
--tokens=./sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17/tokens.txt
```
```bash
cd /path/to/sherpa-onnx/build
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8.tar.bz2
tar xvf …
```
> Add a C++ example for simulated streaming ASR
