.github/workflows/build-wheels.yaml, cmake/cmake_extension.py
cibuildwheel does not support python 3.6 any more. This PR removes Python 3.6 from CI build.
=> Fix building pre-compiled wheels

python-api-examples/decode-file.py, python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py, python-api-examples/speech-recognition-from-microphone.py, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/features.cc, sherpa-onnx/csrc/features.h, sherpa-onnx/csrc/online-stream.cc, sherpa-onnx/csrc/online-stream.h, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.cc, sherpa-onnx/python/csrc/online-stream.cc
If the sample rate of the input audio samples is different from the one expected by the model, we do resampling inside sherpa-onnx.
That is, we don't require the input sample rate to be 16 kHz any more.
=> Support resampling

cmake/asio.cmake, cmake/googletest.cmake, cmake/kaldi-native-fbank.cmake, cmake/onnxruntime.cmake, cmake/portaudio.cmake, cmake/pybind11.cmake, cmake/websocketpp.cmake
People from China have trouble installing sherpa-onnx because they have difficulty downloading dependencies from GitHub.
This PR adds alternative URLs for downloading dependencies.
=> Add alternative URLs for downloading deps

CMakeLists.txt, cmake/json.cmake, sherpa-onnx/csrc/online-recognizer.cc, sherpa-onnx/csrc/online-recognizer.h, sherpa-onnx/csrc/online-transducer-decoder.cc, sherpa-onnx/csrc/online-transducer-decoder.h, sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.cc, sherpa-onnx/csrc/online-websocket-server-impl.cc, sherpa-onnx/csrc/sherpa-onnx.cc, sherpa-onnx/jni/jni.cc
An example output is given below:
```bash
./build/bin/sherpa-onnx \
./sherpa-onnx-streaming-zipformer-en-2023-02-21/tokens.txt \
./sherpa-onnx-streaming-zipformer-en-2023-02-21/encoder-epoch-99-avg-1.int8.onnx \
./sherpa-onnx-streaming-zipformer-en-2023-02-21/decoder-epoch-99-avg-1.int8.onnx \
./sherpa-onnx-streaming-zipformer-en-2023-02-21/joiner-epoch-99-avg-1.int8.onnx \
./sherpa-onnx-streaming-zipformer-en-2023-02-21/test_wavs/8k.wav
```
```bash
OnlineRecognizerConfig(feat_config=FeatureExtractorConfig(sampling_rate=16000, feature_dim=80), model_config=OnlineTransducerModelConfig(encoder_filename="./sherpa-onnx-streaming-zipformer-en-2023-02-21/encoder-epoch-99-avg-1.int8.onnx", decoder_filename="./sherpa-onnx-streaming-zipformer-en-2023-02-21/decoder-epoch-99-avg-1.int8.onnx", …
```
=> Add timestamps for streaming ASR.

sherpa-onnx/csharp-api/CPPLINT.cfg
I am refactoring the csharp-api code and will fix the style issues in a later PR.
=> ignore style check for files in csharp-api

sherpa-onnx/csrc/offline-lm.cc, sherpa-onnx/csrc/offline-lm.h, sherpa-onnx/csrc/offline-recognizer-transducer-impl.h, sherpa-onnx/csrc/offline-rnn-lm.cc, sherpa-onnx/csrc/offline-rnn-lm.h, sherpa-onnx/csrc/online-lm.cc, sherpa-onnx/csrc/online-lm.h, sherpa-onnx/csrc/online-recognizer.cc, sherpa-onnx/csrc/online-rnn-lm.cc, sherpa-onnx/csrc/online-rnn-lm.h
It's support passing num_threads argument to rnnlm onnx model, including offline rnnlm rescore and online rnnlm rescore.
=> rnnlm model inference supports num_threads setting

cmake/onnxruntime.cmake
When downloading onnxruntime, add detection conditions under the x86 platform.
=> Add detection conditions under the x86 platform.

CMakeLists.txt, dotnet-examples/sherpa-onnx.sln, dotnet-examples/speech-recognition-from-microphone/Program.cs, dotnet-examples/speech-recognition-from-microphone/run.sh, dotnet-examples/speech-recognition-from-microphone/speech-recognition-from-microphone.csproj
It requires [PortAudioSharp2](https://github.com/csukuangfj/PortAudioSharp2/)
```
<PackageReference Include="PortAudioSharp2" Version="*" />
```
=> Real-time speech recognition from microphone for .Net

CMakeLists.txt, scripts/dotnet/offline.cs, scripts/dotnet/online.cs, scripts/dotnet/sherpa-onnx.csproj.in, scripts/dotnet/sherpa-onnx.csproj.runtime.in
`Marshal.PtrToStringUTF8()` requires .netstandard 2.1 and `Marshal.PtrToStringAnsi()` has different behaviors on Unix and Windows:
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.ptrtostringansi?view=net-7.0#definition
> Allocates a managed [String](https://learn.microsoft.com/en-us/dotnet/api/system.string?view=net-7.0) and copies all or part of an unmanaged ANSI (on Windows) or UTF-8 (on Unix) string into it.
=> Support .netstandard 2.0

python-api-examples/speech-recognition-from-microphone-with-endpoint-detection.py, python-api-examples/speech-recognition-from-microphone.py, python-api-examples/speech-recognition-from-url.py
Supported URLs are those supported by ffmpeg.
```
#
#
```
=> Support recognition from URLs.

mfc-examples/NonStreamingSpeechRecognition/NonStreamingSpeechRecognitionDlg.cpp, scripts/dotnet/offline.cs, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/offline-model-config.cc, sherpa-onnx/csrc/offline-model-config.h, sherpa-onnx/csrc/offline-recognizer-impl.cc, sherpa-onnx/csrc/offline-transducer-model-config.cc, sherpa-onnx/python/csrc/offline-model-config.cc, sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
Add a new argument `--model-type` so that it only needs to load the model once.
Otherwise, it needs to load the model twice, where the first loading is to determine the model type.
I have tested the following paraformer model with `--model-type=paraformer` using `./build/bin/sherpa-onnx-offline`
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/offline-paraformer/paraformer-models.html
The model loading time is reduced from ~12 seconds to ~6 seconds for the fp32 model; while for the int8 model the time is reduced from 5.8 seconds to 2.7 seconds.
=> Reduce model initialization time for offline speech recognition

sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/online-transducer-model-config.cc, sherpa-onnx/csrc/online-transducer-model-config.h, sherpa-onnx/csrc/online-transducer-model.cc, sherpa-onnx/python/csrc/online-transducer-model-config.cc, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
Implemented `model_type` parameter for online transducer models as suggested by @csukuangfj in [this issue](https://github.com/k2-fsa/sherpa-onnx/issues/211#issuecomment-1635661879) and based largely on [this PR](https://github.com/k2-fsa/sherpa-onnx/pull/213).
Add a new argument `--model-type` so that it only needs to load the model once.
Otherwise, it needs to load the model twice, where the first loading is to determine the model type.
I have tested [csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-26](https://huggingface.co/csukuangfj/sherpa-onnx-streaming-zipformer-en-2023-06-26) via the Python API on Linux, by specifying `model_type="zipformer2"` during initialization.
The model loading time is reduced from ~6 seconds to ~3 seconds for the fp32 model; while for the int8 model …
=> Reduce model initialization time for online speech recognition

sherpa-onnx/csrc/hypothesis.h
As suggested by the subject. This makes it easier to compare results between `sherpa` and `sherpa-onnx`.
=> Updated hypothesis key generation to be the same as sherpa

CMakeLists.txt, cmake/cmake_extension.py, mfc-examples/StreamingSpeechRecognition/StreamingSpeechRecognition.vcxproj, setup.py
There are no `rpath` or `run path` on windows, so we have to copy the required DLLs to the same directory as the the `exe`s.
=> Fix building wheels on Windows

.github/workflows/build-wheels.yaml, CMakeLists.txt, scripts/wheel/patch_wheel.py
When using `pip install sherpa-onnx` in a colab notebook, it throws the following error after installation:
This PR fixes it by changing the `rpath` of generated binaries.
=> Fix building wheels for Linux

CMakeLists.txt, sherpa-onnx/csrc/offline-whisper-greedy-search-decoder.cc
We should use
```
logits[:, -1, :]
```
for the `sot_sequence`, not `logits[:, 0, :]`.
=> Fix a bug for multilingual ASR

sherpa-onnx/csrc/context-graph-test.cc, sherpa-onnx/csrc/context-graph.cc, sherpa-onnx/csrc/context-graph.h
Fix an issue about the failure arc score (the canceling score), I remove the local_node_score which turns out to be an over design and leads to this issue.
I also do some optimization by calculating the output score while compiling the graph.
=> Fix context graph

python-api-examples/two-pass-speech-recognition-from-microphone.py
This PR adds a two-pass speech recognition example in Python.
The first pass uses a streaming model, while the second pass uses a non-streaming model.
In general, a non-streaming model has a better recognition accuracy than that of a streaming model but a
streaming model has a lower latency.
We use the first pass streaming model to show a temporary result to users as they speak.
When an endpoint is detected by the first pass streaming model, the non-streaming model starts to run
and its result is used as the final result.
Download the first-pass model:
https://k2-fsa.github.io/sherpa/onnx/pretrained_models/online-transducer/zipformer-transducer-models.html#sherpa-onnx-streaming-zipformer-zh-14m-2023-02-23
Download the second-pass model …
=> Add a two-pass python example

sherpa-onnx/csrc/offline-recognizer-paraformer-impl.h
To fix the following error for some input waves:
```
2023-09-12 16:36:34.984 sherpa-onnx-offline[64003:6595949] 2023-09-12 16:36:34.984712 
[E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] 
Non-zero status code returned while running ConstantOfShape node. 
Name:'ConstantOfShape_5489' Status Message: /Users/runner/work/1/s/onnxruntime/core/framework/op_kernel.cc:83 
virtual OrtValue *onnxruntime::OpKernelContext::OutputMLValue(int, const onnxruntime::TensorShape &) 
status.IsOK() was false. Tensor shape cannot contain any negative value
2023-09-12 16:36:34.984 sherpa-onnx-offline[64003:6595949] 2023-09-12 16:36:34.984889 
[E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Loop node. 
Name:'Loop_5471' Status Message: Non-zero …
```
=> Catch exception from non-streaming paraformer.

.github/scripts/test-offline-transducer.sh, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/offline-paraformer-decoder.h, sherpa-onnx/csrc/offline-paraformer-greedy-search-decoder.cc, sherpa-onnx/csrc/offline-paraformer-greedy-search-decoder.h, sherpa-onnx/csrc/offline-paraformer-model.cc, sherpa-onnx/csrc/offline-paraformer-model.h, sherpa-onnx/csrc/offline-recognizer-paraformer-impl.h, swift-api-examples/SherpaOnnx.swift, swift-api-examples/decode-file-non-streaming.swift
Note that you have to use
https://huggingface.co/csukuangfj/sherpa-onnx-paraformer-zh-2023-09-14
----
https://huggingface.co/csukuangfj/sherpa-onnx-paraformer-zh-2023-03-28 does not support timestamps.
=> Add timestamps for offline paraformer

sherpa-onnx/csrc/hypothesis.cc
Using 0 as the initial value,  should not perform addition when both values are 0.  It will trigger a bug in the modified beam search algorithm when the language model is not loaded
=> Fix LogAdd

CMakeLists.txt, sherpa-onnx/csrc/symbol-table.cc
```
▁ 259
<0xE8> 235
<0x89> 140
<0xBE> 193
```
The bpe.model  and tokens.txt used for testing are from
https://huggingface.co/zrjin/sherpa-onnx-zipformer-multi-zh-hans-2023-9-2/tree/main
=> Fix tokens for byte-level BPE token.

scripts/whisper/export-onnx.py
Before this pull-request:
```
-rw-r--r--  1 fangjun  staff   105M Aug  7 16:22 tiny.en-decoder.int8.onnx
-rw-r--r--  1 fangjun  staff   185M Sep 20 19:13 tiny.en-decoder.onnx
```
With this pull-request:
```
-rw-r--r--  1 fangjun  staff    86M Sep 20 19:09 tiny.en-decoder.int8.onnx
-rw-r--r--  1 fangjun  staff   109M Sep 20 19:09 tiny.en-decoder.onnx
```
---
It turns out onnx saves a transposed version of `self.textDecoder.token_embedding.weight` at the output when computing `logits`. This PR removes the transposed version to reduce the file size.
---
https://github.com/openai/whisper/#available-models-and-languages
says tiny.en has 39 M parameters, whose file size is about 39 * 1e6 * 4 /1024/1024 = 148.77 MB.
Our exported ONNX model file sizes for float32 are
```
-rw-r--r--  1 fangjun …
```
=> Reduce whisper decoder file size with onnx export

sherpa-onnx/csrc/parse-options.h
=> Added #include <cstdint> to fix gcc 13.2 compilation error.

sherpa-onnx/csrc/session.cc
Default convolution mode is very slow, as a result sherpa-onnx-gpu is much slower than CPU. With this fix the decoding speed is ok.
See also
https://github.com/microsoft/onnxruntime/issues/12880#issuecomment-1330442188
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#cudnn_conv_algo_search
=> Proper convolution mode for fast GPU processing

.github/workflows/export-vits-ljspeech-to-onnx.yaml, scripts/vits/.gitignore, scripts/vits/export-onnx-ljs.py
Note: We are going to support TTS in sherpa-onnx. The first step is to support [vits](https://github.com/jaywalnut310/vits) models.
=> Add script to convert vits models

CMakeLists.txt, cmake/onnxruntime-linux-x86_64.cmake
We need `-pthread -ldl` when link onnxruntime statically on Linux.
=> Fix pkg-config for linux

sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/lexicon.cc, sherpa-onnx/csrc/lexicon.h, sherpa-onnx/csrc/sherpa-onnx-offline-tts.cc, sherpa-onnx/csrc/wave-writer.cc, sherpa-onnx/csrc/wave-writer.h
```
$ ./build/bin/sherpa-onnx-offline-tts --help
/Users/fangjun/open-source/sherpa-onnx/sherpa-onnx/csrc/parse-options.cc:PrintUsage:402
Offline text-to-speech with sherpa-onnx
./bin/sherpa-onnx-offline-tts \
--vits-model /path/to/model.onnx \
--vits-lexicon /path/to/lexicon.txt \
--vits-tokens /path/to/tokens.txt
--output-filename ./generated.wav \
'some text within single quotes'
It will generate a file ./generated.wav as specified by --output-filename.
You can download a test model from
https://huggingface.co/csukuangfj/vits-ljs
For instance, you can use:
wget https://huggingface.co/csukuangfj/vits-ljs/resolve/main/vits-ljs.onnx
wget https://huggingface.co/csukuangfj/vits-ljs/resolve/main/lexicon.txt
wget https://huggingface.co/csukuangfj/vits-ljs/resolve/main/tokens.txt …
```
=> Support writing generated audio samples to wave files

CMakeLists.txt, python-api-examples/offline-tts.py, scripts/vits/.gitignore, scripts/vits/export-onnx-vctk.py, sherpa-onnx/csrc/offline-tts-impl.h, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts-vits-model-config.cc, sherpa-onnx/csrc/offline-tts-vits-model-config.h, sherpa-onnx/csrc/offline-tts-vits-model.cc, sherpa-onnx/csrc/offline-tts-vits-model.h, sherpa-onnx/csrc/offline-tts.cc, sherpa-onnx/csrc/offline-tts.h, sherpa-onnx/csrc/sherpa-onnx-offline-tts.cc, sherpa-onnx/python/csrc/offline-tts-vits-model-config.cc, sherpa-onnx/python/csrc/offline-tts.cc
Please see the documentation at
https://k2-fsa.github.io/sherpa/onnx/tts/index.html
for usages.
=> Support VITS VCTK models

.github/scripts/test-python.sh, .github/workflows/run-python-test.yaml, CMakeLists.txt, cmake/kaldi-decoder.cmake, cmake/kaldi-native-fbank.cmake, cmake/utfcpp.cmake, python-api-examples/offline-tts.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/lexicon.cc, sherpa-onnx/csrc/lexicon.h, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts-vits-model.cc, sherpa-onnx/csrc/offline-tts-vits-model.h, sherpa-onnx/csrc/text-utils.cc, sherpa-onnx/csrc/text-utils.h, sherpa-onnx/csrc/utfcpp-test.cc
```
GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/csukuangfj/vits-zh-aishell3
cd vits-zh-aishell3
git lfs --include "*.onnx"
```
```
./build/bin/sherpa-onnx-offline-tts \
--vits-model=./vits-zh-aishell3/vits-aishell3.onnx \
--vits-lexicon=./vits-zh-aishell3/lexicon.txt \
--vits-tokens=./vits-zh-aishell3/tokens.txt  \
--sid=43 \
--output-filename="43.wav" \
'林美丽最美丽'
```
I have converted 43.wav to 43.mov, which is attached below:
https://github.com/k2-fsa/sherpa-onnx/assets/5284924/3aeb52f5-8870-47cf-bd49-5c1c8fe6212e
Please see
https://k2-fsa.github.io/sherpa/onnx/tts/index.html
for details.
=> Support Chinese vits models

.github/workflows/go.yaml
See also
- https://github.com/egor-tensin/setup-mingw/issues/14
- https://github.com/egor-tensin/setup-mingw/issues/15
=> Fix CI test for Go.

sherpa-onnx/csrc/text-utils.cc
fixes: sherpa-onnx/csrc/text-utils.cc:217:9: error: ‘uint8_t’ does not name a type
=> include cstdint (debian, gcc-13.2)

sherpa-onnx/csrc/lexicon.cc, sherpa-onnx/csrc/lexicon.h, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts-vits-model.cc, sherpa-onnx/csrc/offline-tts-vits-model.h
I have converted the model `en_US-lessac-medium` from [piper](https://github.com/rhasspy/piper) to sherpa-onnx
and you can find the converted model in the following repo:
https://huggingface.co/csukuangfj/vits-piper-en_US-lessac-medium
If you are interested in how the model is converted, please have a look at the following colab notebook:
https://colab.research.google.com/drive/1PScLJV3sbUUAOiptLO7Ixlzh9XnWWoYZ?usp=sharing
In the following, we describe how to use the converted model with sherpa-onnx
```
wget https://huggingface.co/csukuangfj/vits-piper-en_US-lessac-medium/resolve/main/en_US-lessac-medium.onnx
wget https://huggingface.co/csukuangfj/vits-piper-en_US-lessac-medium/resolve/main/lexicon.txt
wget https://huggingface.co/csukuangfj/vits-piper-en_US-lessac-medium/resolve/main/token …
```
=> Support vits models from piper

sherpa-onnx/csrc/lexicon.cc, sherpa-onnx/csrc/lexicon.h, sherpa-onnx/csrc/text-utils.cc
We have managed to convert spanish TTS models from
https://huggingface.co/rhasspy/piper-voices/tree/main/es
to sherpa-onnx.
You can try it by visiting
https://huggingface.co/spaces/k2-fsa/text-to-speech
Note: You don't need to install anything to try it. All you need is a browser.
---
Two generated audios are attached below.
https://github.com/k2-fsa/sherpa-onnx/assets/5284924/daa2337a-5ea9-4e30-948d-453f8bb4399e
https://github.com/k2-fsa/sherpa-onnx/assets/5284924/dfb99911-2d29-46c1-9add-2855c09843cc
=> Support Spanish in TTS

CMakeLists.txt, sherpa-onnx/csrc/lexicon.cc, sherpa-onnx/csrc/lexicon.h, sherpa-onnx/csrc/text-utils.cc
We have converted [piper models](https://huggingface.co/rhasspy/piper-voices/tree/main/fr) to sherpa-onnx for French TTS.
You can try it in your browser by visiting the following URL without installing anything
https://huggingface.co/spaces/k2-fsa/text-to-speech
https://github.com/k2-fsa/sherpa-onnx/assets/5284924/e0df6bf5-a0d2-4cc2-b7ce-f9be2921cdea
=> Support French in TTS

CMakeLists.txt, cmake/kaldifst.cmake, cmake/onnxruntime-linux-aarch64.cmake, cmake/onnxruntime-linux-x86_64-gpu.cmake, cmake/onnxruntime-linux-x86_64.cmake, cmake/onnxruntime-osx-arm64.cmake, cmake/onnxruntime-osx-universal.cmake, cmake/onnxruntime-osx-x86_64.cmake, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts.cc, sherpa-onnx/csrc/offline-tts.h, sherpa-onnx/python/csrc/offline-tts.cc
First, download moel files:
```
wget https://huggingface.co/csukuangfj/vits-zh-aishell3/resolve/main/vits-aishell3.onnx
wget https://huggingface.co/csukuangfj/vits-zh-aishell3/resolve/main/lexicon.txt
wget https://huggingface.co/csukuangfj/vits-zh-aishell3/resolve/main/tokens.txt
wget https://huggingface.co/csukuangfj/vits-zh-aishell3/resolve/main/rule.fst
```
After building sherpa-onnx, you can use
```bash
./build/bin/sherpa-onnx-offline-tts  \
--vits-model=./vits-aishell3.onnx \
--vits-lexicon=./lexicon.txt \
--vits-tokens=./tokens.txt \
--sid=99 \
--debug=1 \
--output-filename=./99.wav  \
--tts-rule-fsts="./rule.fst" \
"理科全省前7434名、文科全省前871名. 在传统高考地区中，文科考生想要考上中南大学，最低也要进入全省前2400名，理科生想考上中南大学，最低需要排进全省前21409名. 99.99"
```
The output is given below:
``` …
```
=> Support text normalization via rule FST

.github/workflows/export-whisper-to-onnx.yaml, scripts/whisper/export-onnx.py
Support models from https://github.com/huggingface/distil-whisper
You can find a colab for it at
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/Run_distil_whisper_with_sherpa_onnx_on_CPU.ipynb)
---
1. Install sherpa-onnx
```
pip install sherpa-onnx
```
2. Use the model
```
mkdir sherpa-onnx-whisper-distil-medium.en
cd sherpa-onnx-whisper-distil-medium.en
wget -q https://huggingface.co/csukuangfj/sherpa-onnx-whisper-distil-medium.en/resolve/main/distil-medium.en-decoder.int8.onnx
wget -q https://huggingface.co/csukuangfj/sherpa-onnx-whisper-distil-medium.en/resolve/main/distil-medium.en-encoder.int8.onnx
wget -q https://huggingface.co/csukuangfj/sherpa-onnx-whisper-distil-medium.en/resolve/main/distil-medi …
```
=> Support distil-whisper

.github/workflows/export-wenet-to-onnx.yaml, scripts/wenet/README.md, scripts/wenet/export-onnx-streaming.py, scripts/wenet/export-onnx.py, scripts/wenet/run.sh, scripts/wenet/test-onnx-streaming.py, scripts/wenet/test-onnx.py
Will add the runtime support later.
=> Add scripts to export ASR models from wenet to ONNX

sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc
When the cached decoder out of the entire batch exists, then use it.
=> Judge before UseCachedDecoderOut

sherpa-onnx/csrc/offline-transducer-modified-beam-search-decoder.cc, sherpa-onnx/csrc/online-rnn-lm.cc, sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.cc, sherpa-onnx/csrc/online-wenet-ctc-model.cc
Replace `Clone()` with `View()`
=> Replace Clone() with View()

.gitignore, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts.xcodeproj/project.pbxproj, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts.xcodeproj/project.xcworkspace/contents.xcworkspacedata, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/Assets.xcassets/AccentColor.colorset/Contents.json, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/Assets.xcassets/AppIcon.appiconset/Contents.json, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/Assets.xcassets/Contents.json, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/ContentView.swift, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/Preview Content/Preview Assets.xcassets/Contents.json, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/SherpaOnnxTtsApp.swift, ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/ViewModel.swift, swift-api-examples/SherpaOnnx.swift
You can find a YouTube video showing how to use it at the following address
https://www.youtube.com/watch?v=MvePdkuMNJk
=> Text-to-speech for iOS

sherpa-onnx/csrc/online-websocket-server-impl.cc
Lock before push_back the deque for thread safety.
=> Lock before push_back the deque for thread safety

sherpa-onnx/csrc/lexicon.cc
```
fangjuns-MacBook-Pro:sherpa-onnx fangjun$ hexdump -c -x -n 10 ./vits-zh-aishell3/tokens.txt
0000000   s   i   l       0  \n   e   o   s
0000000    6973    206c    0a30    6f65    2073
000000a
fangjuns-MacBook-Pro:sherpa-onnx fangjun$ hexdump -c -x -n 10 ~/Downloads/tokens.txt
0000000   s   i   l       0  \r  \n   e   o   s
0000000    6973    206c    0d30    650a    736f
000000a
```
`~/Downloads/tokens.txt` is from a user who downloads it on Windows using git.
This PR handles `\r\n` correctly in case `tokens.txt`  contains `\r\n`.
=> Fix reading tokens.txt on Windows

android/SherpaOnnxTts/app/src/main/java/com/k2fsa/sherpa/onnx/Tts.kt, python-api-examples/offline-tts-play.py, scripts/apk/generate-tts-apk-script.py, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts-vits-model-config.cc, sherpa-onnx/csrc/offline-tts-vits-model-metadata.h, sherpa-onnx/csrc/offline-tts-vits-model.cc, sherpa-onnx/csrc/offline-tts-vits-model.h, sherpa-onnx/csrc/piper-phonemize-lexicon.cc, sherpa-onnx/csrc/piper-phonemize-lexicon.h
```bash
cd sherpa-onnx
mkdir build
cmake ..
make -j
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-en-ljspeech.tar.bz2
tar xf vits-coqui-en-ljspeech.tar.bz2
./bin/sherpa-onnx-offline-tts-play \
--vits-model=./vits-coqui-en-ljspeech/model.onnx \
--vits-tokens=./vits-coqui-en-ljspeech/tokens.txt \
--vits-data-dir=./vits-coqui-en-ljspeech/espeak-ng-data \
--num-threads=3 \
--output-filename=./abc.wav \
--debug=1 \
"Friends fell out often because life was changing so fast. The easiest thing in the world was to lose touch with someone. The best day of the month was payday. But in a way it was the worst day, too. After you had worked hard for so long, it was infuriating to see how much money had been docked for …
```
=> Use espeak-ng for coqui-ai/TTS VITS English models.

mfc-examples/NonStreamingTextToSpeech/NonStreamingTextToSpeechDlg.cpp, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/offline-tts-character-frontend.cc, sherpa-onnx/csrc/offline-tts-character-frontend.h, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts-vits-model-config.cc, sherpa-onnx/csrc/offline-tts-vits-model-metadata.h, sherpa-onnx/csrc/offline-tts-vits-model.cc, sherpa-onnx/csrc/piper-phonemize-lexicon.cc
CC @magicse 
You can find the model at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models
```
cd sherpa-onnx
mkdir build
cd build
cmake ..
make -j
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-coqui-uk-mai.tar.bz2
tar xf vits-coqui-uk-mai.tar.bz2
./bin/sherpa-onnx-offline-tts-play
--vits-model=./vits-coqui-uk-mai/model.onnx \
--vits-tokens=./vits-coqui-uk-mai/tokens.txt \
--num-threads=1 \
--output-filename=./abc.wav \
--debug=1 \
"Сьогодні, як завжди, люди діляться на дві групи: раби і вільні люди. Той, хто не має двох третин свого дня для себе, є рабом, ким би він не був: державним діячем, бізнесменом, чиновником чи вченим. "
```
You can visit the following huggingface space …
=> Support Ukrainian VITS models from coqui-ai/TTS

.github/scripts/test-offline-whisper.sh, .github/workflows/export-whisper-to-onnx.yaml, .github/workflows/linux.yaml, .github/workflows/windows-x86.yaml, scripts/whisper/export-onnx.py, scripts/whisper/test.py, sherpa-onnx/csrc/offline-recognizer-whisper-impl.h, sherpa-onnx/csrc/offline-whisper-model-config.cc, sherpa-onnx/csrc/offline-whisper-model-config.h, sherpa-onnx/python/csrc/offline-whisper-model-config.cc
This PR removes the 30-second constraint for whisper models
In other words, you don't need to pad your audio to 30 seconds. Any duration T <= 30 can be used for whisper models.
You can save computation by removing paddings.
You can find the exported models at
=> Remove the 30-second constraint from whisper. 

.github/workflows/export-wespeaker-to-onnx.yaml, scripts/wespeaker/README.md, scripts/wespeaker/add_meta_data.py, scripts/wespeaker/run.sh, scripts/wespeaker/test.py
You can find the converted models from [wespeaker](https://github.com/wenet-e2e/wespeaker)
at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/speaker-recongition-models
=> convert wespeaker models to sherpa-onnx

android/SherpaOnnxTts/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt, android/SherpaOnnxTts/app/src/main/java/com/k2fsa/sherpa/onnx/Tts.kt, kotlin-api-examples/Main.kt, scripts/apk/generate-tts-apk-script.py, sherpa-onnx/jni/jni.cc
You can find a video demo at
https://www.bilibili.com/video/BV17a4y1d7Ha/
=> Support playing as it is generating for Android

sherpa-onnx/csrc/piper-phonemize-lexicon.cc
Turns out espeak-ng is not thread-safe. This PR adds a lock for espeak-ng.
=> Keep multiple threads from calling into espeak-ng at the same time

android/SherpaOnnx2Pass/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt, kotlin-api-examples/.gitignore, kotlin-api-examples/SherpaOnnx2Pass.kt, kotlin-api-examples/run.sh, kotlin-api-examples/test-2pass.kt
To fix the following error
```
11964/com.k2fsa.sherpa.onnx A/art: art/runtime/runtime.cc:404] 
Pending exception java.lang.NoSuchFieldError: 
no type "Lcom/k2fsa/sherpa/onnx/OnlineZipformer2CtcModelConfig;" 
found and so no field "zipformer2Ctc" could be found in 
class "Lcom/k2fsa/sherpa/onnx/OnlineModelConfig;" or its superclasses
```
Also, add a test for two-pass.
=> Add missing field for two-pass APK.

sherpa-onnx/csrc/offline-recognizer-ctc-impl.h, sherpa-onnx/csrc/offline-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-recognizer-ctc-impl.h, sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/python/csrc/offline-stream.cc, sherpa-onnx/python/csrc/online-recognizer.cc
It ignores invalid UTF8 strings.
Closes #501. The method in this PR is simpler than that of #501
=> Fix Byte BPE string results for Python.

python-api-examples/speaker-identification.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/context-graph-test.cc, sherpa-onnx/csrc/session.cc, sherpa-onnx/csrc/session.h, sherpa-onnx/csrc/speaker-embedding-extractor-impl.cc, sherpa-onnx/csrc/speaker-embedding-extractor-impl.h, sherpa-onnx/csrc/speaker-embedding-extractor-wespeaker-impl.h, sherpa-onnx/csrc/speaker-embedding-extractor-wespeaker-model-metadata.h, sherpa-onnx/csrc/speaker-embedding-extractor-wespeaker-model.cc, sherpa-onnx/csrc/speaker-embedding-extractor-wespeaker-model.h, sherpa-onnx/csrc/speaker-embedding-extractor.cc, sherpa-onnx/csrc/speaker-embedding-extractor.h, sherpa-onnx/csrc/speaker-embedding-manager-test.cc, sherpa-onnx/csrc/speaker-embedding-manager.cc, sherpa-onnx/csrc/speaker-embedding-manager.h, sherpa-onnx/csrc/voice-activity-detector.cc, sherpa-onnx/csrc/voice-activity-detector.h, sherpa-onnx/python/csrc/CMakeLists.txt, sherpa-onnx/python/csrc/online-recognizer.h, sherpa-onnx/python/csrc/sherpa-onnx.cc, sherpa-onnx/python/csrc/speaker-embedding-extractor.cc, sherpa-onnx/python/csrc/speaker-embedding-extractor.h, sherpa-onnx/python/csrc/speaker-embedding-manager.cc, sherpa-onnx/python/csrc/speaker-embedding-manager.h, sherpa-onnx/python/csrc/voice-activity-detector.cc, sherpa-onnx/python/sherpa_onnx/__init__.py
```
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/speaker-recongition-models/zh_cnceleb_resnet34.onnx
wget https://huggingface.co/openspeech/wespeaker-models/resolve/main/test_wavs/00001_spk1.wav
wget https://huggingface.co/openspeech/wespeaker-models/resolve/main/test_wavs/00024_spk1.wav
wget https://huggingface.co/openspeech/wespeaker-models/resolve/main/test_wavs/00010_spk2.wav
```
```python3
#!/usr/bin/env python3
import sherpa_onnx
import torchaudio
import torch
def load_audio(filename):
samples, sample_rate = torchaudio.load(filename)
return samples[0].contiguous().numpy(), sample_rate
def main():
model = "./zh_cnceleb_resnet34.onnx"
config = sherpa_onnx.SpeakerEmbeddingExtractorConfig(
model=model,
num_threads=1,
debug=True,
provider="cpu",
)
print(config)
extractor …
```
=> Add runtime support for wespeaker models

.github/scripts/test-speaker-recognition-python.sh, .github/workflows/export-nemo-speaker-verification-to-onnx.yaml, python-api-examples/speaker-identification.py, scripts/3dspeaker/run.sh, scripts/nemo/README.md, scripts/nemo/speaker-verification/README.md, scripts/nemo/speaker-verification/export-onnx.py, scripts/nemo/speaker-verification/run.sh, scripts/nemo/speaker-verification/test-onnx.py, scripts/wespeaker/run.sh
You can find the exported ONNX models at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/speaker-recongition-models
Note that we have managed to export only 3 out of 4 models from NeMo.
Please see also
https://github.com/NVIDIA/NeMo/issues/8168
=> Export speaker verification models from NeMo to ONNX

android/SherpaOnnxTts/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt, android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt, android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/TtsEngine.kt, android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/TtsService.kt
It used a slider to set the speaker ID for the Android TTS engine, and users could only select 3 speakers.
This PR fixes that by using a text field. You can find a screenshot with this PR below:
=> Fix setting speaker ID for Android TTS Engine.

python-api-examples/speaker-identification-with-vad-non-streaming-asr.py, python-api-examples/speaker-identification-with-vad.py
```bash
python3 ./python-api-examples/speaker-identification-with-vad.py \
--silero-vad-model ./silero_vad.onnx \
--threshold 0.5 \
--model ./3dspeaker_speech_eres2net_large_sv_zh-cn_3dspeaker_16k.onnx \
--speaker-file ./speaker.txt
```
```bash
python3 ./python-api-examples/speaker-identification-with-vad-non-streaming-asr.py \
--paraformer ./sherpa-onnx-paraformer-zh-2023-03-28/model.int8.onnx \
--tokens ./sherpa-onnx-paraformer-zh-2023-03-28/tokens.txt \
--silero-vad-model ./silero_vad.onnx \
--threshold 0.5 \
--model ./3dspeaker_speech_eres2net_large_sv_zh-cn_3dspeaker_16k.onnx \
--speaker-file ./speaker.txt
```
where `speaker.txt` contains:
```
雷军 ./sr-data/enroll/leijun-sr-1.wav
雷军 ./sr-data/enroll/leijun-sr-2.wav
fangjun ./sr-data/enroll/fangjun-sr-1.wav
fangjun …
```
=> Add Python API examples for speaker recognition with VAD and ASR.

python-api-examples/non_streaming_server.py, python-api-examples/offline-decode-files.py, python-api-examples/vad-with-non-streaming-asr.py, sherpa-onnx/csrc/math.h, sherpa-onnx/csrc/offline-recognizer-transducer-impl.h, sherpa-onnx/csrc/offline-recognizer.cc, sherpa-onnx/csrc/offline-recognizer.h, sherpa-onnx/csrc/offline-transducer-greedy-search-decoder.cc, sherpa-onnx/csrc/offline-transducer-greedy-search-decoder.h, sherpa-onnx/csrc/offline-transducer-modified-beam-search-decoder.cc, sherpa-onnx/csrc/offline-transducer-modified-beam-search-decoder.h, sherpa-onnx/python/csrc/offline-recognizer.cc, sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
Fix https://github.com/k2-fsa/sherpa-onnx/issues/541
Tested with `sherpa-onnx-offline`. High penalty will force out more words.
=> add blank_penalty for offline transducer

sherpa-onnx/csrc/offline-recognizer-ctc-impl.h, sherpa-onnx/csrc/offline-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-recognizer-ctc-impl.h, sherpa-onnx/csrc/online-recognizer-transducer-impl.h
- This is to avoid output like : `[' K', '<0x64>', '<0x79>', 'ť', ' a', '<0x75>', 'to', 'bu', '<0x73>', '<0x75>', ... ]` with regular 500 BPE units.
- Don't rewrite 1-char output tokens in range `[ 0x20 (space) .. 0x7E (tilde) ]`
=> Fixes issue #535 , fix hexa 1-char tokens in ASR output.

android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt, android/SherpaOnnx2Pass/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt, sherpa-onnx/jni/jni.cc, swift-api-examples/SherpaOnnx.swift
I implement context biasing (hot words) for android/ios frontend by calling:
```
Reset(hotWords)
```
=> Add context biasing for mobile

sherpa-onnx/python/csrc/online-recognizer.cc, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
This PR adds missing "start_time" to OnlineRecognizeer results in Python API.
This allows "client" to calculate absolute timestamps in the audio stream.
=> Add missing "start_time" to Python API

build-ios.sh
Users don't need to use `git lfs` to download the ios onnxruntime libs any longer.
=> Download ios-onnxruntime from github instead of huggingface.

cmake/cmake_extension.py, setup.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/sherpa-onnx-alsa-offline-speaker-identification.cc, sherpa-onnx/csrc/sherpa-onnx-alsa.cc
On embedded linux boards, alsa works while portaudio does not.
=> Use alsa to read microphone in speaker identification demo.

cmake/onnxruntime-linux-aarch64-static.cmake, cmake/onnxruntime-linux-aarch64.cmake, cmake/onnxruntime-linux-arm-static.cmake, cmake/onnxruntime-linux-arm.cmake, cmake/onnxruntime-linux-x86_64-gpu.cmake, cmake/onnxruntime-linux-x86_64-static.cmake, cmake/onnxruntime-linux-x86_64.cmake, cmake/onnxruntime-osx-arm64-static.cmake, cmake/onnxruntime-osx-arm64.cmake, cmake/onnxruntime-osx-universal-static.cmake, cmake/onnxruntime-osx-universal.cmake, cmake/onnxruntime-osx-x86_64-static.cmake, cmake/onnxruntime-osx-x86_64.cmake, cmake/onnxruntime-win-x64-gpu.cmake, cmake/onnxruntime-win-x64-static-debug.cmake, cmake/onnxruntime-win-x64-static.cmake, cmake/onnxruntime-win-x64.cmake, cmake/onnxruntime-win-x86-static-debug.cmake, cmake/onnxruntime-win-x86-static.cmake, cmake/onnxruntime-win-x86.cmake, cmake/portaudio.cmake, cmake/pybind11.cmake, cmake/websocketpp.cmake
This is mainly for Chinese users since most of them cannot access Huggingface and some cannot access GitHub.
=> Use hub.nuaa.cf to replace huggingface URL to download dependencies.

.gitignore, sherpa-onnx/csrc/hypothesis.h, sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-recognizer.cc, sherpa-onnx/csrc/online-recognizer.h, sherpa-onnx/csrc/online-transducer-decoder.cc, sherpa-onnx/csrc/online-transducer-decoder.h, sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.cc, sherpa-onnx/python/csrc/online-recognizer.cc, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
Hello,
I modified the code, so that the per-token scores are accessible via python API 
(ys_probs, lm_probs, context_scores).
This is tracked during the modified beam search decoding of online transduces,
and it is exported for the BestHypothesis.
Would you be interesting in having this functionality in the codebase ?
This can be used as confidences from the client side...
But I did not evaluate it yet, to see how "useful" these numbers are.
I am ready to do changes as well. I'd like to open the discussion...
Best regards
K. Veselý
=> Track token scores

CMakeLists.txt, cmake/kaldi-native-fbank.cmake
Fixes #615 
See also https://github.com/csukuangfj/kaldi-native-fbank/pull/38
=> Fix computing features for whisper.

build-android-arm64-v8a.sh, sherpa-onnx/csrc/provider.cc, sherpa-onnx/csrc/provider.h, sherpa-onnx/csrc/session.cc
To use Android NNAPI, you need to do the following two steps:
1. Change
https://github.com/k2-fsa/sherpa-onnx/blob/f9db33c9268b20e7bc50c24637fb04bf3fa83e65/build-android-arm64-v8a.sh#L77
to
```
-DANDROID_PLATFORM=android-27 .. 
```
2. Use `nnapi` instead of `cpu` for the provider.
An example is to change
https://github.com/k2-fsa/sherpa-onnx/blob/f9db33c9268b20e7bc50c24637fb04bf3fa83e65/android/SherpaOnnx/app/src/main/java/com/k2fsa/sherpa/onnx/SherpaOnnx.kt#L40
to
```
var provider: String = "nnapi", 
```
=> Support Android NNAPI.

MANIFEST.in
With this PR, you can use
```
pip install --no-binary sherpa-onnx sherpa-onnx
```
to install sherpa-onnx from source when we release the next version, i.e., `v1.9.12`.
=> Fix building wheels from source.

.github/workflows/build-wheels-aarch64.yaml, .github/workflows/build-wheels-linux.yaml, .github/workflows/linux.yaml, cmake/onnxruntime-linux-aarch64.cmake, cmake/onnxruntime-linux-x86_64.cmake
From onnxruntime >= 1.17.0, the pre-compiled shared lib drops support for CentOS 7.0 and it supports only manylinux_2_28.
However, a lot of users are still using CentOS 7 and ubuntu 18.04. They get errors when running `pip install sherpa-onnx`.
This PR fixes the issue by using self pre-compiled shared onnxruntime lib.
=> Support Ubuntu 18.04 and CentOS 7

.github/workflows/test-dot-net.yaml, scripts/dotnet/generate.py, scripts/dotnet/run.sh, scripts/dotnet/sherpa-onnx.csproj.in, sherpa-onnx/csrc/lexicon.cc
=> Add nuget package for Windows x86

cmake/kaldi-native-fbank.cmake, sherpa-onnx/csrc/features.cc, sherpa-onnx/csrc/features.h, sherpa-onnx/csrc/keyword-spotter-transducer-impl.h, sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-transducer-model.h, sherpa-onnx/csrc/online-zipformer2-transducer-model.cc, sherpa-onnx/csrc/online-zipformer2-transducer-model.h, sherpa-onnx/python/csrc/features.cc, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
add support of non-default config of FBANK features
- i built telephone speech ASR system with 56-dim fbanks with low_freq=80, high_freq=3600
- i have a signal with hard-zeros in it, so dithering would be valuable
(i noticed that dithering is not yet in https://github.com/csukuangfj/kaldi-native-fbank)
(i think of porting it there from kaldi, just the constant will be 1/(2^15)-times smaller)
=> Configurable low_freq high_freq, dithering

.github/workflows/build-xcframework.yaml, .github/workflows/linux.yaml, .github/workflows/macos.yaml, .github/workflows/windows-x64.yaml, .github/workflows/windows-x86.yaml, CMakeLists.txt, build-ios-no-tts.sh, c-api-examples/CMakeLists.txt, cmake/sherpa-onnx-no-tts.pc.in, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/jni/jni.cc, sherpa-onnx/python/csrc/CMakeLists.txt, sherpa-onnx/python/csrc/sherpa-onnx.cc
Fixes #498 
Closes #500
If you only want the ASR functions of `sherpa-onnx`, you can set
```
-DSHERPA_ONNX_ENABLE_TTS=OFF
```
while building `sherpa-onnx`.
Note it is useful for developers who want to integrate `sherpa-onnx` in their projects using only the C API.
The generated libraries don't depend on TTS-related stuff, e.g., no dependencies on `espeak-ng`.
Note that even if the `c-api.h` still contains TTS-related declarations, it won't cause any compilation errors as long
as you don't call those TTS-related functions in your projects. Or you can safely delete them if you want.
CC @rkjaran
=> Support including TTS conditionally.

ios-swiftui/SherpaOnnx/SherpaOnnx.xcodeproj/project.pbxproj, ios-swiftui/SherpaOnnx/SherpaOnnx/Info.plist, ios-swiftui/SherpaOnnx/SherpaOnnx/SherpaOnnxViewModel.swift
Fix https://github.com/k2-fsa/sherpa-onnx/issues/444
=> Fix microphone privacy config

sherpa-onnx/python/csrc/offline-stream.cc, sherpa-onnx/python/csrc/online-stream.cc
If the GIL is released, we should not access any Python-related objects in the C++ code.
=> Fix releasing GIL

.github/scripts/test-audio-tagging.sh, .github/workflows/linux.yaml, .github/workflows/macos.yaml, .github/workflows/windows-x64.yaml, .github/workflows/windows-x86.yaml, cmake/cmake_extension.py, go-api-examples/vad-asr-paraformer/.gitignore, nodejs-examples/test-offline-tts-zh.js, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/audio-tagging-impl.cc, sherpa-onnx/csrc/audio-tagging-impl.h, sherpa-onnx/csrc/audio-tagging-label-file.cc, sherpa-onnx/csrc/audio-tagging-label-file.h, sherpa-onnx/csrc/audio-tagging-model-config.cc, sherpa-onnx/csrc/audio-tagging-model-config.h, sherpa-onnx/csrc/audio-tagging-zipformer-impl.h, sherpa-onnx/csrc/audio-tagging.cc, sherpa-onnx/csrc/audio-tagging.h, sherpa-onnx/csrc/math.h, sherpa-onnx/csrc/offline-stream.cc, sherpa-onnx/csrc/offline-stream.h, sherpa-onnx/csrc/offline-zipformer-audio-tagging-model-config.cc, sherpa-onnx/csrc/offline-zipformer-audio-tagging-model-config.h, sherpa-onnx/csrc/offline-zipformer-audio-tagging-model.cc, sherpa-onnx/csrc/offline-zipformer-audio-tagging-model.h, sherpa-onnx/csrc/offline-zipformer-ctc-model.cc, sherpa-onnx/csrc/offline-zipformer-ctc-model.h, sherpa-onnx/csrc/session.cc, sherpa-onnx/csrc/session.h, sherpa-onnx/csrc/sherpa-onnx-offline-audio-tagging.cc
The model is from
https://github.com/k2-fsa/icefall/pull/1421
CC @marcoyang1998
=> Support audio tagging using zipformer

sherpa-onnx/csrc/transducer-keyword-decoder.cc
A vector variable `best_hyp.ys_probs` contains the probabilities of each token in a matched keyword whose length is `level`.
The code checks if the mean of `best_hyp.ys_probs` is greater than or equal to a threshold.
Currently, when calculating the mean, the index ranges from 1 to `level`.
This excludes the first token (at index 0) and includes an undefined value at the end.
In most cases,  this undefined value is zero so the code seems to work fine.
Change the index to range  from 0 to `level`-1.
=> Fix a bug in mean calculation of 'ys_probs'

python-api-examples/speaker-identification-with-vad-non-streaming-asr.py, python-api-examples/speaker-identification-with-vad.py, python-api-examples/speaker-identification.py
`torchaudio` is a part of `PyTorch`. 
`PyTorch` is very large, but only a small part is used in `python-api-examples`.
In real projects,  it is no need to use `PyTorch`,
`soundfile` is smaller and has been used in the project,
So, I replace `torchaudio` with `soundfile` in `python-api-examples`,
Please review :)
=> Replace torchaudio with soundfile in python-api-examples

sherpa-onnx/csrc/speaker-embedding-manager.cc, sherpa-onnx/csrc/speaker-embedding-manager.h, sherpa-onnx/python/csrc/speaker-embedding-manager.cc
Adding a function to `SpeakerEmbeddingManager` to output the match scores. https://github.com/k2-fsa/sherpa-onnx/issues/769
=> Add score function to speaker identification

.github/workflows/run-java-test.yaml, java-api-examples/.gitignore, java-api-examples/NonStreamingDecodeFileParaformer.java, java-api-examples/NonStreamingDecodeFileTransducer.java, java-api-examples/NonStreamingDecodeFileWhisper.java, java-api-examples/README.md, java-api-examples/StreamingDecodeFileCtc.java, java-api-examples/StreamingDecodeFileParaformer.java, java-api-examples/StreamingDecodeFileTransducer.java, java-api-examples/run-non-streaming-decode-file-paraformer.sh, java-api-examples/run-non-streaming-decode-file-transducer.sh, java-api-examples/run-non-streaming-decode-file-whisper.sh, sherpa-onnx/java-api/Makefile, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineModelConfig.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineParaformerModelConfig.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineRecognizer.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineRecognizerConfig.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineRecognizerResult.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineStream.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineTransducerModelConfig.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineWhisperModelConfig.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OnlineModelConfig.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OnlineRecognizer.java, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OnlineRecognizerConfig.java
=> Add Java API for non-streaming ASR

sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-recognizer.cc, sherpa-onnx/csrc/online-recognizer.h, sherpa-onnx/csrc/online-transducer-greedy-search-decoder.cc, sherpa-onnx/csrc/online-transducer-greedy-search-decoder.h, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.cc, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.h, sherpa-onnx/python/csrc/online-recognizer.cc, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
- T is configurable
- so far best result NCE 0.122 (still not so high) 
- the BPE scores were rescaled with 0.2 (but then also incorrect words get high confidence, visually reasonable histograms are for 0.5 scale) 
- BPE->WORD score merging done by min(.) function (tried also prob-product, and also arithmetic, geometric, harmonic mean)
- without temperature scaling (i.e. scale 1.0), the best NCE was 0.032 (here product merging was the best)
Results seem consistent with: https://arxiv.org/abs/2110.15222
Everything tuned on a very small set of 100 sentences with 813 words and 10.2% WER, a Czech model.
I also experimented with blank posteriors mixed into the BPE confidences, but no NCE improvement found, so not pushing that.
Temperature scling added also to the Greedy search confidences.
=> Adding temperature scaling on Joiner logits:

.github/workflows/export-nemo-fast-conformer-hybrid-transducer-ctc.yaml, scripts/nemo/fast-conformer-hybrid-transducer-ctc/README.md, scripts/nemo/fast-conformer-hybrid-transducer-ctc/export-onnx-ctc.py, scripts/nemo/fast-conformer-hybrid-transducer-ctc/run-ctc.sh, scripts/nemo/fast-conformer-hybrid-transducer-ctc/test-onnx-ctc.py
Fixes #790
CC @tempops @sangeet2020
Also CC @titu1994
Exported models can be found at
---
Will add
=> Export NeMo FastConformer Hybrid Transducer-CTC Large Streaming to ONNX.

sherpa-onnx/csrc/offline-punctuation-ct-transformer-impl.h
Solve the issue of missing the last sentence with punctuation.
i just use the sample text, here is the result:
Input text: 你好吗how are you Fantasitic谢谢我很好你怎么样呢
Output text: 你好吗？how are you Fantasitic？
this commit is aim to fix this issue, here is the fix result:
Input text: 你好吗how are you Fantasitic谢谢我很好你怎么样呢
Output text: 你好吗？how are you Fantasitic？谢谢我很好，你怎么样呢？
=> Solve the issue of missing the last sentence with punctuation

.github/scripts/test-online-ctc.sh, .github/scripts/test-python.sh, .github/workflows/linux.yaml, python-api-examples/online-nemo-ctc-decode-files.py, scripts/nemo/fast-conformer-hybrid-transducer-ctc/test-onnx-ctc.py, scripts/nemo/fast-conformer-hybrid-transducer-ctc/test-onnx-transducer.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/offline-punctuation-ct-transformer-impl.h, sherpa-onnx/csrc/online-ctc-model.cc, sherpa-onnx/csrc/online-model-config.cc, sherpa-onnx/csrc/online-model-config.h, sherpa-onnx/csrc/online-nemo-ctc-model-config.cc, sherpa-onnx/csrc/online-nemo-ctc-model-config.h, sherpa-onnx/csrc/online-nemo-ctc-model.cc, sherpa-onnx/csrc/online-nemo-ctc-model.h, sherpa-onnx/csrc/online-recognizer-impl.cc, sherpa-onnx/python/csrc/CMakeLists.txt, sherpa-onnx/python/csrc/online-model-config.cc, sherpa-onnx/python/csrc/online-nemo-ctc-model-config.cc, sherpa-onnx/python/csrc/online-nemo-ctc-model-config.h, sherpa-onnx/python/csrc/online-recognizer.cc, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
Following https://github.com/k2-fsa/sherpa-onnx/pull/843
=> Add C++ support for streaming NeMo CTC models.

sherpa-onnx/csrc/audio-tagging-impl.cc, sherpa-onnx/csrc/keyword-spotter-transducer-impl.h
Found 2 error
Not sure how these were missed/ why they are occurring now
I am on ubuntu machine with g++10 compiler
2 errors
1. Obvious code bug, as Hypothesis class function is having Size() as method
2. Suspecting that SHERPA_ONNX_LOG() function input format is `SHERPA_ONNX_LOG(Type) << "";`
1. 
```
1. /mnt/efs/manickavela/asr_work/trt/sherpa-onnx/sherpa-onnx/csrc/keyword-spotter-transducer-impl.h:310:33: error: ‘class sherpa_onnx::Hypotheses’ has no member named ‘size’; did you mean ‘Size’?
310 |     SHERPA_ONNX_CHECK_EQ(r.hyps.size(), 1);
|                                 ^~~~
/mnt/efs/manickavela/asr_work/trt/sherpa-onnx/sherpa-onnx/csrc/log.h:306:5: note: in definition of macro ‘_SHERPA_ONNX_CHECK_OP’
306 |   ((x)op(y)) ? (void)0 …
```
=> Compiler Error and Minor Bug fix

.github/scripts/node-addon/README.md, .github/workflows/test-nodejs-addon-npm.yaml, nodejs-addon-examples/README.md, nodejs-addon-examples/package.json, nodejs-addon-examples/test_asr_non_streaming_nemo_ctc.js, nodejs-addon-examples/test_asr_non_streaming_paraformer.js, nodejs-addon-examples/test_asr_non_streaming_transducer.js, nodejs-addon-examples/test_asr_non_streaming_whisper.js, nodejs-addon-examples/test_asr_streaming_ctc.js, nodejs-addon-examples/test_asr_streaming_ctc_hlg.js, nodejs-addon-examples/test_asr_streaming_paraformer.js, nodejs-addon-examples/test_asr_streaming_transducer.js, nodejs-addon-examples/test_audio_tagging_ced.js, nodejs-addon-examples/test_audio_tagging_zipformer.js, nodejs-addon-examples/test_keyword_spotter_transducer.js, nodejs-addon-examples/test_tts_non_streaming_vits_coqui_de.js, nodejs-addon-examples/test_tts_non_streaming_vits_piper_en.js, nodejs-addon-examples/test_tts_non_streaming_vits_zh_aishell3.js, nodejs-addon-examples/test_tts_non_streaming_vits_zh_ll.js
Also, use `Date.now()` to replace `performance.now()` since `performance` is not available in earlier versions of node.
=> Fix sherpa-onnx-node-version in node examples

sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h
Added following new fields in offline recognizer result
- tokens
- tokens_arr 
- json
=> Added tokens, tokens_arr and json for offline recognizer result

swift-api-examples/SherpaOnnx.swift
=> fix: Typo 'maxNumSenetences' in SherpaOnnx.swift

.github/scripts/test-online-transducer.sh, .github/workflows/aarch64-linux-gnu-shared.yaml, .github/workflows/aarch64-linux-gnu-static.yaml, .github/workflows/android.yaml, .github/workflows/arm-linux-gnueabihf.yaml, .github/workflows/build-xcframework.yaml, .github/workflows/riscv64-linux.yaml, .github/workflows/windows-x64.yaml, .github/workflows/windows-x86.yaml, sherpa-onnx/csrc/online-recognizer-impl.cc, sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-recognizer-transducer-nemo-impl.h, sherpa-onnx/csrc/online-stream.cc, sherpa-onnx/csrc/online-stream.h, sherpa-onnx/csrc/online-transducer-greedy-search-nemo-decoder.cc, sherpa-onnx/csrc/online-transducer-greedy-search-nemo-decoder.h, sherpa-onnx/csrc/online-transducer-nemo-model.cc, sherpa-onnx/csrc/online-transducer-nemo-model.h
=> Fix nemo streaming transducer greedy search

sherpa-onnx/csrc/offline-ctc-decoder.h, sherpa-onnx/csrc/offline-ctc-fst-decoder.cc, sherpa-onnx/csrc/offline-paraformer-greedy-search-decoder.cc, sherpa-onnx/csrc/offline-recognizer-ctc-impl.h, sherpa-onnx/csrc/offline-stream.cc, sherpa-onnx/csrc/offline-stream.h, sherpa-onnx/csrc/online-ctc-decoder.h, sherpa-onnx/csrc/online-ctc-fst-decoder.cc, sherpa-onnx/csrc/online-recognizer-ctc-impl.h, sherpa-onnx/csrc/online-recognizer.cc, sherpa-onnx/csrc/online-recognizer.h, sherpa-onnx/python/csrc/offline-stream.cc, sherpa-onnx/python/csrc/online-recognizer.cc
Fixes #805
@w11wo 
Could you help test this PR with your phone-based CTC model?
Note that we only return the word IDs. You need to convert the IDs to actual word symbols.
---
```bash
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-zipformer-ctc-en-2023-10-02.tar.bz2
tar xvf sherpa-onnx-zipformer-ctc-en-2023-10-02.tar.bz2
rm sherpa-onnx-zipformer-ctc-en-2023-10-02.tar.bz2
```
```bash
./build/bin/sherpa-onnx-offline \
--model-type=zipformer2_ctc \
--ctc.graph=./sherpa-onnx-zipformer-ctc-en-2023-10-02/HLG.fst \
--zipformer-ctc-model=./sherpa-onnx-zipformer-ctc-en-2023-10-02/model.int8.onnx \
--tokens=./sherpa-onnx-zipformer-ctc-en-2023-10-02/tokens.txt \
./sherpa-onnx-zipformer-ctc-en-2023-10-02/test_wavs/0.wav \ …
```
=> Support getting word IDs for CTC HLG decoding.

.github/scripts/test-python.sh, python-api-examples/inverse-text-normalization-offline-asr.py, sherpa-onnx/csrc/offline-recognizer-ctc-impl.h, sherpa-onnx/csrc/offline-recognizer-impl.cc, sherpa-onnx/csrc/offline-recognizer-impl.h, sherpa-onnx/csrc/offline-recognizer-paraformer-impl.h, sherpa-onnx/csrc/offline-recognizer-transducer-impl.h, sherpa-onnx/csrc/offline-recognizer-transducer-nemo-impl.h, sherpa-onnx/csrc/offline-recognizer-whisper-impl.h, sherpa-onnx/csrc/offline-recognizer.cc, sherpa-onnx/csrc/offline-recognizer.h, sherpa-onnx/python/csrc/offline-recognizer.cc, sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
```
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-paraformer-zh-2023-03-28.tar.bz2
tar xvf sherpa-onnx-paraformer-zh-2023-03-28.tar.bz2
rm sherpa-onnx-paraformer-zh-2023-03-28.tar.bz2
```
```
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/itn_zh_number.fst
```
Please refer to
https://github.com/k2-fsa/colab/blob/master/sherpa-onnx/itn_zh_number.ipynb
for how `itn_zh_number.fst `is generated.
```
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/itn-zh-number.wav
```
```
python3 ./python-api-examples/inverse-text-normalization-offline-asr.py
```
The output is given below:
```
/Users/fangjun/open-source/sherpa-onnx/sherpa-onnx/csrc/offline-recognizer-impl.cc:ApplyInverseTextNormalization:428 After inverse …
```
=> Add inverse text normalization for non-streaming ASR

.github/workflows/linux-jni.yaml
Some users are building sherpa-onnx for jni on computer A and run it on computer B. However, computer B has an old version of glibc and throws errors like below:
```
libsherpa-onnx-jni.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found
```
This PR tries to fix that by providing a pre-built jni lib compiled on CentOS 7.
=> Publish pre-compiled libs for jni (linux x64)

.github/scripts/test-swift.sh, swift-api-examples/.gitignore, swift-api-examples/SherpaOnnx.swift, swift-api-examples/keyword-spotting-from-file.swift, swift-api-examples/run-keyword-spotting-from-file.sh
=> Swift API for keyword spotting.

.github/workflows/build-wheels-aarch64.yaml, .github/workflows/build-wheels-linux.yaml, .github/workflows/linux-jni.yaml, .github/workflows/linux.yaml, build-aarch64-linux-gnu.sh, build-arm-linux-gnueabihf.sh, build-riscv64-linux-gnu.sh
To fix the following error
https://github.com/k2-fsa/sherpa-onnx/actions/runs/9624761090/job/26548907449#step:3:741
```
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: seq/.libs/libseq.a(seqmid.o): in function `update_group_ports':
/project/alsa-lib/src/seq/seqmid.c:672: undefined reference to `strlcat'
/opt/rh/devtoolset-10/root/usr/libexec/gcc/x86_64-redhat-linux/10/ld: /project/alsa-lib/src/seq/seqmid.c:673: undefined reference to `strlcat'
collect2: error: ld returned 1 exit status
```
=> Fix the alsa-lib version to v1.2.12

cmake/onnxruntime.cmake
There is an issue with the directory, ${location_onnxruntime_header_dir} may be NOT-FOUND
=> Resolve issues with using pre-installed onnxruntime

sherpa-onnx/c-api/c-api.cc
Due to the following lines
https://github.com/k2-fsa/sherpa-onnx/blob/dfca4500aa713cdc9ba1d83fc16f579584c4e8a5/sherpa-onnx/csrc/offline-recognizer-ctc-impl.h#L41-L43
`tokens.size()` is not necessarily equal to `timestamp.size()`.
It causes the following errors without this PR.
https://github.com/k2-fsa/sherpa-onnx/actions/runs/9665724491/job/26663537339#step:15:391
```
free(): invalid next size (fast)
SIGABRT: abort
PC=0x7f8c488969fc m=0 sigcode=18446744073709551610
signal arrived during cgo execution
goroutine 1 gp=0xc0000061c0 m=0 mp=0x5a5900 [syscall]:
runtime.cgocall(0x4b51d0, 0xc000123d08)
/opt/hostedtoolcache/go/1.22.4/x64/src/runtime/cgocall.go:157 +0x4b fp=0xc000123ce0 sp=0xc000123ca8 pc=0x4082ab
github.com/k2-fsa/sherpa-onnx-go-linux._Cfunc_DestroyOfflineRecognizer(0x21bea00) …
```
=> Fix possible segfault in C API.

CMakeLists.txt, dotnet-examples/offline-decode-files/Program.cs, dotnet-examples/offline-tts/Program.cs, dotnet-examples/online-decode-files/Program.cs, scripts/dotnet/OfflineRecognizer.cs, scripts/dotnet/OnlineRecognizer.cs, scripts/dotnet/OnlineRecognizerResult.cs, scripts/dotnet/run.sh, scripts/dotnet/sherpa-onnx.csproj.in, scripts/dotnet/sherpa-onnx.csproj.runtime.in, sherpa-onnx/kotlin-api/OfflineRecognizer.kt
Also, fixes build warnings of .Net examples.
=> Support .Net framework 2.0

CMakeLists.txt, nodejs-addon-examples/package.json, sherpa-onnx/csrc/silero-vad-model.cc, sherpa-onnx/csrc/silero-vad-model.h, sherpa-onnx/csrc/vad-model.h, sherpa-onnx/csrc/voice-activity-detector.cc
The PR
https://github.com/snakers4/silero-vad/pull/468
releases a new version of silero vad, i.e., version 5, which has a different programming interface from version 4.
This PR supports silero VAD v5. It is also compatible with silero VAD v4.
```bash
cd sherpa-onnx
mkdir build
cd build
cmake ..
make
wget https://github.com/snakers4/silero-vad/raw/master/files/silero_vad.onnx
./bin/sherpa-onnx-vad-microphone --silero-vad-model=./silero_vad.onnx
```
For APIs of other languages, e.g., python, please see
https://github.com/k2-fsa/sherpa-onnx/tree/master/python-api-examples
=> Support silero_vad version 5

sherpa-onnx/csrc/silero-vad-model.cc, sherpa-onnx/csrc/silero-vad-model.h, sherpa-onnx/csrc/voice-activity-detector.cc
The network input is 64 + 512 samples instead of 512 samples for 16kHz.
=> Fix for silero vad v5.

.github/workflows/build-wheels-macos-arm64.yaml, .github/workflows/build-wheels-macos-x64.yaml, .github/workflows/npm-addon-macos.yaml, .github/workflows/run-python-test-macos.yaml, .github/workflows/test-build-wheel.yaml, .github/workflows/test-pip-install.yaml
Tests using `macos-11` wait a long time before they can start, so we replace `macos-11` with `macos-13`.
=> replace macos-11 with macos-13 for GitHub actions

sherpa-onnx/csrc/provider-config.cc, sherpa-onnx/csrc/provider-config.h, sherpa-onnx/python/csrc/tensorrt-config.cc
trt_workspace range can be extended further with this,
and will not be limited to just 2GB default value
=> updating trt workspace int64

.github/scripts/test-dot-net.sh, .github/scripts/test-offline-transducer.sh, .github/scripts/test-online-transducer.sh, .github/scripts/test-python.sh, CHANGELOG.md, CMakeLists.txt, dotnet-examples/keyword-spotting-from-files/Program.cs, dotnet-examples/keyword-spotting-from-files/keyword-spotting-from-files.csproj, dotnet-examples/keyword-spotting-from-files/run.sh, dotnet-examples/online-decode-files/run-transducer-itn.sh, dotnet-examples/online-decode-files/run-transducer.sh, dotnet-examples/sherpa-onnx.sln, dotnet-examples/speech-recognition-from-microphone/run-transducer.sh, flutter/sherpa_onnx/example/example.md, scripts/dotnet/.gitignore, scripts/dotnet/KeywordResult.cs, scripts/dotnet/KeywordSpotter.cs, scripts/dotnet/KeywordSpotterConfig.cs, scripts/dotnet/run.sh, sherpa-onnx/python/tests/test_keyword_spotter.py, sherpa-onnx/python/tests/test_offline_recognizer.py, sherpa-onnx/python/tests/test_online_recognizer.py
=> Add keyword spotting for C#

sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/speaker-embedding-manager.cc, sherpa-onnx/csrc/speaker-embedding-manager.h
Resolve https://github.com/k2-fsa/sherpa-onnx/issues/1096
=> feat: find best embedding matches

.github/workflows/export-whisper-to-onnx.yaml, CHANGELOG.md, CMakeLists.txt, cmake/kaldi-native-fbank.cmake, dart-api-examples/non-streaming-asr/pubspec.yaml, dart-api-examples/streaming-asr/pubspec.yaml, dart-api-examples/tts/pubspec.yaml, dart-api-examples/vad/pubspec.yaml, flutter-examples/streaming_asr/pubspec.yaml, flutter-examples/tts/pubspec.yaml, flutter/sherpa_onnx/pubspec.yaml, flutter/sherpa_onnx_ios/ios/sherpa_onnx_ios.podspec, flutter/sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec, nodejs-addon-examples/package.json, scripts/dart/sherpa-onnx-pubspec.yaml, scripts/whisper/.gitignore, scripts/whisper/export-onnx.py, scripts/whisper/test.py, sherpa-onnx/csrc/offline-recognizer-whisper-impl.h, sherpa-onnx/csrc/offline-stream.cc, sherpa-onnx/csrc/offline-stream.h, sherpa-onnx/csrc/offline-whisper-model.cc, sherpa-onnx/csrc/offline-whisper-model.h
See also #464 
CC @LazycatChaos 
----
You can find exported onnx models at
|model|URL|
|---|---|
|whisper large|https://huggingface.co/csukuangfj/sherpa-onnx-whisper-large|
|whisper large-v1|https://huggingface.co/csukuangfj/sherpa-onnx-whisper-large-v1|
|whisper large-v2|https://huggingface.co/csukuangfj/sherpa-onnx-whisper-large-v2|
|whisper large-v3|https://huggingface.co/csukuangfj/sherpa-onnx-whisper-large-v3|
|distil large-v2|https://huggingface.co/csukuangfj/sherpa-onnx-whisper-distil-large-v2|
You can find a colab notebook
https://colab.research.google.com/drive/1o-ifX1a226EWcJpQDZx7V3B0sTje4Dzm?usp=sharing
showing how to use the exported whisper large v3 with sherpa-onnx.
=> Support whisper large/large-v1/large-v2/large-v3 and distil-large-v2

flutter/publish.md, flutter/sherpa_onnx/lib/src/utils.dart, flutter/sherpa_onnx/pubspec.yaml
To fix the following error while publishing dart packages.
https://github.com/csukuangfj/sherpa-onnx/actions/runs/9910954410/job/27385314444#step:7:70
```
Total compressed archive size: 19 KB.
Validating package...
Package validation found the following potential issue:
* `dart analyze` found the following issue(s):
Analyzing lib, pubspec.yaml...
warning - lib/src/utils.dart:4:8 - Unused import: 'dart:typed_data'. Try removing the import directive. - unused_import
1 issue found.
The server may enforce additional checks.
Package has 1 warning.
```
=> Fix releasing dart packages

sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/offline-recognizer-ctc-impl.h, sherpa-onnx/csrc/offline-recognizer-impl.cc, sherpa-onnx/csrc/offline-recognizer-impl.h, sherpa-onnx/csrc/offline-recognizer-paraformer-impl.h, sherpa-onnx/csrc/offline-recognizer-transducer-impl.h, sherpa-onnx/csrc/offline-recognizer-transducer-nemo-impl.h, sherpa-onnx/csrc/offline-recognizer-whisper-impl.h, sherpa-onnx/csrc/offline-recognizer.cc, sherpa-onnx/csrc/offline-recognizer.h, sherpa-onnx/csrc/offline-stream.h, sherpa-onnx/csrc/offline-whisper-decoder.h, sherpa-onnx/csrc/offline-whisper-greedy-search-decoder.cc, sherpa-onnx/csrc/offline-whisper-greedy-search-decoder.h
Allow modify model config at decode time for ASR.
https://github.com/k2-fsa/sherpa-onnx/issues/1116
Also, exposes the language which was recognized by whisper to the calling client in the SherpaOnnxOfflineRecognizerResult.
=> Allow modify model config at decode time for ASR

sherpa-onnx/csrc/online-zipformer2-transducer-model.cc, sherpa-onnx/csrc/online-zipformer2-transducer-model.h, sherpa-onnx/csrc/session.cc, sherpa-onnx/csrc/session.h
Enabling only encoder model to run in **TRT**,
with decoder and joiner running in **CUDA**
cc : https://github.com/k2-fsa/sherpa-onnx/issues/1098
=> encoder only trt ep for transducer

.github/workflows/build-wheels-aarch64.yaml, .github/workflows/build-wheels-armv7l.yaml, .github/workflows/build-wheels-linux.yaml, .github/workflows/build-wheels-macos-arm64.yaml, .github/workflows/build-wheels-macos-universal2.yaml, .github/workflows/build-wheels-macos-x64.yaml, .github/workflows/build-wheels-win32.yaml, .github/workflows/build-wheels-win64.yaml
pypi.org provides only 10GB of free space for open-source projects.
Each new release of sherpa-onnx occupies about 800MB, so we have to delete previous releases otherwise pypi.org refuses to accept new releases due to limited spaces.
To let users install previous versions, we also publish wheels to huggingface and users can find them at
https://k2-fsa.github.io/sherpa/onnx/cpu.html
and
https://k2-fsa.github.io/sherpa/onnx/cpu-cn.html (for users without access to huggingface.co)
=> publish all pre-built wheels to huggingface

.github/workflows/build-wheels-linux-cuda.yaml, .github/workflows/build-wheels-linux.yaml, .github/workflows/build-wheels-win64-cuda.yaml, setup.py
You can find them at
https://k2-fsa.github.io/sherpa/onnx/cuda.html
Note that only linux x64 and windows x64 are supported.
---
```bash
pip install sherpa-onnx==1.10.16+cuda -f https://k2-fsa.github.io/sherpa/onnx/cuda.html
```
The log is
```
Looking in links: https://k2-fsa.github.io/sherpa/onnx/cuda.html
Collecting sherpa-onnx==1.10.16+cuda
Downloading https://huggingface.co/csukuangfj/sherpa-onnx-wheels/resolve/main/cuda/1.10.16/sherpa_onnx-1.10.16%2Bcuda-cp310-cp310-linux_x86_64.whl (183.3 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.3/183.3 MB 3.8 MB/s eta 0:00:00
Installing collected packages: sherpa-onnx
Successfully installed sherpa-onnx-1.10.16+cuda
```
```python3
import sherpa_onnx
print(sherpa_onnx.__version__)
```
should print
```
1.10.16+cuda
```
=> Provide pre-built wheels with CUDA support.

.github/workflows/export-melo-tts-to-onnx.yaml, .github/workflows/export-sense-voice-to-onnx.yaml, scripts/melo-tts/run.sh, scripts/sense-voice/README.md, scripts/sense-voice/export-onnx.py, scripts/sense-voice/run.sh, scripts/sense-voice/show-info.py
Support exporting models from https://github.com/FunAudioLLM/SenseVoic to onnx
See also
https://huggingface.co/csukuangfj/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tree/main
=> export sense-voice to onnx

.github/scripts/test-nodejs-addon-npm.sh, .gitignore, CHANGELOG.md, CMakeLists.txt, dart-api-examples/keyword-spotter/pubspec.yaml, dart-api-examples/non-streaming-asr/pubspec.yaml, dart-api-examples/streaming-asr/pubspec.yaml, dart-api-examples/tts/pubspec.yaml, dart-api-examples/vad/pubspec.yaml, flutter-examples/streaming_asr/pubspec.yaml, flutter-examples/tts/pubspec.yaml, flutter/sherpa_onnx/pubspec.yaml, flutter/sherpa_onnx_ios/ios/sherpa_onnx_ios.podspec, flutter/sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec, nodejs-addon-examples/README.md, nodejs-addon-examples/package.json, nodejs-addon-examples/test_vad_with_non_streaming_asr_whisper.js, scripts/dart/kws-pubspec.yaml, scripts/dart/sherpa-onnx-pubspec.yaml, scripts/node-addon-api/lib/vad.js, sherpa-onnx/csrc/offline-stream.cc, sherpa-onnx/csrc/online-recognizer.cc
It also fixes the following error
```
undefined:1
{"text": " But whenever I complain, my mother would just give me one of those looks and she'd say, "This is no picnic for me, either, Buster."", "tim
estamps": [], "tokens":[" But", " whenever", " I", " complain", ",", " my", " mother", " would", " just", " give", " me", " one", " of", " those", "
looks", " and", " she", "'d", " say", ",", " "", "This", " is", " no", " picnic", " for", " me", ",", " either", ",", " Buster", ".""], "words": []}
^
SyntaxError: Expected ',' or '}' after property value in JSON at position 100 (line 1 column 101)
at JSON.parse (<anonymous>)
at OfflineRecognizer.getResult (/Users/fangjun/open-source/sherpa-onnx/nodejs-addon-examples/node_modules/sherpa-onnx-node/non-streaming-asr.js:3
4:17)
at Object.<anonymous> …
```
=> Add VAD + Non-streaming ASR example for JavaScript API.

.github/scripts/test-dot-net.sh, .github/workflows/test-dot-net-nuget.yaml, .github/workflows/test-dot-net.yaml, dotnet-examples/offline-decode-files/run-whisper-large-v3.sh, dotnet-examples/offline-decode-files/run-whisper.sh
Since whisper large models use external data, we need to move `.onnx` and `.weights` files to the current directory at runtime.
=> Add test about whisper large-v3 for .Net

flutter-examples/streaming_asr/lib/utils.dart, flutter-examples/tts/lib/utils.dart
If the target file exists but has a different file size, we need to copy the source file to the target file.
=> Fix copying asset files for flutter examples.

sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/online-cnn-bilstm-model-meta-data.h, sherpa-onnx/csrc/online-cnn-bilstm-model.cc, sherpa-onnx/csrc/online-cnn-bilstm-model.h, sherpa-onnx/csrc/online-punctuation-cnn-bilstm-impl.h, sherpa-onnx/csrc/online-punctuation-impl.cc, sherpa-onnx/csrc/online-punctuation-impl.h, sherpa-onnx/csrc/online-punctuation-model-config.cc, sherpa-onnx/csrc/online-punctuation-model-config.h, sherpa-onnx/csrc/online-punctuation.cc, sherpa-onnx/csrc/online-punctuation.h, sherpa-onnx/csrc/session.cc, sherpa-onnx/csrc/session.h, sherpa-onnx/csrc/sherpa-onnx-online-punctuation.cc
For anyone who wants to add punctuation and casing to the raw text output of online ASR.
The quantized model is only 7MB, which is suitable for online ASR on edge devices.
=> Add online punctuation and casing prediction model for English language

scripts/go/sherpa_onnx.go, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h
Added support for the blank_penalty config parameter in the  Go module to match the existing Python implementation.
=> addition of blank_penalty config in online_recognizer

flutter-examples/tts/generate-asset-list.py
To avoid the following case
Users don't need to manually exclude `.DS_Store` files on macOS.
=> Exclude .DS_Store files from flutter tts assets

.github/workflows/c-api.yaml, c-api-examples/CMakeLists.txt, c-api-examples/paraformer-c-api.c, c-api-examples/streaming-paraformer-c-api.c, c-api-examples/streaming-zipformer-c-api.c, c-api-examples/telespeech-c-api.c, c-api-examples/zipformer-c-api.c
C API examples for zipformer, paraformer, and TeleSpeech-ASR CTC models.
=> Add more C API examples

sherpa-onnx/csrc/melo-tts-lexicon.cc
If an English word does not exist in the lexicon, we split it into characters. For instance, if the word TTS does not exist in lexicon.txt, we split it into 3 characters T, T, and S.
=> Fix looking up OOVs in lexicon.txt for MeloTTS models.

flutter/sherpa_onnx/lib/src/offline_recognizer.dart
- add support for language, emotion, and event to OfflineRecognizerResult
- example output:
```
flutter: OfflineRecognizerResult(text: Can you tell me more about this emotion or speech?, tokens: [Can,  you,  tell,  me,  more,  about,  this,  emotion,  or,  speech, ?], timestamps: [2.88, 3.12, 3.3, 3.42, 3.66, 3.9, 4.14, 4.44, 4.86, 5.16, 7.2], lang: <|en|>, emotion: <|SAD|>, event: <|Speech|>)
```
=> flutter: add lang, emotion, event to OfflineRecognizerResult

.github/workflows/lazarus.yaml, lazarus-examples/generate_subtitles/generate_subtitles.lpi, lazarus-examples/generate_subtitles/generate_subtitles.lpr, lazarus-examples/generate_subtitles/my_init.pas, lazarus-examples/generate_subtitles/unit1.pas, sherpa-onnx/csrc/silero-vad-model-config.cc, sherpa-onnx/pascal-api/sherpa_onnx.pas
So that the main thread is not blocked and the user interface is responsive.
=> Use a separate thread to initialize models for lazarus examples.

pascal-api-examples/portaudio-test/.gitignore, pascal-api-examples/portaudio-test/README.md, pascal-api-examples/portaudio-test/run-test-play.sh, pascal-api-examples/portaudio-test/run-test-record.sh, pascal-api-examples/portaudio-test/test-play.pas, pascal-api-examples/portaudio-test/test-record.pas, sherpa-onnx/pascal-api/README.md, sherpa-onnx/pascal-api/portaudio.pas, sherpa-onnx/pascal-api/sherpa_onnx.pas
The recording example can be used for speech recognition while the playing example can be used for text to speech.
The portaudio wrapper for object pascal is copied from
https://github.com/UltraStar-Deluxe/USDX/blob/master/src/lib/portaudio/portaudio.pas
=> Object pascal examples for recording and playing audio with portaudio.

sherpa-onnx/csrc/offline-ctc-model.cc, sherpa-onnx/csrc/offline-transducer-model.cc, sherpa-onnx/csrc/offline-transducer-nemo-model.cc, sherpa-onnx/csrc/offline-tts-vits-model.cc, sherpa-onnx/csrc/online-conformer-transducer-model.cc, sherpa-onnx/csrc/online-lstm-transducer-model.cc, sherpa-onnx/csrc/online-nemo-ctc-model.cc, sherpa-onnx/csrc/online-paraformer-model.cc, sherpa-onnx/csrc/online-recognizer-impl.cc, sherpa-onnx/csrc/online-transducer-model.cc, sherpa-onnx/csrc/online-transducer-nemo-model.cc, sherpa-onnx/csrc/online-wenet-ctc-model.cc, sherpa-onnx/csrc/online-zipformer-transducer-model.cc, sherpa-onnx/csrc/online-zipformer2-ctc-model.cc, sherpa-onnx/csrc/online-zipformer2-transducer-model.cc, sherpa-onnx/csrc/speaker-embedding-extractor-impl.cc, sherpa-onnx/csrc/spoken-language-identification-impl.cc
Change the logging level from WARNING to ERROR.
=> Reduce onnxruntime log output.

sherpa-onnx/jni/wave-reader.cc
I think it's better to throw a error instead of exit to let the developer handle it in the app
=> Throw error instead exit on fail to read wav in java

sherpa-onnx/csrc/hypothesis.h, sherpa-onnx/csrc/online-lm-config.cc, sherpa-onnx/csrc/online-lm-config.h, sherpa-onnx/csrc/online-lm.h, sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-rnn-lm.cc, sherpa-onnx/csrc/online-rnn-lm.h, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.cc, sherpa-onnx/csrc/online-transducer-modified-beam-search-decoder.h, sherpa-onnx/python/csrc/online-lm-config.cc, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
Shallow fusion can be too slow for online cpu inference. Added an option to use classical LM rescore instead.
- Rescore implementation based on https://github.com/k2-fsa/sherpa-onnx/pull/133
- Shallow fusion enabled by default
- Pass _lm-shallow-fusion=false_ to enable rescore instead
- Updated online Python API
CPU runtime comparison for ~1 min wav file using the default _--lm-num-threads=1_
| Method              | Runtime (s) | RTF |
| :---------------- | :------: | :----: |
| No LM | 5.7  | 0.098 |
| Rescore | 40 | 0.68 |
| Shallow Fusion | 69 | 1.2 |
=> Re-implement LM rescore for online transducer

sherpa-onnx/csrc/online-recognizer-transducer-impl.h
In online transducer recognizer during reset() sherpa-onnx preserves the output of the decoder network (decoder_output), but resets model context to sequence of blanks.
```cpp
decoder_->UpdateDecoderOut(&s->GetResult());
Ort::Value decoder_out = std::move(s->GetResult().decoder_out);
auto r = decoder_->GetEmptyResult(); # initialized with empty hyp containing blanks
...
s->SetResult(r);
s->GetResult().decoder_out = std::move(decoder_out);
```
After the reset, at t0 of the new segment the beam-search-decoder reuses decoder_output. 
```cpp
if (t == 0) {
UseCachedDecoderOut(hyps_row_splits, *result, &decoder_out);
}
```
Let's assume it outputs some token Z, because it's the most probable considering cached decoder output (calculated for previous context before reset - "X Y").
Then on step …
=> Preserve previous result as context for next segment

sherpa-onnx/csrc/offline-stream.cc
See also
https://github.com/RicherMans/CED/blob/main/onnx_inference_with_kaldi.py
=> Fix computing features for CED audio tagging models.

python-api-examples/generate-subtitles.py, sherpa-onnx/csrc/silero-vad-model-config.cc, sherpa-onnx/csrc/silero-vad-model-config.h, sherpa-onnx/csrc/voice-activity-detector.cc, sherpa-onnx/python/csrc/silero-vad-model-config.cc
Support for other programming language APIs will be added in a separate pull-request.
This PR handles only the C++ and Python APIs.
Fixes #1136 
CC @chiiyeh
=> Support specifying max speech duration for VAD.

nodejs-addon-examples/package.json, nodejs-addon-examples/test_asr_non_streaming_sense_voice.js, scripts/node-addon-api/src/macros.h
We first convert utf-16 strings to Uint8Array and then we pass the array to C++.
=> Support passing utf-8 strings from JavaScript to C++.

swift-api-examples/generate-subtitles.swift
We need to invoke vad.flush() at the end.
=> Fix swift example for generating subtitles.

.github/workflows/c-api-from-buffer.yaml, c-api-examples/CMakeLists.txt, c-api-examples/keywords-spotter-buffered-tokens-keywords-c-api.c, c-api-examples/streaming-ctc-buffered-tokens-c-api.c, c-api-examples/streaming-ctc-buffered-tokens-hotwords-c-api.c, c-api-examples/streaming-paraformer-buffered-tokens-c-api.c, c-api-examples/streaming-paraformer-buffered-tokens-hotwords-c-api.c, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/keyword-spotter-transducer-impl.h, sherpa-onnx/csrc/keyword-spotter.cc, sherpa-onnx/csrc/keyword-spotter.h, sherpa-onnx/csrc/online-model-config.h, sherpa-onnx/csrc/online-recognizer-ctc-impl.h, sherpa-onnx/csrc/online-recognizer-paraformer-impl.h, sherpa-onnx/csrc/online-recognizer.h
for online paraformer and ctc, their symbol tables are able to be initialized from tokens in a memory buffer
=> allow more online models to load tokens file from the memory

scripts/melo-tts/export-onnx.py
We need to use opset 18 to export the model to onnx.
We have updated the released model to use opset 18.
=> Fix running MeloTTS models on GPU.

.github/workflows/speaker-diarization.yaml, .gitignore, scripts/pyannote/segmentation/README.md, scripts/pyannote/segmentation/speaker-diarization-onnx.py, scripts/pyannote/segmentation/speaker-diarization-torch.py, sherpa-onnx/csrc/fast-clustering.cc
It should be straightforward to port the Python example to C++.
---
CI logs for this PR can be found at
https://github.com/csukuangfj/sherpa-onnx/actions/runs/11200310992/job/31133785096
---
Please refer to
https://github.com/k2-fsa/sherpa-onnx/blob/master/.github/workflows/speaker-diarization.yaml
for usages.
=> Speaker diarization example with onnxruntime Python API

nodejs-addon-examples/README.md, scripts/node-addon-api/lib/addon.js
For example, pnpm will install the `sherpa-onnx-linux-x64` at `node_modules/.pnpm/sherpa-onnx-linux-x64@1.10.27`, so the addon.js can not find `sherpa-onnx.node`.
=> docs(nodejs-addon-examples): add guide for pnpm user

sherpa-onnx/csrc/offline-speaker-diarization-impl.cc, sherpa-onnx/csrc/offline-speaker-diarization-impl.h, sherpa-onnx/csrc/offline-speaker-diarization-pyannote-impl.h, sherpa-onnx/csrc/offline-speaker-diarization.cc, sherpa-onnx/csrc/offline-speaker-diarization.h, sherpa-onnx/csrc/offline-speaker-segmentation-pyannote-model.cc, sherpa-onnx/csrc/offline-speaker-segmentation-pyannote-model.h, sherpa-onnx/csrc/sherpa-onnx-vad-microphone-offline-asr.cc, sherpa-onnx/jni/audio-tagging.cc, sherpa-onnx/jni/keyword-spotter.cc, sherpa-onnx/jni/offline-punctuation.cc, sherpa-onnx/jni/offline-recognizer.cc, sherpa-onnx/jni/offline-speaker-diarization.cc, sherpa-onnx/jni/offline-tts.cc, sherpa-onnx/jni/online-recognizer.cc, sherpa-onnx/jni/speaker-embedding-extractor.cc, sherpa-onnx/jni/spoken-language-identification.cc, sherpa-onnx/jni/voice-activity-detector.cc
Will add Android demo for speaker diarizaiton in a separate pull-request.
=> Android JNI support for speaker diarization

scripts/go/sherpa_onnx.go
It is contributed by a community user from [our QQ group](https://k2-fsa.github.io/sherpa/social-groups.html#qq).
=> Add Go API for offline punctuation models

sherpa-onnx/csrc/offline-whisper-model.cc
在进行 RISCV 运行的 sherpa-onnx 交叉编译的过程中，执行 ./build-riscv64-linux-gnu.sh 脚本的时候出现了
error: 'log10' is not a member of 'std'
在 sherpa-onnx/sherpa-onnx/csrc/offline-whisper-model.cc 文件中导入 <cmath> 库解决
=> fix "log10" compile error by import CMATH lib

cxx-api-examples/sense-voice-cxx-api.cc, cxx-api-examples/streaming-zipformer-cxx-api.cc, cxx-api-examples/whisper-cxx-api.cc, scripts/check_style_cpplint.sh, sherpa-onnx/csrc/offline-speaker-diarization-pyannote-impl.h, sherpa-onnx/csrc/speaker-embedding-extractor-nemo-impl.h
It should fix https://github.com/thewh1teagle/sherpa-rs/issues/33
CC @WilliamVenner
=> Handle NaN embeddings in speaker diarization.

scripts/node-addon-api/src/non-streaming-speaker-diarization.cc
To fix the following errors on Windows x86:
https://github.com/csukuangfj/sherpa-onnx/actions/runs/11514071976/job/32051958194#step:9:140
```
1>Checking Build System
Building Custom Rule D:/a/sherpa-onnx/sherpa-onnx/scripts/node-addon-api/CMakeLists.txt
audio-tagging.cc
keyword-spotting.cc
non-streaming-asr.cc
non-streaming-speaker-diarization.cc
D:\a\sherpa-onnx\sherpa-onnx\scripts\node-addon-api\src\non-streaming-speaker-diarization.cc(245,10): error C2666: 'Napi::Object::operator []': 3 overloads have similar conversions [D:\a\sherpa-onnx\sherpa-onnx\scripts\node-addon-api\build\sherpa-onnx.vcxproj]
D:\a\sherpa-onnx\sherpa-onnx\scripts\node-addon-api\node_modules\node-addon-api\napi-inl.h(942,22): message : could be 'Napi::Value Napi::Object::operator [](uint32_t) const' …
```
=> Fix building node-addon for Windows x86.

.github/workflows/c-api.yaml, .github/workflows/cxx-api.yaml, c-api-examples/CMakeLists.txt, c-api-examples/moonshine-c-api.c, c-api-examples/vad-moonshine-c-api.c, c-api-examples/vad-whisper-c-api.c, cxx-api-examples/CMakeLists.txt, cxx-api-examples/moonshine-cxx-api.cc, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/c-api/cxx-api.cc, sherpa-onnx/c-api/cxx-api.h
@thewh1teagle  Could you support it in [sherpa-rs](https://github.com/thewh1teagle/sherpa-rs)?
=> Add C and C++ API for Moonshine models

.github/workflows/export-melo-tts-to-onnx.yaml, scripts/melo-tts/README.md, scripts/melo-tts/export-onnx-en.py, scripts/melo-tts/run.sh, sherpa-onnx/csrc/macros.h, sherpa-onnx/csrc/melo-tts-lexicon.cc, sherpa-onnx/csrc/melo-tts-lexicon.h, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts-vits-model.cc, sherpa-onnx/csrc/onnx-utils.cc
Usage:
```bash
build/bin/sherpa-onnx-offline-tts \
--vits-model=./vits-melo-tts-en/model.onnx \
--vits-lexicon=./vits-melo-tts-en/lexicon.txt \
--vits-tokens=./vits-melo-tts-en/tokens.txt \
--sid=3 --output-filename=./s3.wav \
'how are you doing'
```
You can download the model from
https://github.com/k2-fsa/sherpa-onnx/releases/tag/tts-models
E.g.,
https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/vits-melo-tts-en.tar.bz2
=> Export the English TTS model from MeloTTS

c-api-examples/vad-sense-voice-c-api.c
The current code uses a repeated while loop code (two sections of while) to process the tail data.
```c
while(..) {
}
while(..) {
}
```
And the optimized early calculation of total_size can circulate less each calculation amount and improve efficiency.
So I reduce sherpa-onnx/c-api-examples/vad-sense-voice-c-api.c some codes.
=> Reduce vad-sense-voice example code.

.github/workflows/build-xcframework.yaml, build-ios-shared.sh, sherpa-onnx/csrc/CMakeLists.txt
=> Fixes #1512

cmake/onnxruntime.cmake
fix #1545 
- 自定 onnxruntime 时 windows 的链接库名称不正确。
- 缺少 IMPORTED_IMPLIB 属性，导致编译报错 onnxruntime-NOTFOUND.obj 
Windows 操作系统使用如下命令测试通过
```
set SHERPA_ONNXRUNTIME_INCLUDE_DIR=XXXXX
set SHERPA_ONNXRUNTIME_LIB_DIR=XXXX
cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 17 2022" ^
-DSHERPA_ONNX_ENABLE_PORTAUDIO=OFF ^
-DSHERPA_ONNX_ENABLE_WEBSOCKET=OFF ^
-DBUILD_SHARED_LIBS=ON ^
-DSHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE=ON ^
-DSHERPA_ONNX_BUILD_C_API_EXAMPLES=OFF 
```
=> fix windows build

.github/workflows/release-dart-package.yaml, CHANGELOG.md, CMakeLists.txt, build-ios-shared.sh, dart-api-examples/add-punctuations/pubspec.yaml, dart-api-examples/audio-tagging/pubspec.yaml, dart-api-examples/keyword-spotter/pubspec.yaml, dart-api-examples/non-streaming-asr/pubspec.yaml, dart-api-examples/speaker-diarization/pubspec.yaml, dart-api-examples/speaker-identification/pubspec.yaml, dart-api-examples/streaming-asr/pubspec.yaml, dart-api-examples/tts/pubspec.yaml, dart-api-examples/vad-with-non-streaming-asr/pubspec.yaml, dart-api-examples/vad/pubspec.yaml, flutter-examples/README.md, flutter-examples/streaming_asr/pubspec.yaml, flutter-examples/tts/lib/model.dart, flutter-examples/tts/pubspec.yaml, flutter/sherpa_onnx/lib/sherpa_onnx.dart, flutter/sherpa_onnx/pubspec.yaml, flutter/sherpa_onnx_ios/ios/sherpa_onnx_ios.podspec, flutter/sherpa_onnx_macos/macos/sherpa_onnx_macos.podspec, new-release.sh, nodejs-addon-examples/package.json
Fixes #1172 
Screenshot of running `./build-ios-shared.sh`
You can see that the xcframework contains pre-built libs for both iOS (arm64) and iOS simulators (arm64 + x86_64)
=> Use xcframework for Flutter iOS plugin. 

.github/workflows/aarch64-linux-gnu-shared.yaml, .github/workflows/aarch64-linux-gnu-static.yaml, .github/workflows/arm-linux-gnueabihf.yaml, CMakeLists.txt, build-aarch64-linux-gnu.sh, cmake/onnxruntime-linux-aarch64-gpu.cmake
The pre-built onnxruntime libs are provided by the community using the following command:
```bash
./build.sh --build_shared_lib --config Release --update \
--build --parallel --use_cuda \
--cuda_home /usr/local/cuda \
--cudnn_home /usr/lib/aarch64-linux-gnu 2>&1 | tee my-log.txt
```
See also https://github.com/microsoft/onnxruntime/discussions/11226
---
info about the board:
```
Model: NVIDIA Orin NX T801-16GB - Jetpack 5.1.4 [L4T 35.6.0]
```
```
nvidia@nvidia-desktop:~/Downloads$ head -n 1 /etc/nv_tegra_release
nvidia@nvidia-desktop:~/Downloads$ uname -r
5.10.216-tegra
nvidia@nvidia-desktop:~/Downloads$ lsb_release -i -r
Distributor ID:	Ubuntu
Release:	20.04
nvidia@nvidia-desktop:~/Downloads$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built …
```
=> Support using onnxruntime 1.16.0 with CUDA 11.4 on Jetson Orin NX (Linux arm64 GPU).

.github/workflows/android.yaml
Resolve https://github.com/k2-fsa/sherpa-onnx/issues/1634
=> feat: enable c api for android ci

android/SherpaOnnxVadAsr/app/src/main/java/com/k2fsa/sherpa/onnx/MainActivity.kt
This change ensures that the main audio processing loop is not blocked by long-running operations in `runSecondPass`, improving responsiveness and reducing the risk of missing parts of input speech.
=> SherpaOnnxVadAsr: Offload runSecondPass to background thread for improved real-time audio processing

sherpa-onnx/python/csrc/offline-tts-model-config.cc
Allow setting `vits` and `matcha` separately.
=> Fix initializing TTS in Python.

sherpa-onnx/csrc/jieba-lexicon.cc
A space means a pause. Removing spaces after punctuations reduces extra pauses.
=> Remove spaces after punctuations for TTS

flutter/sherpa_onnx/lib/src/audio_tagging.dart, flutter/sherpa_onnx/lib/src/keyword_spotter.dart, flutter/sherpa_onnx/lib/src/offline_recognizer.dart, flutter/sherpa_onnx/lib/src/offline_speaker_diarization.dart, flutter/sherpa_onnx/lib/src/online_recognizer.dart, flutter/sherpa_onnx/lib/src/punctuation.dart, flutter/sherpa_onnx/lib/src/speaker_identification.dart, flutter/sherpa_onnx/lib/src/tts.dart, flutter/sherpa_onnx/lib/src/vad.dart
参见 #1660 ，此 PR 将所有的 Flutter lib 内的包含 factory 构造函数的类，增加了 fromPtr() 构造函数，从而允许跨 Isolate 进行构造、传递相关类。
=> Add constructor fromPtr() for all flutter class with factory ctor.

.github/scripts/test-offline-tts.sh, .github/scripts/test-python.sh, python-api-examples/offline-tts-play.py, python-api-examples/offline-tts.py, sherpa-onnx/csrc/macros.h, sherpa-onnx/csrc/offline-tts-matcha-impl.h, sherpa-onnx/csrc/offline-tts-matcha-model-metadata.h, sherpa-onnx/csrc/offline-tts-matcha-model.cc, sherpa-onnx/csrc/piper-phonemize-lexicon.cc, sherpa-onnx/csrc/piper-phonemize-lexicon.h
```bash
curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/matcha-icefall-en_US-ljspeech.tar.bz2
tar xvf matcha-icefall-en_US-ljspeech.tar.bz2
rm matcha-icefall-en_US-ljspeech.tar.bz2
curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/vocoder-models/hifigan_v2.onnx
./build/bin/sherpa-onnx-offline-tts \
--matcha-acoustic-model=./matcha-icefall-en_US-ljspeech/model-steps-3.onnx \
--matcha-vocoder=./hifigan_v2.onnx \
--matcha-tokens=./matcha-icefall-en_US-ljspeech/tokens.txt \
--matcha-data-dir=./matcha-icefall-en_US-ljspeech/espeak-ng-data \
--num-threads=2 \
--output-filename=./matcha-ljspeech-1.wav \
--debug=1 \
"Today as always, men fall into two groups: slaves and free men. Whoever does not have two-thirds of his day for himself, is a slave, …
```
=> Support Matcha-TTS models using espeak-ng

scripts/sense-voice/export-onnx.py
由于[SenseVoiceSmall.from_pretrained()](https://github.com/FunAudioLLM/SenseVoice/blob/5780ace4ea4a1b3e72f21d1632aa5ced23176dca/model.py#L651)
调用的[funasr.auto.auto_model.AutoModel.build_model()](https://github.com/modelscope/FunASR/blob/d4f13c2e444f972b272273bce76b05f52f5164aa/funasr/auto/auto_model.py#L182)默认device是cuda
(在cuda available的环境中)
```python
device = kwargs.get("device", "cuda")
if not torch.cuda.is_available() or kwargs.get("ngpu", 1) == 0:
device = "cpu"
kwargs["batch_size"] = 1
kwargs["device"] = device
```
而export-onnx.py里的tensor默认都是cpu, 导致
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu
所以直接在加载model的时候指定cpu
=> Fix: export-onnx.py(expected all tensors to be on the same device)

.github/workflows/export-kokoro.yaml, scripts/kokoro/.gitignore, scripts/kokoro/README.md, scripts/kokoro/add-meta-data.py, scripts/kokoro/run.sh, scripts/kokoro/test.py, scripts/melo-tts/export-onnx.py
CC @thewh1teagle  @giannik 
Even though [kokoro](https://huggingface.co/hexgrad/Kokoro-82M) TTS claims it has only about 82M parameters, 
it is by far the **LARGEST** model we have in sherpa-onnx. 
It is also the **SLOWEST** TTS model on CPU in sherpa-onnx
---
For the model `kokoro-v0_19.onnx`, it throws the following error for onnxruntime 1.16.3
```
File "/home/runner/work/sherpa-onnx/sherpa-onnx/scripts/kokoro/./test.py", line 60, in show
sess = ort.InferenceSession(filename, session_opts)
File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
self._create_inference_session(providers, provider_options, disabled_optimizers)
File "/opt/hostedtoolcache/Python/3.10.16/x64/lib/python3.10/site-pack …
```
=> Export kokoro to sherpa-onnx

.github/scripts/test-offline-tts.sh, .github/scripts/test-python.sh, python-api-examples/offline-tts-play.py, python-api-examples/offline-tts.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/melo-tts-lexicon.h, sherpa-onnx/csrc/offline-tts-character-frontend.h, sherpa-onnx/csrc/offline-tts-impl.cc, sherpa-onnx/csrc/offline-tts-kokoro-impl.h, sherpa-onnx/csrc/offline-tts-kokoro-model-config.cc, sherpa-onnx/csrc/offline-tts-kokoro-model-config.h, sherpa-onnx/csrc/offline-tts-kokoro-model-meta-data.h, sherpa-onnx/csrc/offline-tts-kokoro-model.cc, sherpa-onnx/csrc/offline-tts-kokoro-model.h, sherpa-onnx/csrc/offline-tts-matcha-model-meta-data.h, sherpa-onnx/csrc/offline-tts-matcha-model.h, sherpa-onnx/csrc/offline-tts-model-config.cc, sherpa-onnx/csrc/offline-tts-model-config.h, sherpa-onnx/csrc/offline-tts-vits-model-meta-data.h, sherpa-onnx/csrc/offline-tts-vits-model.h, sherpa-onnx/csrc/piper-phonemize-lexicon.cc, sherpa-onnx/csrc/piper-phonemize-lexicon.h, sherpa-onnx/python/csrc/CMakeLists.txt, sherpa-onnx/python/csrc/offline-tts-kokoro-model-config.cc, sherpa-onnx/python/csrc/offline-tts-kokoro-model-config.h, sherpa-onnx/python/csrc/offline-tts-model-config.cc, sherpa-onnx/python/sherpa_onnx/__init__.py
| 0 af | 1 af_bella | 2 af_nicole|
|---|---|---|
|https://github.com/user-attachments/assets/6d0c0cb4-6b5b-48f4-a9e4-1eaaab86327a|https://github.com/user-attachments/assets/70596402-a74f-4775-abcb-1f2b4fcaba60|https://github.com/user-attachments/assets/c76cf8fc-efa7-4f03-b356-7e1759eebea8|
|3 af_sarah | 4 af_sky| 5 am_adam|
|---|---|---|
|https://github.com/user-attachments/assets/3f160a11-05c4-47ed-b356-7a160e836ecc|https://github.com/user-attachments/assets/1443e0a0-1c92-4ac2-9e5d-56c0a0dbf4af|https://github.com/user-attachments/assets/153abc1a-421d-4e08-b62b-9fcb401fbfec|
|6 am_michael| 7 bf_emma| 8 bf_isabella|
|---|---|---|
|https://github.com/user-attachments/assets/6372c7d5-a2d5-4b8c-9e56-7f9957f592cc|https://github.com/user-attachments/assets/6e9ccccd-de74-43e4-8594-f44121277d7a|ht …
=> Add C++ and Python API for Kokoro TTS models.

android/SherpaOnnxTtsEngine/app/src/main/java/com/k2fsa/sherpa/onnx/tts/engine/MainActivity.kt
Set max number of lines of the input text field so that the buttons are still visible when the input text is long.
=> Fix UI for Android TTS Engine.

ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/ViewModel.swift
```
mkdir -p ~/open-source/
cd ~/open-source
cd sherpa-onnx
./build-ios.sh
```
Note that you can put `sherpa-onnx` anywhere you like. We use `~/open-source` as an example
Please refer to
https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/matcha.html#matcha-icefall-zh-baker-chinese-1-female-speaker
to download models.
```bash
mkdir -p ~/open-source/icefall-models
cd ~/open-source/icefall-models
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/matcha-icefall-zh-baker.tar.bz2
tar xvf matcha-icefall-zh-baker.tar.bz2
rm matcha-icefall-zh-baker.tar.bz2
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/vocoder-models/hifigan_v2.onnx
```
Note that you can put  model files anywhere you like. We use …
=> Add iOS TTS example for MatchaTTS

ios-swiftui/SherpaOnnxTts/SherpaOnnxTts/ViewModel.swift
```bash
mkdir -p ~/open-source/
cd ~/open-source
cd sherpa-onnx
./build-ios.sh
```
Please refer to
https://k2-fsa.github.io/sherpa/onnx/tts/pretrained_models/kokoro.html#kokoro-en-v0-19-english-11-speakers
to download models.
```bash
mkdir -p ~/open-source/icefall-models
cd ~/open-source/icefall-models
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/kokoro-en-v0_19.tar.bz2
tar xf kokoro-en-v0_19.tar.bz2
rm kokoro-en-v0_19.tar.bz2
```
Note that you can put model files anywhere you like. We use `~/open-source/icefall-models` as an example
Start xcode and open the project
https://github.com/k2-fsa/sherpa-onnx/tree/master/ios-swiftui/SherpaOnnxTts
----
The version of xcode I am using is
=> Add iOS example for Kokoro TTS

sherpa-onnx/python/csrc/features.cc
This PR fixes the incorrect binding of the dither attribute in the FeatureExtractorConfig Pybind11 bindings. Previously, dither was mistakenly bound to the high_freq member variable, causing unexpected behavior where changes to one attribute affected the other.
The fix updates the Pybind11 binding to correctly map dither to its own member variable, ensuring that dither and high_freq are independent properties in Python
=> Fix `dither` binding in Pybind11 to ensure independence from `high_freq` in `FeatureExtractorConfig`

c-api-examples/vad-moonshine-c-api.c
Reduce vad-moonshine-c-api example code.
The current code uses a repeated while loop code (two sections of while) to process the tail data.
```cpp
while(..) {
}
while(..) {
}
```
And the optimized early calculation of total_size can circulate less each calculation amount and improve efficiency.
So I reduce sherpa-onnx/c-api-examples/vad-moonshine-c-api.c some codes.
The PR like this: https://github.com/k2-fsa/sherpa-onnx/pull/1510
The screenshot is test results after modification in my pc.
=> Reduce vad-moonshine-c-api example code.

.github/workflows/build-wheels-aarch64.yaml, .github/workflows/build-wheels-armv7l.yaml, .github/workflows/build-wheels-linux-cuda.yaml, .github/workflows/build-wheels-linux.yaml, .github/workflows/build-wheels-macos-arm64.yaml, .github/workflows/build-wheels-macos-universal2.yaml, .github/workflows/build-wheels-macos-x64.yaml, .github/workflows/build-wheels-win32.yaml, .github/workflows/build-wheels-win64.yaml
To fix the following error
```
Uploading distributions to https://upload.pypi.org/legacy/
ERROR    InvalidDistribution: Invalid distribution metadata: dynamic introduced
in metadata version 2.2, not 2.1 
```
=> Fix publishing wheels

sherpa-onnx/csrc/piper-phonemize-lexicon.cc
Addressed issue Skipping words #1777
In the original code they have a 0 in front and behind. Currently it only has it behind so I added it to the front also. Here is the original code:
https://huggingface.co/hexgrad/kLegacy/blob/d0acca3b0748cae52e0a14a28ad03515002ff22f/v0.19/kokoro.py#L117
=> Fix: Prepend 0 to tokenization to prevent word skipping for Kokoro.

.github/workflows/export-kokoro.yaml, .gitignore, scripts/kokoro/add_meta_data.py, scripts/kokoro/run.sh, scripts/kokoro/v1.0/.gitignore, scripts/kokoro/v1.0/README.md, scripts/kokoro/v1.0/add_meta_data.py, scripts/kokoro/v1.0/generate_lexicon.py, scripts/kokoro/v1.0/generate_tokens.py, scripts/kokoro/v1.0/generate_voices_bin.py, scripts/kokoro/v1.0/run.sh, scripts/kokoro/v1.0/test.py
Need to add C++ code to support it.
=> Export Kokoro 1.0 to sherpa-onnx

harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/ets/components/NonStreamingTts.ets, harmony-os/SherpaOnnxTts/entry/src/main/ets/workers/NonStreamingTtsWorker.ets
It throws the following error since HarmonyOS in sherpa-onnx uses onnxruntime 1.16.3.
```
LastFatalMessage:terminating due to uncaught exception of type Ort::Exception: 
Failed to load model with error: /home/runner/work/onnxruntime-libs/onnxruntime-libs/onnxruntime/onnxruntime/core/graph/model_load_utils.h:56 
void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::string, int> &, const logging::Logger &, bool, const std::string &, int) 
ONNX Runtime only *guarantees* support for models stamped with 
official released onnx opset versions. Opset 20 is under development
and support for this is limited. The operator schemas and or other functionality 
may change before next ONNX release and in this case ONNX Runtime 
will not guarantee backward …
```
=> Add HarmonyOS demo for Kokoro TTS 1.0

sherpa-onnx/csrc/offline-tts.cc, sherpa-onnx/csrc/text-utils.cc, sherpa-onnx/csrc/text-utils.h
Chinese users usually have the strings encoded in GB2312 on Windows, not in UTF8. 
This PR converts GB2312 encoded strings to UTF8 encoding.
=> Fix passing gb2312 encoded strings to tts on Windows

c-api-examples/keywords-spotter-buffered-tokens-keywords-c-api.c, flutter/sherpa_onnx/lib/src/sherpa_onnx_bindings.dart, flutter/sherpa_onnx/lib/src/tts.dart, harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/cpp/non-streaming-tts.cc, harmony-os/SherpaOnnxHar/sherpa_onnx/src/main/ets/components/NonStreamingTts.ets, scripts/dotnet/OfflineTtsConfig.cs, scripts/go/sherpa_onnx.go, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/c-api/cxx-api.cc, sherpa-onnx/c-api/cxx-api.h, sherpa-onnx/csrc/offline-tts-kokoro-impl.h, sherpa-onnx/csrc/offline-tts-matcha-impl.h, sherpa-onnx/csrc/offline-tts-vits-impl.h, sherpa-onnx/csrc/offline-tts.cc, sherpa-onnx/csrc/offline-tts.h, sherpa-onnx/java-api/src/com/k2fsa/sherpa/onnx/OfflineTtsConfig.java, sherpa-onnx/jni/offline-tts.cc, sherpa-onnx/kotlin-api/Tts.kt, sherpa-onnx/pascal-api/sherpa_onnx.pas, sherpa-onnx/python/csrc/offline-tts.cc, swift-api-examples/SherpaOnnx.swift, wasm/tts/sherpa-onnx-tts.js, wasm/tts/sherpa-onnx-wasm-main-tts.cc
You can set the parameter `length_scale` to control the scale.
=> Support scaling the duration of a pause in TTS.

.github/workflows/build-wheels-aarch64-cuda.yaml, .github/workflows/build-wheels-aarch64.yaml, build-aarch64-linux-gnu.sh
After removing qemu and using the ubuntu 22.04 ARM virtual machine, the build time is reduced from 2 hours 20 minutes to 15 minutes, which is about 9x faster.
=> Fix building wheels for linux aarch64.

.github/scripts/test-offline-tts.sh, scripts/apk/generate-tts-apk-script.py, sherpa-onnx/csrc/offline-tts-matcha-impl.h, sherpa-onnx/csrc/offline-tts-matcha-model-meta-data.h, sherpa-onnx/csrc/offline-tts-matcha-model.cc
Fixes #1779 
See pre-built APKs at 
https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html
CC @mah92
---
```bash
curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/matcha-tts-fa_en-male.tar.bz2
tar xvf matcha-tts-fa_en-male.tar.bz2
rm matcha-tts-fa_en-male.tar.bz2
curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/vocoder-models/hifigan_v2.onnx
build/bin/sherpa-onnx-offline-tts \
--matcha-acoustic-model=./matcha-tts-fa_en-male/model.onnx \
--matcha-vocoder=./hifigan_v2.onnx \
--matcha-tokens=./matcha-tts-fa_en-male/tokens.txt \
--matcha-data-dir=./matcha-tts-fa_en-male/espeak-ng-data \
--output-filename=./tts/test-matcha-fa-en-male.wav \
--num-threads=2 \
"How are you doing today? این یک نمونه ی تست فارسی است. This is a test."
```
=> Add C++ support for MatchaTTS models not from icefall.

sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/c-api/cxx-api.cc, sherpa-onnx/c-api/cxx-api.h
Add the hotwords parameter when creating a stream to the offline recognizer in the C and C++ APIs.
=> OfflineRecognizer supports create stream with hotwords

.github/workflows/export-peng-cheng-starling.yaml, scripts/matcha-tts/README.md, scripts/peng-cheng-starling/.gitignore, scripts/peng-cheng-starling/README.md, scripts/peng-cheng-starling/quantize_models.py, scripts/peng-cheng-starling/run.sh, sherpa-onnx/csrc/offline-tts.h
The model is from https://github.com/yangb05/PengChengStarling
Note that it is a streaming zipformer (v2) and supports the following 8 languages.
- English
- Chinese
- Japanese
- Russian
- Thai
- Indonesian
- Arabic
- Vietnamese
You can download the model from
[sherpa-onnx-streaming-zipformer-ar_en_id_ja_ru_th_vi_zh-2025-02-10.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-streaming-zipformer-ar_en_id_ja_ru_th_vi_zh-2025-02-10.tar.bz2)
```
total 324M
-rw-r--r-- 1 runner docker  105 Feb 10 09:51 README.md
-rw-r--r-- 1 runner docker 465K Feb 10 09:51 bpe.model
-rw-r--r-- 1 runner docker  33M Feb 10 09:49 decoder-epoch-75-avg-11-chunk-16-left-128.onnx
-rw-r--r-- 1 runner docker 283M Feb 10 …
```
=> Add PengChengStarling models to sherpa-onnx

sherpa-onnx/csrc/kokoro-multi-lang-lexicon.cc, sherpa-onnx/csrc/offline-tts-kokoro-impl.h, sherpa-onnx/csrc/offline-tts-kokoro-model-meta-data.h, sherpa-onnx/csrc/offline-tts-kokoro-model.cc
If you use German, please avoid `äöüßÄÖÜ` in your text.
We will fix it later so that it supports `äöüßÄÖÜ` in the text.
=> Support specifying voice in espeak-ng for kokoro tts models.

sherpa-onnx/csrc/kokoro-multi-lang-lexicon.cc
Currently, during normal use you may get a lot of print statements such as: `Use espeak-ng to handle the OOV: 'ipsum'` which may not be relevant unless you are debugging.
=> Fix: made print sherpa_onnx_loge when it is in debug mode

sherpa-onnx/c-api/cxx-api.cc, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/kokoro-multi-lang-lexicon.cc, sherpa-onnx/csrc/regex-lang-test.cc, sherpa-onnx/csrc/text-utils-test.cc, sherpa-onnx/csrc/text-utils.cc, sherpa-onnx/csrc/text-utils.h
It separates only Chinese and non-Chinese text for now.
=> Fix spliting text by languages for kokoro tts.

.github/workflows/export-fire-red-asr.yaml, .github/workflows/mfc.yaml
See also https://github.com/FireRedTeam/FireRedASR
and
https://huggingface.co/FireRedTeam/FireRedASR-AED-L/tree/main
Note it supports both Chinese and English.
The **Large** version is quite large. See the exported onnx model files below:
```
total 1.7G
-rw-r--r-- 1 runner docker  188 Feb 16 08:46 README.md
-rw-r--r-- 1 runner docker 425M Feb 16 08:45 decoder.int8.onnx
-rw-r--r-- 1 runner docker 1.3G Feb 16 08:46 encoder.int8.onnx
drwxr-xr-x 2 runner docker 4.0K Feb 16 08:45 test_wavs
-rw-r--r-- 1 runner docker  70K Feb 16 08:46 tokens.txt
```
You can download it from
We will open-source the export code once the `xs` version of the model from
https://github.com/FireRedTeam/FireRedASR
is open-sourced.
=> Export FireRedASR to ONNX

.gitignore, python-api-examples/offline-fire-red-asr-decode-files.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/offline-fire-red-asr-decoder.h, sherpa-onnx/csrc/offline-fire-red-asr-greedy-search-decoder.cc, sherpa-onnx/csrc/offline-fire-red-asr-greedy-search-decoder.h, sherpa-onnx/csrc/offline-fire-red-asr-model-config.cc, sherpa-onnx/csrc/offline-fire-red-asr-model-config.h, sherpa-onnx/csrc/offline-fire-red-asr-model-meta-data.h, sherpa-onnx/csrc/offline-fire-red-asr-model.cc, sherpa-onnx/csrc/offline-fire-red-asr-model.h, sherpa-onnx/csrc/offline-model-config.cc, sherpa-onnx/csrc/offline-model-config.h, sherpa-onnx/csrc/offline-recognizer-fire-red-asr-impl.h, sherpa-onnx/csrc/offline-recognizer-impl.cc, sherpa-onnx/python/csrc/CMakeLists.txt, sherpa-onnx/python/csrc/offline-fire-red-asr-model-config.cc, sherpa-onnx/python/csrc/offline-fire-red-asr-model-config.h, sherpa-onnx/python/csrc/offline-model-config.cc, sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
1. Build sherpa-onnx from source
2. Download a model
```bash
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16.tar.bz2
tar xvf sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16.tar.bz2
rm sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16.tar.bz2
```
3. Run it with a binary compiled from C++
```bash
./build/bin/sherpa-onnx-offline \
--fire-red-asr-encoder=./sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/encoder.int8.onnx \
--fire-red-asr-decoder=./sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/decoder.int8.onnx \
--tokens=./sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/tokens.txt \
./sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16/test_wavs/0.wav
```
4. Run it with Python API
```bash
python3 …
```
=> Add C++ and Python API for FireRedASR AED models

scripts/kokoro/v1.0/run.sh
=> Fix kokoro lexicon.

python-api-examples/speaker-identification-with-vad-non-streaming-asr.py
Fix that speaker-identification-with-vad-non-streaming-asr.py does not support the sense_voice ASR model. (#1883)
=> speaker-identification-with-vad-non-streaming-asr.py Lack of support for sense_voice.

c-api-examples/vad-whisper-c-api.c
Reduce vad-whisper-c-api.c example code.
The current code uses a repeated while loop code (two sections of while) to process the tail data.
```cpp
while(..) {
}
while(..) {
}
```
And the optimized early calculation of total_size can circulate less each calculation amount and improve efficiency.
So I reduce sherpa-onnx/c-api-examples/vad-whisper-c-api.c some codes.
This change is exactly the same as these PRs: https://github.com/k2-fsa/sherpa-onnx/pull/1510 and https://github.com/k2-fsa/sherpa-onnx/pull/1742
=> Reduce vad-whisper-c-api example code.

scripts/export_bpe_vocab.py
Fix #1901 
Also refactored the `sentencepiece` function names.
=> Fix #1901: UnicodeEncodeError running export_bpe_vocab.py

.github/scripts/test-offline-tts.sh, .github/workflows/windows-x64.yaml, .github/workflows/windows-x86.yaml, sherpa-onnx/csrc/offline-whisper-greedy-search-decoder.cc
Fixes #1900 
Now the released windows artifacts also contain TTS-related stuff.
=> Fix publishing pre-built windows libraries

.gitignore, sherpa-onnx/csrc/offline-recognizer-whisper-impl.h, sherpa-onnx/csrc/text-utils-test.cc
Fixing Whisper Model Token Normalization UTF8 characters issues.  
Adding more unit tests for the RemoveInvalidUtf8Sequences.
Issue reported [here](https://github.com/k2-fsa/sherpa-onnx/pull/1452)
The summary of the issue: all normalization works for the text in the result, however, it was not applied to tokens, causing JNI exception.
=> Fixing Whisper Model Token Normalization

nodejs-examples/README.md, nodejs-examples/package.json, nodejs-examples/test-online-paraformer-microphone-mic.js
Add the example of using `mic` to get the mic phone audio stream and better formatting.    https://www.npmjs.com/package/mic
This PR can solve the Mac M1 audio compatibility issue.
Sample output:
```bash
=== Automated Speech Recognition ===
Current Session #1
Time: 8:44:46 PM
------------------------
Recognized Sentences:
[8:44:43 PM] 1. it's so great three result is great great 她还支持中文
[8:44:46 PM] 2. 很厉
------------------------
Recognizing: 真的很厉害太厉害
```
I tested it on my Mac M1, worked well with [SOX](https://sourceforge.net/projects/sox/)
=> feat: add mic example for better compatibility

.github/workflows/aarch64-linux-gnu-shared.yaml, CMakeLists.txt, build-aarch64-linux-gnu.sh, cmake/onnxruntime-linux-aarch64-gpu.cmake
See also https://github.com/k2-fsa/sherpa-onnx/pull/1630
The pre-built onnxruntime libs are provided by the community using the following command:
```bash
./build.sh --build_shared_lib --config Release --update \
--build --parallel --use_cuda \
--cuda_home /usr/local/cuda \
--cudnn_home /usr/lib/aarch64-linux-gnu 2>&1 | tee my-log.txt
```
See also https://github.com/microsoft/onnxruntime/discussions/11226
info about the board:
```
Software part of jetson-stats 4.3.1 - (c) 2024, Raffaello Bonghi
Model: NVIDIA Jetson Orin Nano Engineering Reference Developer Kit Super - Jetpack 6.2 [L4T 36.4.3]
NV Power Mode[1]: 25W
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
- P-Number: p3767-0003
- Module: NVIDIA Jetson Orin Nano (8GB ram)
Platform:
- Distribution: Ubuntu 22.04 Jammy …
```
=> Add onnxruntime 1.18.1 for Linux aarch64 GPU

scripts/go/sherpa_onnx.go
fix the error while building like:
github.com\k2-fsa\sherpa-onnx-go-windows@v1.10.45\sherpa_onnx.go:1431:2: type [268435456]_Ctype_struct_SherpaOnnxOfflineSpeakerDiarizationSegment too large
=> change [1<<28] to [1<<10], to fix build issues on GOARCH=386

.github/workflows/build-wheels-aarch64-rknn.yaml, .github/workflows/linux.yaml, .github/workflows/rknn-linux-aarch64.yaml, sherpa-onnx/csrc/online-model-config.cc
You can find pre-built wheels at
- https://k2-fsa.github.io/sherpa/onnx/rk-npu-cn.html
- https://k2-fsa.github.io/sherpa/onnx/rk-npu.html
To install it, please use
```bash
pip uninstall -y sherpa-onnx
pip install sherpa-onnx -f https://k2-fsa.github.io/sherpa/onnx/rk-npu-cn.html
pip install sherpa-onnx -f https://k2-fsa.github.io/sherpa/onnx/rk-npu.html
```
=> Build wheels for rknn linux aarch64

sherpa-onnx/csrc/offline-recognizer-whisper-impl.h, sherpa-onnx/csrc/offline-whisper-decoder.h, sherpa-onnx/csrc/offline-whisper-greedy-search-decoder.cc, sherpa-onnx/csrc/offline-whisper-greedy-search-decoder.h
Otherwise, it spends lots of time in the loop if the EOT token is not predicted.
=> Limit number of tokens per second for whisper.

.gitignore, sherpa-onnx/c-api/c-api.cc, sherpa-onnx/c-api/c-api.h, sherpa-onnx/csrc/wave-reader.cc, sherpa-onnx/csrc/wave-writer.cc, sherpa-onnx/csrc/wave-writer.h
in same case , the api can be useful :
- a tts server which  sent  wave  output to its client  and  not  do not need to save a tmp file to filesystem。
=> c-api add wave write to buffer.

.github/scripts/test-offline-speech-denoiser.sh, .github/workflows/linux.yaml, .github/workflows/macos.yaml, README.md, cmake/kaldi-native-fbank.cmake, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/offline-speech-denoiser-gtcrn-impl.h, sherpa-onnx/csrc/offline-speech-denoiser-gtcrn-model-config.cc, sherpa-onnx/csrc/offline-speech-denoiser-gtcrn-model-config.h, sherpa-onnx/csrc/offline-speech-denoiser-gtcrn-model-meta-data.h, sherpa-onnx/csrc/offline-speech-denoiser-gtcrn-model.cc, sherpa-onnx/csrc/offline-speech-denoiser-gtcrn-model.h, sherpa-onnx/csrc/offline-speech-denoiser-impl.cc, sherpa-onnx/csrc/offline-speech-denoiser-impl.h, sherpa-onnx/csrc/offline-speech-denoiser-model-config.cc, sherpa-onnx/csrc/offline-speech-denoiser-model-config.h, sherpa-onnx/csrc/offline-speech-denoiser.cc, sherpa-onnx/csrc/offline-speech-denoiser.h, sherpa-onnx/csrc/offline-tts-kokoro-model-meta-data.h, sherpa-onnx/csrc/sherpa-onnx-offline-denoiser.cc
See also
https://github.com/Xiaobin-Rong/gtcrn
CC @yuyun2000 @Xiaobin-Rong
```bash
cd /path/to/sherpa-onnx
mkdir build
cd build
cmake ..
make
```
```bash
cd /path/to/sherpa-onnx
curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/speech-enhancement-models/gtcrn_simple.onnx
curl -SL -O https://github.com/k2-fsa/sherpa-onnx/releases/download/speech-enhancement-models/speech_with_noise.wav
```
```bash
ls -lh gtcrn_simple.onnx
-rw-r--r--  1 fangjun  staff   523K Mar 10 12:55 gtcrn_simple.onnx
```
```
cd /path/to/sherpa-onnx
./build/bin/sherpa-onnx-offline-denoiser \
--debug=1 \
--speech-denoiser-gtcrn-model=./gtcrn_simple.onnx \
--input-wav=./speech_with_noise.wav \
--output-wav=./enhanced_speech_16k.wav
```
https://github.com/user-attachments/assets/97792ba4-8378-40de-810b-113 …
=> Add C++ runtime for speech enhancement GTCRN models

.github/workflows/export-vocos.yaml, scripts/vocos/README.md, scripts/vocos/add_meta_data.py, scripts/vocos/run.sh, scripts/vocos/test.py
You can download it from https://github.com/k2-fsa/sherpa-onnx/releases/tag/vocoder-models
| | Hifigan V2|vocos|
|---|---|---|
|onnx file size| 3.58 MB |51.4MB|
|CPU RTF|0.071|0.038| 
The RTF is tested on my MacBook pro
using [scripts/vocos/test.py](https://github.com/k2-fsa/sherpa-onnx/blob/vocoder-models/scripts/vocos/run.sh). The log output is
```
{'language': 'English', 'voice': 'en-us', 'pad_id': '0', 'model_type': 'matcha-tts', 'has_espeak': '1', 'jieba': '0', 'sample_rate': '22050', 'maintainer': 'k2-fsa', 'n_speakers': '1', 'model_author': 'icefall', 'version': '1', 'dataset_url': 'https://keithito.com/LJ-Speech-Dataset/', 'use_eos_bos': '1', 'dataset': 'LJ Speech', 'num_ode_steps': '3'}
----------matcha----------
NodeArg(name='x', type='tensor(int64)', shape=['N', 'L']) …
```
=> Export vocos to sherpa-onnx

.github/workflows/aarch64-linux-gnu-shared.yaml, CMakeLists.txt, build-aarch64-linux-gnu.sh, cmake/onnxruntime-linux-aarch64-gpu.cmake
See also https://github.com/k2-fsa/sherpa-onnx/pull/1914
Info about the board used to build the onnxruntime
```
Software part of jetson-stats 4.2.4 - (c) 2024, Raffaello Bonghi
Jetpack： 6.0 [L4T 36.3.0]
Hardware:
- P-Number: p3767-0000
- Module: NVIDIA Jetson Orin NX (16GB ram)
Platform:
- Distribution: Ubuntu 22.04 Jammy Jellyfish
- Release: 5.15.136-tegra
jtop:
- Version: 4.2.4
- Service: Active
Libraries:
- CUDA: 12.2.140
- cuDNN: 8.9.4.25
- TensorRT: 8.6.2.3
- VPI: 3.1.5
- Vulkan: 1.3.204
- OpenCV: 4.8.0 - with CUDA: NO
```
Thanks to @litao-zhx for providing the pre-built onnxruntime libs.
---
You can download pre-built sherpa-onnx libs at
https://github.com/k2-fsa/sherpa-onnx/releases/tag/v1.11.1
=> Support cuda12 and cudnn8 for Linux aarch64.

mfc-examples/README.md
Fix build script: add 'cd build' after 'mkdir build' to ensure the correct working directory for CMake
=> Fix build script

sherpa-onnx/csrc/CMakeLists.txt
Hi,
This PR is in reference to the issue: https://github.com/k2-fsa/sherpa-onnx/issues/1541
The current cmake logic does not handle the case where ONNX runtime is pre-installed and static linking is used.
The proposed solution modifies the `sherpa-onnx/csrc/CMakeLists.txt` file.
```cmake
if((BUILD_SHARED_LIBS OR SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE) AND NOT DEFINED onnxruntime_lib_files)
target_link_libraries(sherpa-onnx-core onnxruntime)
else()
target_link_libraries(sherpa-onnx-core ${onnxruntime_lib_files})
```
The modified conditioning allows linking to the pre-installed ONNX Runtime when `BUILD_SHARED_LIBS` is True or when `SHERPA_ONNX_USE_PRE_INSTALLED_ONNXRUNTIME_IF_AVAILABLE` is set. This prevents build failures caused by missing onnxruntime_lib_files in static …
=> fix static linking

.github/scripts/test-offline-ctc.sh, .github/scripts/test-python.sh, .github/workflows/export-dophin-ctc-to-onnx.yaml, .github/workflows/linux.yaml, .github/workflows/macos.yaml, CMakeLists.txt, python-api-examples/offline-dolphin-ctc-decode-files.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/offline-ctc-model.cc, sherpa-onnx/csrc/offline-ctc-model.h, sherpa-onnx/csrc/offline-dolphin-model-config.cc, sherpa-onnx/csrc/offline-dolphin-model-config.h, sherpa-onnx/csrc/offline-dolphin-model-meta-data.h, sherpa-onnx/csrc/offline-dolphin-model.cc, sherpa-onnx/csrc/offline-dolphin-model.h, sherpa-onnx/csrc/offline-model-config.cc, sherpa-onnx/csrc/offline-model-config.h, sherpa-onnx/csrc/offline-recognizer-ctc-impl.h, sherpa-onnx/csrc/offline-recognizer-impl.cc, sherpa-onnx/csrc/offline-sense-voice-model-config.h, sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/rknn/silero-vad-model-rknn.h, sherpa-onnx/python/csrc/CMakeLists.txt, sherpa-onnx/python/csrc/offline-dolphin-model-config.cc, sherpa-onnx/python/csrc/offline-dolphin-model-config.h, sherpa-onnx/python/csrc/offline-model-config.cc, sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
Support models from https://github.com/DataoceanAI/Dolphin
Note that only the CTC head is supported. We don't support its attention decoder.
Fixes #2083
CC @DataoceanAI @MXuer @hotbaby
Download a model from
- [sherpa-onnx-dolphin-base-ctc-multi-lang-int8-2025-04-02.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-dolphin-base-ctc-multi-lang-int8-2025-04-02.tar.bz2)
- [sherpa-onnx-dolphin-base-ctc-multi-lang-2025-04-02.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-dolphin-base-ctc-multi-lang-2025-04-02.tar.bz2)
- [sherpa-onnx-dolphin-small-ctc-multi-lang-int8-2025-04-02.tar.bz2](https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherp …
=> Add C++ and Python API for Dolphin CTC models

sherpa-onnx/csrc/offline-transducer-modified-beam-search-decoder.cc, sherpa-onnx/csrc/offline-transducer-modified-beam-search-decoder.h
I noticed that for offline transducer strict_mode is True when traversing ContextGraph, but for online non-strict mode is used (see #638 ).
What is the rationale behind this?
In my testing, when using strict_mode the decoder sometimes "gets stuck" in the final state of the hotword graph, penalizing all tokens after the hotword. In other words, if we have sentence "he is my friend" and hotwords list contains "he", then sometimes decoder output is just "he" and remainder of the sentence is truncated. This is typically happens if weight is too large, but I would still consider such behaviour undesirable for ASR (not keyword spotter). 
This PR proposes to disable strict hotword matching mode for offline transducer. 
Also it introduces new variable, so that later this mode can be made …
=> Disable strict hotword matching mode for offline transducer

cmake/cmake_extension.py, setup.py, sherpa-onnx/csrc/parse-options.cc
- make sure the defaults in `cmake/cmake_extension.py` variable `extra_cmake_args` can be overriden by `cmake_args` from `${SHERPA_ONNX_CMAKE_ARGS}` env variable
- fix a bug in `sherpa-onnx/csrc/parse-options.cc` which appears when using `-DSHERPA_ONNX_ENABLE_CHECK=ON`
=> cmake build, configurable from env

sherpa-onnx/python/sherpa_onnx/offline_recognizer.py
Dither is critical for accuracy in real life
=> Expose dither in python API

sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-recognizer.cc, sherpa-onnx/csrc/online-recognizer.h, sherpa-onnx/python/csrc/online-recognizer.cc, sherpa-onnx/python/csrc/sherpa-onnx.cc, sherpa-onnx/python/sherpa_onnx/__init__.py, sherpa-onnx/python/sherpa_onnx/online_recognizer.py
I've noticed a potential issue in streaming-transducer code. 
In the case of an endpoint following and empty segment, 
the prev. 2 tokens in predictor are reset to 2x blank symbol.
But, the encoder states are kept.
It seems more logical to reset BOTH the encoder states and the prev. 
blank symbols (i.e. to effectively start the decoding from scratch).
If the prev. 2 tokens are kept, the encoder states are also kept.
Would you agree too ?
K.
// I've tested it with custom encoder, recognizing a 16min long czech fairy tale from youtube.
// It has behaved normally, but I am not sure, how often there were 2 endpoints in a row,
// with no speech in between.
=> online-transducer: reset the encoder toghter with 2 previous output symbols (non-blank)

sherpa-onnx/csrc/kokoro-multi-lang-lexicon.cc
=> Fix punctuations for kokoro tts 1.1-zh.

sherpa-onnx/csrc/offline-recognizer-transducer-nemo-impl.h, sherpa-onnx/csrc/offline-transducer-nemo-model.cc, sherpa-onnx/csrc/offline-transducer-nemo-model.h
See also #2180 
1. Build sherpa-onnx
2. Download a model from https://github.com/k2-fsa/sherpa-onnx/releases/tag/asr-models
For example
```
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8.tar.bz2
tar xvf sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8.tar.bz2
```
3. Run it
```
./build/bin/sherpa-onnx-offline \
--encoder=./sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/encoder.int8.onnx \
--decoder=./sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/decoder.int8.onnx \
--joiner=./sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/joiner.int8.onnx \
--tokens=./sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/tokens.txt \
--model-type=nemo_transducer \
./sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8/test_wavs/0.wav
```
The output on my mac is
Info about my …
=> Add C++ runtime for parakeet-tdt-0.6b-v2.

cxx-api-examples/CMakeLists.txt, cxx-api-examples/dolphin-ctc-cxx-api.cc, cxx-api-examples/fire-red-asr-cxx-api.cc, cxx-api-examples/moonshine-cxx-api.cc, cxx-api-examples/sense-voice-cxx-api.cc, cxx-api-examples/sense-voice-simulate-streaming-microphone-cxx-api.cc, cxx-api-examples/sense-voice-with-hr-cxx-api.cc, cxx-api-examples/sherpa-display.h, cxx-api-examples/streaming-zipformer-cxx-api.cc, cxx-api-examples/streaming-zipformer-rtf-cxx-api.cc, cxx-api-examples/streaming-zipformer-with-hr-cxx-api.cc, cxx-api-examples/whisper-cxx-api.cc, python-api-examples/simulate-streaming-sense-voice-microphone.py, sherpa-onnx/c-api/cxx-api.cc, sherpa-onnx/c-api/cxx-api.h, sherpa-onnx/csrc/homophone-replacer.cc
```bash
cd sherpa-onnx
mkdir build
cd build
cmake ..
make
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/silero_vad.onnx
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/asr-models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2
tar xvf sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2
rm sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17.tar.bz2
./bin/sense-voice-simulate-streaming-microphone-cxx-api
```
=> Add C++ example for streaming ASR with SenseVoice.

sherpa-onnx/csrc/online-recognizer.cc, sherpa-onnx/csrc/online-recognizer.h, sherpa-onnx/csrc/online-websocket-server-impl.cc
is_final=true means an endpoint is detected.
is_eof=true means all received samples have been processed by the server.
=> Support sending is_eof for online websocket server.

.github/workflows/build-wheels-aarch64-rknn.yaml
Many users have reported that the pre-built sherpa-onnx wheels for RK NPU do not work on Ubuntu 20.04 with some errors like below:
After some debugging, we find that
```
cd sherpa_onnx-1.12.0.data/data/bin
strings sherpa-onnx | grep GLIBC
GLIBC_2.17
GLIBC_2.32
GLIBC_2.34
GLIBC_2.27
GLIBC_2.29
GLIBCXX_3.4.20
GLIBCXX_3.4.17
GLIBCXX_3.4.26
GLIBCXX_3.4.19
GLIBCXX_3.4.29
GLIBCXX_3.4.18
GLIBCXX_3.4.11
GLIBCXX_3.4.9
GLIBCXX_3.4.14
GLIBCXX_3.4.30
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.15
GLIBCXX_3.4
```
while the `librknnrt.so` we are using depends only on lower versions of glibc and glibcxx
```bash
strings librknnrt.so | grep GLIBC
GLIBC_2.17
GLIBCXX_3.4.20
GLIBCXX_3.4.18
GLIBCXX_3.4.9
GLIBCXX_3.4.11
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.22
GLIBCXX_3.4.21
GLIBCXX_3.4
```
After using this …
=> Fix building rknn wheels

.github/workflows/export-spleeter-to-onnx.yaml, cmake/cmake_extension.py, scripts/spleeter/convert_to_torch.py, scripts/spleeter/export_onnx.py, scripts/spleeter/separate.py, scripts/spleeter/separate_onnx.py, scripts/spleeter/unet.py, sherpa-onnx/csrc/CMakeLists.txt, sherpa-onnx/csrc/offline-source-separation-impl.cc, sherpa-onnx/csrc/offline-source-separation-impl.h, sherpa-onnx/csrc/offline-source-separation-model-config.cc, sherpa-onnx/csrc/offline-source-separation-model-config.h, sherpa-onnx/csrc/offline-source-separation-spleeter-impl.h, sherpa-onnx/csrc/offline-source-separation-spleeter-model-config.cc, sherpa-onnx/csrc/offline-source-separation-spleeter-model-config.h, sherpa-onnx/csrc/offline-source-separation-spleeter-model-meta-data.h, sherpa-onnx/csrc/offline-source-separation-spleeter-model.cc, sherpa-onnx/csrc/offline-source-separation-spleeter-model.h, sherpa-onnx/csrc/offline-source-separation.cc, sherpa-onnx/csrc/offline-source-separation.h, sherpa-onnx/csrc/offline-speech-denoiser-gtcrn-model-meta-data.h, sherpa-onnx/csrc/sherpa-onnx-offline-denoiser.cc, sherpa-onnx/csrc/sherpa-onnx-offline-source-separation.cc, sherpa-onnx/csrc/wave-reader.cc, sherpa-onnx/csrc/wave-reader.h, sherpa-onnx/csrc/wave-writer.cc, sherpa-onnx/csrc/wave-writer.h, wasm/speech-enhancement/app-speech-enhancement.js
```bash
cd sherpa-onnx
mkdir build
cd build
cmake ..
make
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/source-separation-models/sherpa-onnx-spleeter-2stems-fp16.tar.bz2
tar xvf sherpa-onnx-spleeter-2stems-fp16.tar.bz2
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/source-separation-models/qi-feng-le-zh.wav
wget https://github.com/k2-fsa/sherpa-onnx/releases/download/source-separation-models/audio_example.wav
```
```bash
./bin/sherpa-onnx-offline-source-separation \
--spleeter-vocals=sherpa-onnx-spleeter-2stems-fp16/vocals.fp16.onnx \
--spleeter-accompaniment=sherpa-onnx-spleeter-2stems-fp16/accompaniment.fp16.onnx \
--num-threads=2 \
--debug=0 \
--input-wav=audio_example.wav \ …
```
=> Add C++ runtime for spleeter about source separation

sherpa-onnx/csrc/offline-source-separation-impl.cc
`./build-android-arm64-v8a.sh`
Build fails for this. So I added headers
=> Add include headers for __ANDROID_API__,__OHOS__

.github/workflows/build-wheels-aarch64-rknn.yaml
Convert rknn wheels to be compatible with `manylinux_aarch64_2_27_aarch64`.
=> repair rknn wheels

.github/workflows/export-piper.yaml, scripts/piper/.gitignore, scripts/piper/add_meta_data.py, scripts/piper/dynamic_quantization.py, scripts/piper/generate.py, scripts/piper/generate.sh.in, scripts/piper/generate_samples.py.in, sherpa-onnx/python/csrc/offline-tts-vits-model-config.cc
You can find the exported piper tts models at
https://k2-fsa.github.io/sherpa/onnx/tts/all/index.html
For each model, there are samples for each speaker.
=> Add scripts for exporting Piper TTS models to sherpa-onnx

cmake/sherpa-onnx-shared.pc.in
修复了C++链接错误，添加-lsherpa-onnx-cxx-api
=> 修复了C++链接错误，添加-lsherpa-onnx-cxx-api：Update sherpa-onnx-shared.pc.in

go-api-examples/real-time-speech-recognition-from-microphone/go.mod, go-api-examples/real-time-speech-recognition-from-microphone/main.go, nodejs-addon-examples/test_asr_non_streaming_whisper.js, nodejs-examples/test-offline-whisper.js
It uses https://github.com/gen2brain/malgo to replace portaudio-go.
malgo uses https://github.com/mackron/miniaudio and works on linux, macos, windows, etc.
Many users have issues with portaudio-go on windows and linux.
=> Remove portaudio-go in Go API examples.

sherpa-onnx/csrc/features.cc, sherpa-onnx/csrc/features.h, sherpa-onnx/csrc/online-ctc-model.h, sherpa-onnx/csrc/online-recognizer-ctc-impl.h, sherpa-onnx/csrc/online-stream.cc, sherpa-onnx/csrc/online-zipformer2-ctc-model.cc, sherpa-onnx/csrc/online-zipformer2-ctc-model.h, sherpa-onnx/csrc/sherpa-onnx-microphone.cc
CC @yuekaizhang  @mtdxc
Support models from https://github.com/k2-fsa/icefall/blob/master/egs/multi_zh-hans/ASR/RESULTS.md#streaming-with-ctc-head
Download a CTC onnx model from
https://hf-mirror.com/pingzxy/icefall-asr-multi-zh-hans-zipformer-large-onnx/tree/main
Note: This model supports only Chinese.
```bash
wget https://hf-mirror.com/pingzxy/icefall-asr-multi-zh-hans-zipformer-large-onnx/resolve/main/ctc-epoch-99-avg-1-chunk-16-left-128.int8.onnx
wget https://hf-mirror.com/pingzxy/icefall-asr-multi-zh-hans-zipformer-large-onnx/resolve/main/tokens.txt
```
Now run it with
```bash
#!/usr/bin/env bash
./build/bin/sherpa-onnx \
--zipformer2-ctc-model=./t/ctc-epoch-99-avg-1-chunk-16-left-128.int8.onnx \
--tokens=./t/tokens.txt \
./path/to/some/test.wav
```
=> Support zipformer CTC ASR with whisper features.

sherpa-onnx/csrc/features.cc, sherpa-onnx/csrc/online-recognizer-transducer-impl.h, sherpa-onnx/csrc/online-transducer-model.h, sherpa-onnx/csrc/online-zipformer2-transducer-model.cc, sherpa-onnx/csrc/online-zipformer2-transducer-model.h
CC @yuekaizhang 
Support models from https://github.com/k2-fsa/icefall/blob/master/egs/multi_zh-hans/ASR/RESULTS.md#multi-chinese-datasets-char-based-training-results-streaming-on-zipformer-large-model
Download  onnx model  files from
https://hf-mirror.com/pingzxy/icefall-asr-multi-zh-hans-zipformer-large-onnx/tree/main
```
wget https://hf-mirror.com/pingzxy/icefall-asr-multi-zh-hans-zipformer-large-onnx/resolve/main/encoder-epoch-99-avg-1-chunk-16-left-128.int8.onnx
wget https://hf-mirror.com/pingzxy/icefall-asr-multi-zh-hans-zipformer-large-onnx/resolve/main/decoder-epoch-99-avg-1-chunk-16-left-128.onnx
wget https://hf-mirror.com/pingzxy/icefall-asr-multi-zh-hans-zipformer-large-onnx/resolve/main/joiner-epoch-99-avg-1-chunk-16-left-128.int8.onnx
wget …
```
=> Support Zipformer transducer ASR with whisper features.

scripts/nemo/canary/export_onnx_180m_flash.py, scripts/nemo/canary/test_180m_flash.py
Using dynamo export fixes issues related to the decoder producing garbage output on long sequences.
In order to use dynamo, the example input needs to match the runtime inputs, therefore requiring fixed size input_ids at runtime and (to avoid 0/1 specialization) a larger decoder_mems_list in the example. opset_version 18 is required for dynamo export. 
Additionally, I enabled int8 exports for the decoder, it seems to work just fine in my testing, while being twice as fast. The fp16 exports seem to be broken, though, this has been the case before as well.
Fixes https://github.com/k2-fsa/sherpa-onnx/issues/2148
=> fix(canary): use dynamo export, single input_ids and avoid 0/1 specialization

.github/workflows/export-kitten.yaml, .github/workflows/generate-tts-samples.yaml, scripts/apk/generate-tts-apk-script.py, scripts/kitten-tts/mini_v0_1/add_meta_data.py, scripts/kitten-tts/mini_v0_1/convert_opset.py, scripts/kitten-tts/mini_v0_1/generate_samples.py, scripts/kitten-tts/mini_v0_1/generate_tokens.py, scripts/kitten-tts/mini_v0_1/generate_voices_bin.py, scripts/kitten-tts/mini_v0_1/run.sh, scripts/kitten-tts/mini_v0_1/show.py, scripts/kitten-tts/mini_v0_1/test.py, scripts/kitten-tts/nano_v0_2/generate_samples.py
See also https://k2-fsa.github.io/sherpa/onnx/tts/all/English/kitten-mini-en-v0_1.html
=> Export KittenTTS mini v0.1 to sherpa-onnx
